package exam_management_syatem.db;

import java.util.ArrayList;
import java.util.List;

public class QuestionBankPart1 {

    public static class QuestionItem {
        public final String question;
        public final String optA;
        public final String optB;
        public final String optC;
        public final String optD;
        public final String correct;
        public final String difficulty;

        public QuestionItem(String question, String optA, String optB, String optC, String optD, String correct, String difficulty) {
            this.question = question;
            this.optA = optA;
            this.optB = optB;
            this.optC = optC;
            this.optD = optD;
            this.correct = correct;
            this.difficulty = difficulty;
        }
    }

    public static List<QuestionItem> getJavaQuestions() {
        List<QuestionItem> list = new ArrayList<>();
        // 20 EASY
        list.add(new QuestionItem("What is the size of an int primitive type in Java?", "16-bit", "32-bit", "64-bit", "8-bit", "32-bit", "EASY"));
        list.add(new QuestionItem("Which keyword is used to create a subclass in Java?", "implements", "inherits", "extends", "instanceof", "extends", "EASY"));
        list.add(new QuestionItem("Which access modifier makes a member accessible only within its own class?", "protected", "private", "public", "default", "private", "EASY"));
        list.add(new QuestionItem("Which collection interface allows duplicate elements and maintains insertion order?", "Set", "Map", "List", "TreeSet", "List", "EASY"));
        list.add(new QuestionItem("What is the root class of all classes in Java?", "java.lang.System", "java.lang.Object", "java.lang.Class", "java.lang.Root", "java.lang.Object", "EASY"));
        list.add(new QuestionItem("Which keyword prevents a class from being inherited in Java?", "static", "abstract", "final", "const", "final", "EASY"));
        list.add(new QuestionItem("Which package is automatically imported into every Java compilation unit?", "java.util", "java.io", "java.lang", "java.net", "java.lang", "EASY"));
        list.add(new QuestionItem("What is the default value of a boolean variable in Java when declared as an instance field?", "true", "false", "null", "0", "false", "EASY"));
        list.add(new QuestionItem("Which exception is thrown when dividing an integer by zero in Java?", "NullPointerException", "ArithmeticException", "NumberFormatException", "IllegalArgumentException", "ArithmeticException", "EASY"));
        list.add(new QuestionItem("Which method must be implemented by any class implementing the Runnable interface?", "start()", "run()", "execute()", "init()", "run()", "EASY"));
        list.add(new QuestionItem("Which keyword is used to call a superclass constructor from a subclass constructor?", "this", "super", "parent", "base", "super", "EASY"));
        list.add(new QuestionItem("Which loop construct in Java is guaranteed to execute its body at least once?", "for loop", "while loop", "do-while loop", "enhanced for loop", "do-while loop", "EASY"));
        list.add(new QuestionItem("What is the return type of the hashCode() method in java.lang.Object?", "long", "int", "short", "byte", "int", "EASY"));
        list.add(new QuestionItem("Which interface does ArrayList implement to allow fast index-based element access?", "RandomAccess", "Serializable", "Cloneable", "FastAccess", "RandomAccess", "EASY"));
        list.add(new QuestionItem("Which operator is used to test if an object is an instance of a specific class or interface?", "typeof", "instanceof", "isInstance", "isa", "instanceof", "EASY"));
        list.add(new QuestionItem("What does the JVM bytecode execution engine use to convert bytecode into native machine instructions at runtime?", "Pre-compiler", "JIT Compiler", "Assembler", "Linker", "JIT Compiler", "EASY"));
        list.add(new QuestionItem("Which string class in Java is thread-safe due to synchronized methods?", "StringBuilder", "StringBuffer", "String", "StringTokenizer", "StringBuffer", "EASY"));
        list.add(new QuestionItem("Which statement terminates the current loop iteration and proceeds to the next iteration?", "break", "continue", "return", "exit", "continue", "EASY"));
        list.add(new QuestionItem("What is the size of a double in Java?", "32-bit", "64-bit", "128-bit", "16-bit", "64-bit", "EASY"));
        list.add(new QuestionItem("Which keyword is used to declare an interface in Java?", "class", "interface", "implements", "protocol", "interface", "EASY"));

        // 20 MEDIUM
        list.add(new QuestionItem("What happens when an exception is thrown in a try block that has both a catch block and a finally block?", "finally is skipped", "finally executes regardless of catch outcome", "catch executes after finally", "program halts immediately", "finally executes regardless of catch outcome", "MEDIUM"));
        list.add(new QuestionItem("What is the purpose of the transient keyword in Java serialization?", "Prevents garbage collection", "Marks field to be skipped during serialization", "Makes field immutable", "Shares field across threads", "Marks field to be skipped during serialization", "MEDIUM"));
        list.add(new QuestionItem("Which memory area in the JVM is shared across all application threads?", "Java Stack", "Program Counter (PC) Register", "Heap Memory", "Native Method Stack", "Heap Memory", "MEDIUM"));
        list.add(new QuestionItem("In Java 8+, how does HashMap handle high collision buckets once the treeify threshold of 8 is reached?", "Converts bucket list into a Red-Black Tree", "Rehashes entire table into a B-Tree", "Drops collided entries", "Converts to a linked hash set", "Converts bucket list into a Red-Black Tree", "MEDIUM"));
        list.add(new QuestionItem("What contract must hold if two objects are equal according to the equals() method?", "Their hash codes must also be equal", "Their references must be identical", "They must have the same memory address", "Their hash codes must be different", "Their hash codes must also be equal", "MEDIUM"));
        list.add(new QuestionItem("What is the primary difference between Comparable and Comparator interfaces?", "Comparable specifies external ordering; Comparator specifies natural ordering", "Comparable specifies natural ordering; Comparator specifies custom external ordering", "Comparable is in java.util; Comparator is in java.lang", "Comparator cannot be used with lambda expressions", "Comparable specifies natural ordering; Comparator specifies custom external ordering", "MEDIUM"));
        list.add(new QuestionItem("What does the volatile keyword ensure when applied to a field in multi-threaded Java?", "Atomicity of compound operations", "Visibility of writes across threads without caching", "Mutual exclusion synchronization", "Object immutability", "Visibility of writes across threads without caching", "MEDIUM"));
        list.add(new QuestionItem("Which functional interface in java.util.function accepts an argument of type T and returns a boolean?", "Consumer<T>", "Supplier<T>", "Predicate<T>", "Function<T, R>", "Predicate<T>", "MEDIUM"));
        list.add(new QuestionItem("What is the result of invoking intern() on a String object?", "Returns string from string pool or adds it if absent", "Converts string to lowercase", "Creates a deep clone on heap", "Deletes string from memory", "Returns string from string pool or adds it if absent", "MEDIUM"));
        list.add(new QuestionItem("Which garbage collector in modern Java divides the heap into equal-sized regions and predicts pauses?", "Serial GC", "Parallel GC", "G1 Garbage Collector", "CMS Collector", "G1 Garbage Collector", "MEDIUM"));
        list.add(new QuestionItem("What is type erasure in Java generics?", "Generics information is removed at runtime by the compiler", "All types become Object at compile time", "Generics are translated to C pointers", "Generic types are checked exclusively by the JVM at runtime", "Generics information is removed at runtime by the compiler", "MEDIUM"));
        list.add(new QuestionItem("Why is String immutable in Java?", "Security, caching hash codes, and thread-safety", "To prevent subclassing", "Because JVM cannot reallocate memory", "To conform to C standard", "Security, caching hash codes, and thread-safety", "MEDIUM"));
        list.add(new QuestionItem("What does Thread.join() accomplish when called on thread t from main thread?", "Terminates thread t", "Suspends calling thread until thread t finishes execution", "Resumes thread t", "Interrupts thread t", "Suspends calling thread until thread t finishes execution", "MEDIUM"));
        list.add(new QuestionItem("Which Java class loader loads the core Java API classes located in the rt.jar or java.base module?", "Application ClassLoader", "Extension ClassLoader", "Bootstrap ClassLoader", "System ClassLoader", "Bootstrap ClassLoader", "MEDIUM"));
        list.add(new QuestionItem("What happens if a custom checked exception is thrown inside a method without a throws clause or try-catch?", "Warning only", "Compilation error", "JVM ignores it at runtime", "Converted to Error automatically", "Compilation error", "MEDIUM"));
        list.add(new QuestionItem("Which collection class in java.util.concurrent allows lock-free concurrent reads and partitioned writes?", "Hashtable", "SynchronizedMap", "ConcurrentHashMap", "TreeMap", "ConcurrentHashMap", "MEDIUM"));
        list.add(new QuestionItem("What is the default capacity of a newly created ArrayList in Java?", "0 initially, grows to 10 on first add", "16", "32", "1", "0 initially, grows to 10 on first add", "MEDIUM"));
        list.add(new QuestionItem("Which stream intermediate operation is used to transform elements from one type to another?", "filter", "map", "reduce", "forEach", "map", "MEDIUM"));
        list.add(new QuestionItem("What is the effect of marking a method as synchronized in an instance context?", "Locks the Class object", "Acquires monitor lock on the 'this' instance", "Disables context switching", "Pins the thread to a CPU core", "Acquires monitor lock on the 'this' instance", "MEDIUM"));
        list.add(new QuestionItem("In Java NIO, which channel component allows non-blocking checking of multiple channels for readiness?", "Buffer", "Selector", "Pipe", "Charset", "Selector", "MEDIUM"));

        // 10 HARD
        list.add(new QuestionItem("What does the Java Memory Model (JMM) 'happens-before' relationship guarantee?", "Operations always execute in alphabetical order", "Memory writes by one thread are guaranteed to be visible to another thread", "Instruction pipelining is disabled", "Garbage collection will not pause threads", "Memory writes by one thread are guaranteed to be visible to another thread", "HARD"));
        list.add(new QuestionItem("How does the ForkJoinPool manage work distribution among its worker threads?", "Round-robin scheduling", "Work-stealing algorithm using double-ended queues (deques)", "Priority queue assignment", "Spinlock polling", "Work-stealing algorithm using double-ended queues (deques)", "HARD"));
        list.add(new QuestionItem("Under what condition does the JVM throw an OutOfMemoryError: Metaspace?", "When the heap space is exhausted by user objects", "When class metadata exceeds Metaspace limits or leaks classloaders", "When stack frames overflow recursion limit", "When direct byte buffers run out of memory", "When class metadata exceeds Metaspace limits or leaks classloaders", "HARD"));
        list.add(new QuestionItem("What is the purpose of PhantomReference in java.lang.ref package?", "To make objects resurrectable", "To execute pre-mortem cleanup actions after object has been finalized", "To keep objects strongly reachable forever", "To speed up serialization", "To execute pre-mortem cleanup actions after object has been finalized", "HARD"));
        list.add(new QuestionItem("What optimization does Escape Analysis in the HotSpot C2 compiler enable?", "Lock coarsening and stack allocation of objects that do not escape method scope", "Dead code elimination only", "Disabling JIT compilation", "Converting recursive methods to loops", "Lock coarsening and stack allocation of objects that do not escape method scope", "HARD"));
        list.add(new QuestionItem("What mechanism prevents the 'ABA problem' in Java atomic classes like AtomicStampedReference?", "ThreadLocal storage", "Pairing the reference with an integer stamp/version counter", "Using biased locking", "Disabling hardware CAS instructions", "Pairing the reference with an integer stamp/version counter", "HARD"));
        list.add(new QuestionItem("How does biased locking optimize synchronized blocks in HotSpot JVM?", "By delegating locks to the OS kernel directly", "By biasing the lock towards the first thread that acquires it, avoiding atomic operations", "By forcing every thread to spinlock", "By removing the monitor entirely", "By biasing the lock towards the first thread that acquires it, avoiding atomic operations", "HARD"));
        list.add(new QuestionItem("In java.lang.invoke, what is the key advantage of MethodHandle over traditional reflection?", "MethodHandle has no security checks", "MethodHandle can be inlined and optimized by the JIT compiler like direct bytecodes", "MethodHandle works without bytecode verification", "MethodHandle only supports private methods", "MethodHandle can be inlined and optimized by the JIT compiler like direct bytecodes", "HARD"));
        list.add(new QuestionItem("What is the primary operational characteristic of the ZGC (Z Garbage Collector)?", "Generational full stop-the-world pauses", "Sub-millisecond pause times using colored pointers and load barriers", "Stop-the-world mark and sweep", "Compaction only on explicit System.gc()", "Sub-millisecond pause times using colored pointers and load barriers", "HARD"));
        list.add(new QuestionItem("In Project Loom (Java 21+), how do Virtual Threads differ from OS Platform Threads?", "Virtual Threads do not have a call stack", "Virtual Threads are lightweight user-mode threads managed by JVM and mounted on carrier threads", "Virtual Threads run in separate OS processes", "Virtual Threads cannot perform network I/O", "Virtual Threads are lightweight user-mode threads managed by JVM and mounted on carrier threads", "HARD"));

        return list;
    }

    public static List<QuestionItem> getDataStructuresQuestions() {
        List<QuestionItem> list = new ArrayList<>();
        // 20 EASY
        list.add(new QuestionItem("Which data structure operates on a Last In First Out (LIFO) basis?", "Queue", "Stack", "Array", "Linked List", "Stack", "EASY"));
        list.add(new QuestionItem("Which data structure operates on a First In First Out (FIFO) basis?", "Stack", "Queue", "Binary Tree", "Graph", "Queue", "EASY"));
        list.add(new QuestionItem("What is the time complexity of accessing an array element by its index?", "O(n)", "O(log n)", "O(1)", "O(n^2)", "O(1)", "EASY"));
        list.add(new QuestionItem("Which node in a singly linked list points to null?", "Head node", "Tail node", "Root node", "Intermediate node", "Tail node", "EASY"));
        list.add(new QuestionItem("What is the maximum number of children a node can have in a binary tree?", "1", "2", "3", "Unlimited", "2", "EASY"));
        list.add(new QuestionItem("What operation adds an element to the top of a stack?", "Pop", "Push", "Peek", "Enqueue", "Push", "EASY"));
        list.add(new QuestionItem("What operation removes an element from the front of a queue?", "Push", "Pop", "Dequeue", "Enqueue", "Dequeue", "EASY"));
        list.add(new QuestionItem("In a doubly linked list, how many pointers does each internal node maintain?", "1", "2", "3", "4", "2", "EASY"));
        list.add(new QuestionItem("What is a tree node that has no children called?", "Interior node", "Leaf node", "Root node", "Branch node", "Leaf node", "EASY"));
        list.add(new QuestionItem("Which data structure uses a key-value mapping for fast lookups?", "Stack", "Hash Table", "Queue", "Heap", "Hash Table", "EASY"));
        list.add(new QuestionItem("What is the height of a tree with only one root node?", "0", "1", "-1", "2", "0", "EASY"));
        list.add(new QuestionItem("What is the worst-case time complexity of searching for an element in an unsorted array of size n?", "O(1)", "O(log n)", "O(n)", "O(n log n)", "O(n)", "EASY"));
        list.add(new QuestionItem("Which linear data structure does not require contiguous memory allocation?", "Array", "Linked List", "Vector", "Bitset", "Linked List", "EASY"));
        list.add(new QuestionItem("In a circular queue with capacity N, how is the next rear position calculated?", "(rear + 1) % N", "rear + 1", "rear % (N + 1)", "rear - 1", "(rear + 1) % N", "EASY"));
        list.add(new QuestionItem("What type of graph has edges that point in a specific direction?", "Undirected Graph", "Directed Graph (Digraph)", "Bipartite Graph", "Complete Graph", "Directed Graph (Digraph)", "EASY"));
        list.add(new QuestionItem("What data structure is commonly used to implement recursion iteratively?", "Queue", "Stack", "Hash Set", "Priority Queue", "Stack", "EASY"));
        list.add(new QuestionItem("In a complete binary tree of depth d, what is the maximum number of nodes at level i (where root is at level 0)?", "i", "2^i", "2^(i+1)", "i^2", "2^i", "EASY"));
        list.add(new QuestionItem("Which traversal visits the root node before its left and right subtrees?", "Inorder", "Preorder", "Postorder", "Level-order", "Preorder", "EASY"));
        list.add(new QuestionItem("Which data structure is best suited for implementing a priority queue?", "Stack", "Binary Heap", "Unsorted Array", "Circular Linked List", "Binary Heap", "EASY"));
        list.add(new QuestionItem("What happens when push is performed on a full fixed-size stack?", "Underflow", "Overflow", "Segmentation fault", "Deadlock", "Overflow", "EASY"));

        // 20 MEDIUM
        list.add(new QuestionItem("In a Binary Search Tree (BST), which tree traversal produces keys in sorted ascending order?", "Preorder", "Inorder", "Postorder", "Breadth-First", "Inorder", "MEDIUM"));
        list.add(new QuestionItem("What is the worst-case time complexity of searching in an unbalanced Binary Search Tree of size n?", "O(1)", "O(log n)", "O(n)", "O(n log n)", "O(n)", "MEDIUM"));
        list.add(new QuestionItem("What balance factor condition defines an AVL tree node as balanced?", "Height of left and right subtrees differ by at most 1", "Left and right subtrees have equal keys", "All leaves are at exact same level", "Node has exactly two children", "Height of left and right subtrees differ by at most 1", "MEDIUM"));
        list.add(new QuestionItem("Which collision resolution technique in hash tables stores collided elements in linked lists at each bucket?", "Linear Probing", "Quadratic Probing", "Separate Chaining", "Double Hashing", "Separate Chaining", "MEDIUM"));
        list.add(new QuestionItem("What is the primary drawback of linear probing in open-addressing hash tables?", "High pointer overhead", "Primary Clustering", "Secondary Clustering", "Inability to resize", "Primary Clustering", "MEDIUM"));
        list.add(new QuestionItem("In a max-heap, what relationship holds between parent node P and its children C?", "P >= C", "P <= C", "P == C", "Left Child <= P <= Right Child", "P >= C", "MEDIUM"));
        list.add(new QuestionItem("What is the time complexity of the build-heap operation on an array of n elements?", "O(n log n)", "O(n)", "O(n^2)", "O(log n)", "O(n)", "MEDIUM"));
        list.add(new QuestionItem("Which graph representation is more memory-efficient for a sparse graph with V vertices and E edges?", "Adjacency Matrix", "Adjacency List", "Incidence Matrix", "Complete Matrix", "Adjacency List", "MEDIUM"));
        list.add(new QuestionItem("What algorithm is used to detect cycles in a linked list using two pointers moving at different speeds?", "Dijkstra Algorithm", "Floyd's Cycle-Finding Algorithm (Tortoise and Hare)", "Kruskal Algorithm", "Boyer-Moore Voting", "Floyd's Cycle-Finding Algorithm (Tortoise and Hare)", "MEDIUM"));
        list.add(new QuestionItem("What is the time complexity of deleting a node given a pointer to it in a doubly linked list?", "O(n)", "O(1)", "O(log n)", "O(n^2)", "O(1)", "MEDIUM"));
        list.add(new QuestionItem("In a B-Tree of order m, what is the maximum number of children each internal node can have?", "m", "m - 1", "2m", "m / 2", "m", "MEDIUM"));
        list.add(new QuestionItem("Which data structure is optimal for finding the prefix common to a collection of strings?", "Red-Black Tree", "Trie (Prefix Tree)", "Min-Heap", "Disjoint Set", "Trie (Prefix Tree)", "MEDIUM"));
        list.add(new QuestionItem("What is the worst-case lookup time in a Red-Black Tree with n nodes?", "O(1)", "O(log n)", "O(n)", "O(n log n)", "O(log n)", "MEDIUM"));
        list.add(new QuestionItem("What is the space complexity of an adjacency matrix for a graph with V vertices?", "O(V + E)", "O(V^2)", "O(E^2)", "O(V log V)", "O(V^2)", "MEDIUM"));
        list.add(new QuestionItem("What properties must hold for a binary tree to be considered a Full Binary Tree?", "Every node has 0 or 2 children", "Every node has exactly 1 child", "All leaf nodes are at same depth", "Number of nodes is odd", "Every node has 0 or 2 children", "MEDIUM"));
        list.add(new QuestionItem("Which data structure supports union and find operations in nearly constant amortized time?", "Segment Tree", "Disjoint Set Union (Union-Find)", "Fenwick Tree", "Treap", "Disjoint Set Union (Union-Find)", "MEDIUM"));
        list.add(new QuestionItem("In an AVL tree, what rotation is required when a node is inserted into the right subtree of the left child (LR case)?", "Single Left", "Single Right", "Left-Right Double Rotation", "Right-Left Double Rotation", "Left-Right Double Rotation", "MEDIUM"));
        list.add(new QuestionItem("What data structure can compute range sum queries and point updates in O(log n) time with minimal code?", "Fenwick Tree (Binary Indexed Tree)", "Splay Tree", "Skip List", "KD-Tree", "Fenwick Tree (Binary Indexed Tree)", "MEDIUM"));
        list.add(new QuestionItem("How many null pointers are present in a binary tree with n nodes?", "n", "n + 1", "2n", "n - 1", "n + 1", "MEDIUM"));
        list.add(new QuestionItem("In open addressing with double hashing, what must be true about the second hash function h2(k)?", "Must evaluate to 0", "Must never evaluate to 0 and must be coprime to table size", "Must be identical to first hash function", "Must return a floating-point value", "Must never evaluate to 0 and must be coprime to table size", "MEDIUM"));

        // 10 HARD
        list.add(new QuestionItem("What is the amortized time complexity of operations in a Splay Tree?", "O(1)", "O(log n)", "O(n)", "O(sqrt(n))", "O(log n)", "HARD"));
        list.add(new QuestionItem("How does a Fibonacci Heap achieve O(1) amortized time for decrease-key operations?", "By cascading cuts and maintaining a lazy collection of heap-ordered trees", "By full tree balancing on every operation", "By using a B-Tree internally", "By preventing tree growth", "By cascading cuts and maintaining a lazy collection of heap-ordered trees", "HARD"));
        list.add(new QuestionItem("What is the space and time trade-off achieved by a Bloom Filter?", "Zero false positives with O(n) space", "Space-efficient probabilistic membership testing with possible false positives but no false negatives", "Lossless data compression", "Deterministic key sorting", "Space-efficient probabilistic membership testing with possible false positives but no false negatives", "HARD"));
        list.add(new QuestionItem("What is the worst-case search complexity in a Skip List with n elements?", "O(log n)", "O(n)", "O(1)", "O(n log n)", "O(n)", "HARD"));
        list.add(new QuestionItem("In a Treap, what two data structure invariants are simultaneously maintained?", "Binary Search Tree on keys and Heap order on random priorities", "B-Tree on keys and Stack on priorities", "AVL balance on keys and Queue on priorities", "Trie on keys and Hash table on priorities", "Binary Search Tree on keys and Heap order on random priorities", "HARD"));
        list.add(new QuestionItem("What is the purpose of a persistent data structure?", "Data is saved to SSD on every write", "Preserves previous versions of itself when modified", "Prevents concurrent access", "Only allows read-only operations", "Preserves previous versions of itself when modified", "HARD"));
        list.add(new QuestionItem("In a B+ Tree, why are range queries significantly faster than in a standard B-Tree?", "All keys are kept in internal nodes", "All leaf nodes are linked sequentially in a doubly/singly linked list", "Leaf nodes are stored in main memory only", "B+ Trees do not use disk blocks", "All leaf nodes are linked sequentially in a doubly/singly linked list", "HARD"));
        list.add(new QuestionItem("What is the time complexity to find the Lowest Common Ancestor (LCA) in a tree of size n using binary lifting after O(n log n) preprocessing?", "O(1)", "O(log n)", "O(sqrt(n))", "O(log^2 n)", "O(log n)", "HARD"));
        list.add(new QuestionItem("In a Disjoint Set Union (DSU) structure using both path compression and union by rank, what is the amortized time per operation?", "O(log n)", "O(alpha(n)) where alpha is inverse Ackermann function", "O(1) strictly", "O(log* n)", "O(alpha(n)) where alpha is inverse Ackermann function", "HARD"));
        list.add(new QuestionItem("What spatial partitioning data structure recursively divides k-dimensional space using axis-aligned hyperplanes?", "Suffix Automaton", "k-d Tree", "Link-Cut Tree", "Cartesian Tree", "k-d Tree", "HARD"));

        return list;
    }

    public static List<QuestionItem> getAlgorithmsQuestions() {
        List<QuestionItem> list = new ArrayList<>();
        // 20 EASY
        list.add(new QuestionItem("What is the time complexity of Binary Search on a sorted array of size n?", "O(1)", "O(log n)", "O(n)", "O(n log n)", "O(log n)", "EASY"));
        list.add(new QuestionItem("Which sorting algorithm has an average time complexity of O(n^2)?", "Merge Sort", "Quick Sort", "Bubble Sort", "Heap Sort", "Bubble Sort", "EASY"));
        list.add(new QuestionItem("Which algorithmic paradigm solves a problem by breaking it into independent subproblems, solving them recursively, and combining their results?", "Greedy Approach", "Divide and Conquer", "Dynamic Programming", "Backtracking", "Divide and Conquer", "EASY"));
        list.add(new QuestionItem("What is the worst-case time complexity of Linear Search?", "O(1)", "O(log n)", "O(n)", "O(n^2)", "O(n)", "EASY"));
        list.add(new QuestionItem("Which sorting algorithm repeatedly selects the minimum element from the unsorted portion and places it at the beginning?", "Insertion Sort", "Selection Sort", "Quick Sort", "Radix Sort", "Selection Sort", "EASY"));
        list.add(new QuestionItem("What is the best-case time complexity of Bubble Sort when optimized with a swapped flag on an already sorted array?", "O(n^2)", "O(n log n)", "O(n)", "O(1)", "O(n)", "EASY"));
        list.add(new QuestionItem("Which search algorithm uses a queue to explore nodes level by level?", "Depth-First Search (DFS)", "Breadth-First Search (BFS)", "Binary Search", "Linear Search", "Breadth-First Search (BFS)", "EASY"));
        list.add(new QuestionItem("Which search algorithm uses a stack or recursion to explore as deep as possible along each branch before backtracking?", "Breadth-First Search (BFS)", "Depth-First Search (DFS)", "Uniform Cost Search", "A* Search", "Depth-First Search (DFS)", "EASY"));
        list.add(new QuestionItem("What is the space complexity of iterative Binary Search?", "O(log n)", "O(n)", "O(1)", "O(n log n)", "O(1)", "EASY"));
        list.add(new QuestionItem("What requirement must be met before executing Binary Search on an array?", "Array elements must be unique", "Array must be sorted", "Array size must be a power of 2", "Array must contain only integers", "Array must be sorted", "EASY"));
        list.add(new QuestionItem("Which notation represents the tight asymptotic bound of an algorithm's running time?", "Big-O (O)", "Big-Omega (Omega)", "Big-Theta (Theta)", "Little-o", "Big-Theta (Theta)", "EASY"));
        list.add(new QuestionItem("Which sorting algorithm builds the final sorted array one item at a time by inserting each element into its proper position?", "Selection Sort", "Insertion Sort", "Merge Sort", "Heap Sort", "Insertion Sort", "EASY"));
        list.add(new QuestionItem("What is the worst-case time complexity of Merge Sort?", "O(n^2)", "O(n log n)", "O(n)", "O(log n)", "O(n log n)", "EASY"));
        list.add(new QuestionItem("In asymptotic analysis, what does Big-O notation describe?", "Lower bound on growth rate", "Upper bound on growth rate", "Exact tight bound", "Average execution time", "Upper bound on growth rate", "EASY"));
        list.add(new QuestionItem("Which algorithm finds the single-source shortest path in an unweighted graph in O(V + E) time?", "Dijkstra Algorithm", "Breadth-First Search (BFS)", "Bellman-Ford Algorithm", "Floyd-Warshall Algorithm", "Breadth-First Search (BFS)", "EASY"));
        list.add(new QuestionItem("Which sorting algorithm is commonly used for small arrays or nearly sorted data due to low overhead?", "Merge Sort", "Insertion Sort", "Heap Sort", "Quick Sort", "Insertion Sort", "EASY"));
        list.add(new QuestionItem("What is the auxiliary space complexity of standard Merge Sort on an array of size n?", "O(1)", "O(log n)", "O(n)", "O(n^2)", "O(n)", "EASY"));
        list.add(new QuestionItem("Which algorithmic approach makes the locally optimal choice at each stage with the hope of finding a global optimum?", "Dynamic Programming", "Greedy Algorithm", "Backtracking", "Branch and Bound", "Greedy Algorithm", "EASY"));
        list.add(new QuestionItem("What is the base case in a recursive algorithm?", "The condition that continues recursion", "The terminating condition that returns without further recursive calls", "The maximum recursion depth", "The memory cleanup step", "The terminating condition that returns without further recursive calls", "EASY"));
        list.add(new QuestionItem("What is the time complexity of finding the maximum element in an unsorted array of size n?", "O(1)", "O(log n)", "O(n)", "O(n log n)", "O(n)", "EASY"));

        // 20 MEDIUM
        list.add(new QuestionItem("What causes the worst-case O(n^2) running time in standard Quick Sort with naive pivot selection?", "Array has random distribution", "Array is already sorted or reverse sorted and pivot is always extreme element", "Array size is even", "Pivot is the exact median", "Array is already sorted or reverse sorted and pivot is always extreme element", "MEDIUM"));
        list.add(new QuestionItem("What is the time complexity of Dijkstra's algorithm implemented with a min-priority queue (binary heap) for a graph with V vertices and E edges?", "O(V^2)", "O(V + E)", "O((V + E) log V)", "O(V * E)", "O((V + E) log V)", "MEDIUM"));
        list.add(new QuestionItem("Why cannot standard Dijkstra's algorithm correctly handle graphs with negative edge weights?", "Priority queue crashes on negative numbers", "Greedy assumption that shortest path cannot be decreased by further extensions fails", "Graph must be acyclic", "Edges must be undirected", "Greedy assumption that shortest path cannot be decreased by further extensions fails", "MEDIUM"));
        list.add(new QuestionItem("Which algorithm solves the single-source shortest path problem in graphs with negative edge weights and detects negative weight cycles?", "Dijkstra Algorithm", "Bellman-Ford Algorithm", "Prim Algorithm", "Kruskal Algorithm", "Bellman-Ford Algorithm", "MEDIUM"));
        list.add(new QuestionItem("What is the running time of Bellman-Ford algorithm on a graph with V vertices and E edges?", "O(V + E)", "O(V * E)", "O(V^3)", "O(E log V)", "O(V * E)", "MEDIUM"));
        list.add(new QuestionItem("Which all-pairs shortest path algorithm uses dynamic programming and runs in O(V^3) time?", "Dijkstra", "Bellman-Ford", "Floyd-Warshall Algorithm", "Johnson Algorithm", "Floyd-Warshall Algorithm", "MEDIUM"));
        list.add(new QuestionItem("What two algorithms are standard for finding a Minimum Spanning Tree (MST) in a connected weighted graph?", "Kruskal and Prim", "Dijkstra and Bellman-Ford", "BFS and DFS", "Kosaraju and Tarjan", "Kruskal and Prim", "MEDIUM"));
        list.add(new QuestionItem("What data structure is essential for Kruskal's algorithm to efficiently check for cycles when adding edges?", "Min-Heap", "Disjoint Set (Union-Find)", "Stack", "Adjacency Matrix", "Disjoint Set (Union-Find)", "MEDIUM"));
        list.add(new QuestionItem("What is the time complexity of computing the 0/1 Knapsack problem with n items and knapsack capacity W using dynamic programming?", "O(n + W)", "O(n * W)", "O(2^n)", "O(W^2)", "O(n * W)", "MEDIUM"));
        list.add(new QuestionItem("Why is the dynamic programming solution to the 0/1 Knapsack problem described as pseudo-polynomial?", "Its running time depends on the numeric value of W, not the number of input bits", "It only works on small arrays", "It has exponential space complexity", "It uses floating point calculations", "Its running time depends on the numeric value of W, not the number of input bits", "MEDIUM"));
        list.add(new QuestionItem("What is the time complexity of the Longest Common Subsequence (LCS) problem for two strings of lengths m and n using dynamic programming?", "O(m + n)", "O(m * n)", "O(2^(m+n))", "O(m log n)", "O(m * n)", "MEDIUM"));
        list.add(new QuestionItem("Which linear-time non-comparison based sorting algorithm sorts integers by processing individual digits?", "Merge Sort", "Quick Sort", "Radix Sort", "Heap Sort", "Radix Sort", "MEDIUM"));
        list.add(new QuestionItem("What is the running time of Counting Sort on an array of n integers with maximum value k?", "O(n log k)", "O(n + k)", "O(n * k)", "O(k log n)", "O(n + k)", "MEDIUM"));
        list.add(new QuestionItem("What is the lower bound on comparison-based sorting algorithms in the worst case?", "Omega(n)", "Omega(n log n)", "Omega(n^2)", "Omega(log n)", "Omega(n log n)", "MEDIUM"));
        list.add(new QuestionItem("Which string matching algorithm preprocesses the pattern to create a failure function (pi table) and matches in O(n + m) time?", "Rabin-Karp", "Knuth-Morris-Pratt (KMP)", "Boyer-Moore", "Aho-Corasick", "Knuth-Morris-Pratt (KMP)", "MEDIUM"));
        list.add(new QuestionItem("What technique does the Rabin-Karp algorithm use to search for a pattern in text?", "Finite State Automaton", "Rolling Hash", "Suffix Array", "Z-algorithm", "Rolling Hash", "MEDIUM"));
        list.add(new QuestionItem("What is the time complexity of Heap Sort on an array of size n?", "O(n^2)", "O(n log n)", "O(n)", "O(log n)", "O(n log n)", "MEDIUM"));
        list.add(new QuestionItem("Is standard Heap Sort an in-place and stable sorting algorithm?", "In-place but not stable", "Stable but not in-place", "Both in-place and stable", "Neither in-place nor stable", "In-place but not stable", "MEDIUM"));
        list.add(new QuestionItem("Which algorithm finds the strongly connected components (SCCs) of a directed graph using two passes of DFS?", "Tarjan Algorithm", "Kosaraju Algorithm", "Kruskal Algorithm", "Hopcroft-Karp", "Kosaraju Algorithm", "MEDIUM"));
        list.add(new QuestionItem("In divide and conquer, what does the Master Theorem case T(n) = aT(n/b) + f(n) evaluate to when f(n) = O(n^(log_b(a) - epsilon))?", "T(n) = Theta(n^(log_b(a)))", "T(n) = Theta(f(n))", "T(n) = Theta(n log n)", "T(n) = Theta(log n)", "T(n) = Theta(n^(log_b(a)))", "MEDIUM"));

        // 10 HARD
        list.add(new QuestionItem("What is the time complexity of the Aho-Corasick automaton construction for matching a dictionary of patterns?", "O(n * m)", "Linear in the sum of lengths of patterns", "Exponential in pattern count", "O(V^2)", "Linear in the sum of lengths of patterns", "HARD"));
        list.add(new QuestionItem("What is the maximum flow value equal to in a flow network according to the Max-Flow Min-Cut theorem?", "Total capacity of all edges in graph", "Capacity of the minimum s-t cut", "Sum of all incoming edges to target", "Number of augmenting paths", "Capacity of the minimum s-t cut", "HARD"));
        list.add(new QuestionItem("What is the time complexity of the Edmonds-Karp algorithm for maximum flow on a network with V vertices and E edges?", "O(V * E^2)", "O(V^2 * E)", "O(V^3)", "O(E log V)", "O(V * E^2)", "HARD"));
        list.add(new QuestionItem("What algorithm finds maximum cardinality matching in a general (non-bipartite) graph by shrinking odd-length cycles (blossoms)?", "Hopcroft-Karp", "Edmonds' Blossom Algorithm", "Hungarian Algorithm", "Ford-Fulkerson", "Edmonds' Blossom Algorithm", "HARD"));
        list.add(new QuestionItem("What is the complexity class of the Traveling Salesperson Problem (decision version)?", "P", "NP-Complete", "Co-NP only", "Log-space", "NP-Complete", "HARD"));
        list.add(new QuestionItem("What algorithm multiplies two n-digit numbers in O(n^1.585) time using divide and conquer?", "Strassen Algorithm", "Karatsuba Algorithm", "Cooley-Tukey FFT", "Schonhage-Strassen", "Karatsuba Algorithm", "HARD"));
        list.add(new QuestionItem("What algorithm solves all-pairs shortest paths on sparse graphs with negative edge weights faster than Floyd-Warshall by using reweighting?", "Johnson's Algorithm", "Dijkstra's Algorithm", "Karger's Algorithm", "Boruvka's Algorithm", "Johnson's Algorithm", "HARD"));
        list.add(new QuestionItem("What is the time complexity of the Fast Fourier Transform (FFT) for multiplying two polynomials of degree n?", "O(n^2)", "O(n log n)", "O(n)", "O(n^1.5)", "O(n log n)", "HARD"));
        list.add(new QuestionItem("What randomized algorithm computes a global minimum cut in an undirected connected graph by edge contractions in O(V^2) per trial?", "Karger's Algorithm", "Metropolis-Hastings", "Las Vegas Algorithm", "Monte Carlo Tree Search", "Karger's Algorithm", "HARD"));
        list.add(new QuestionItem("What is the worst-case time complexity of Median-of-Medians selection algorithm to find the k-th smallest element in an unsorted array?", "O(n^2)", "O(n log n)", "O(n)", "O(log n)", "O(n)", "HARD"));

        return list;
    }

    public static List<QuestionItem> getDbmsQuestions() {
        List<QuestionItem> list = new ArrayList<>();
        // 20 EASY
        list.add(new QuestionItem("What does the acronym DBMS stand for?", "Data Base Metric System", "Database Management System", "Distributed Base Management Service", "Data Binary Management System", "Database Management System", "EASY"));
        list.add(new QuestionItem("What does SQL stand for?", "Structured Query Language", "Sequential Query Language", "Standard Query Logic", "System Query Link", "Structured Query Language", "EASY"));
        list.add(new QuestionItem("Which SQL clause is used to filter records returned by a SELECT query?", "ORDER BY", "GROUP BY", "WHERE", "HAVING", "WHERE", "EASY"));
        list.add(new QuestionItem("Which key uniquely identifies each record in a database table?", "Foreign Key", "Primary Key", "Candidate Key", "Super Key", "Primary Key", "EASY"));
        list.add(new QuestionItem("What does the ACID acronym stand for in database transactions?", "Atomicity, Consistency, Isolation, Durability", "Action, Clarity, Integrity, Distribution", "Accuracy, Concurrency, Indexing, Data", "Access, Control, Identification, Delegation", "Atomicity, Consistency, Isolation, Durability", "EASY"));
        list.add(new QuestionItem("Which SQL command is used to add new rows to a table?", "UPDATE", "INSERT INTO", "ALTER TABLE", "SELECT", "INSERT INTO", "EASY"));
        list.add(new QuestionItem("Which SQL command removes all rows from a table quickly without logging individual row deletions?", "DELETE", "DROP", "TRUNCATE", "REMOVE", "TRUNCATE", "EASY"));
        list.add(new QuestionItem("Which SQL command is used to modify existing column definitions in a table?", "UPDATE", "ALTER TABLE", "MODIFY TABLE", "CHANGE", "ALTER TABLE", "EASY"));
        list.add(new QuestionItem("What type of relationship is established by a Foreign Key referencing a Primary Key?", "Referential Integrity", "Functional Dependency", "Entity Completeness", "Domain Validation", "Referential Integrity", "EASY"));
        list.add(new QuestionItem("Which aggregate function returns the total count of rows satisfying a condition?", "SUM()", "COUNT()", "AVG()", "TOTAL()", "COUNT()", "EASY"));
        list.add(new QuestionItem("Which clause is used to sort the result-set in SQL?", "ORDER BY", "GROUP BY", "SORT BY", "ARRANGE BY", "ORDER BY", "EASY"));
        list.add(new QuestionItem("What keyword is used to eliminate duplicate rows from a query result?", "UNIQUE", "DISTINCT", "DIFFERENT", "SEPARATE", "DISTINCT", "EASY"));
        list.add(new QuestionItem("Which constraint ensures that all values in a column are distinct?", "NOT NULL", "CHECK", "UNIQUE", "DEFAULT", "UNIQUE", "EASY"));
        list.add(new QuestionItem("What is a row in a relational database table also known as in relational model theory?", "Attribute", "Tuple", "Domain", "Relation", "Tuple", "EASY"));
        list.add(new QuestionItem("What is a column in a relational database table also known as in relational model theory?", "Tuple", "Attribute", "Entity", "Degree", "Attribute", "EASY"));
        list.add(new QuestionItem("Which SQL command completely deletes a table and its structure from the database?", "TRUNCATE TABLE", "DELETE TABLE", "DROP TABLE", "REMOVE TABLE", "DROP TABLE", "EASY"));
        list.add(new QuestionItem("Which operator in SQL is used for pattern matching using wildcards like '%' and '_'?", "EQUALS", "LIKE", "MATCH", "CONTAINS", "LIKE", "EASY"));
        list.add(new QuestionItem("Which join returns only rows where there is a match in both joined tables?", "LEFT JOIN", "RIGHT JOIN", "INNER JOIN", "FULL OUTER JOIN", "INNER JOIN", "EASY"));
        list.add(new QuestionItem("Which SQL clause is used to filter groups created by GROUP BY?", "WHERE", "HAVING", "LIMIT", "FILTER", "HAVING", "EASY"));
        list.add(new QuestionItem("What is a virtual table based on the result-set of an SQL statement called?", "Snapshot", "View", "Index", "Cursor", "View", "EASY"));

        // 20 MEDIUM
        list.add(new QuestionItem("In database normalization, which normal form eliminates repeating groups and ensures atomic column values?", "First Normal Form (1NF)", "Second Normal Form (2NF)", "Third Normal Form (3NF)", "Boyce-Codd Normal Form (BCNF)", "First Normal Form (1NF)", "MEDIUM"));
        list.add(new QuestionItem("Which normal form requires the table to be in 1NF and have no partial functional dependencies on candidate keys?", "Second Normal Form (2NF)", "Third Normal Form (3NF)", "BCNF", "4NF", "Second Normal Form (2NF)", "MEDIUM"));
        list.add(new QuestionItem("What dependency must be eliminated for a relation to satisfy Third Normal Form (3NF)?", "Partial Dependency", "Transitive Dependency", "Multivalued Dependency", "Join Dependency", "Transitive Dependency", "MEDIUM"));
        list.add(new QuestionItem("How does Boyce-Codd Normal Form (BCNF) differ from standard 3NF?", "BCNF allows transitive dependencies", "In BCNF, for every functional dependency X -> Y, X must be a superkey", "BCNF only applies to numeric columns", "BCNF does not require 1NF", "In BCNF, for every functional dependency X -> Y, X must be a superkey", "MEDIUM"));
        list.add(new QuestionItem("Which transaction isolation level prevents dirty reads, non-repeatable reads, and phantom reads?", "Read Uncommitted", "Read Committed", "Repeatable Read", "Serializable", "Serializable", "MEDIUM"));
        list.add(new QuestionItem("What phenomenon occurs when a transaction reads data written by another uncommitted concurrent transaction?", "Phantom Read", "Non-Repeatable Read", "Dirty Read", "Lost Update", "Dirty Read", "MEDIUM"));
        list.add(new QuestionItem("What index structure is most widely used in relational databases for range queries and equality lookups?", "Hash Index", "B+ Tree Index", "Bitmap Index", "R-Tree Index", "B+ Tree Index", "MEDIUM"));
        list.add(new QuestionItem("In two-phase locking (2PL), what happens during the shrinking phase?", "Locks are acquired", "Locks are released and no new locks can be acquired", "Transaction commits immediately", "Deadlock is detected", "Locks are released and no new locks can be acquired", "MEDIUM"));
        list.add(new QuestionItem("What does Write-Ahead Logging (WAL) ensure in database crash recovery?", "Logs are written to disk after dirty pages are flushed", "Log records describing changes are written to disk before data pages are updated", "No logs are kept in memory", "Rollback is executed on every query", "Log records describing changes are written to disk before data pages are updated", "MEDIUM"));
        list.add(new QuestionItem("In the ARIES recovery algorithm, which phase scans the log forward from checkpoint to reconstruct the state at failure?", "Analysis Phase", "Redo Phase", "Undo Phase", "Commit Phase", "Redo Phase", "MEDIUM"));
        list.add(new QuestionItem("What is a Clustered Index?", "An index that alters the physical order of data rows on disk to match index key", "An index stored across multiple cluster nodes", "A secondary index with duplicate pointers", "An in-memory hash table", "An index that alters the physical order of data rows on disk to match index key", "MEDIUM"));
        list.add(new QuestionItem("How many clustered indexes can a relational database table have?", "One", "Two", "Unlimited", "Depends on number of columns", "One", "MEDIUM"));
        list.add(new QuestionItem("What does Multi-Version Concurrency Control (MVCC) achieve in modern DBMS engines?", "Readers do not block writers, and writers do not block readers", "Prevents all deadlocks completely", "Disables database transactions", "Forces single-threaded execution", "Readers do not block writers, and writers do not block readers", "MEDIUM"));
        list.add(new QuestionItem("What is the role of a Database Cursor?", "A mechanism to navigate and process query result rows one by one", "A GUI pointing device", "A type of table lock", "A backup snapshot", "A mechanism to navigate and process query result rows one by one", "MEDIUM"));
        list.add(new QuestionItem("What type of lock prevents other transactions from modifying or reading a resource?", "Shared Lock (S-Lock)", "Exclusive Lock (X-Lock)", "Intent Shared Lock", "Update Lock", "Exclusive Lock (X-Lock)", "MEDIUM"));
        list.add(new QuestionItem("What is the CAP Theorem trade-off in distributed database systems?", "Only two out of Consistency, Availability, and Partition Tolerance can be guaranteed", "Cost, Accuracy, Performance trade-off", "Centralization, Atomicity, Privacy", "Cache, Array, Persistence", "Only two out of Consistency, Availability, and Partition Tolerance can be guaranteed", "MEDIUM"));
        list.add(new QuestionItem("What does a trigger in a relational database do?", "Executes automatically in response to specified events like INSERT/UPDATE/DELETE", "Accelerates query compilation", "Creates a database backup", "Enforces network firewall rules", "Executes automatically in response to specified events like INSERT/UPDATE/DELETE", "MEDIUM"));
        list.add(new QuestionItem("What is a phantom read in concurrent database transactions?", "Transaction re-reads data and finds new rows inserted by a committed concurrent transaction", "Transaction reads deleted data", "Data is corrupted on disk", "Lock timeout occurs", "Transaction re-reads data and finds new rows inserted by a committed concurrent transaction", "MEDIUM"));
        list.add(new QuestionItem("Which relational algebra operation corresponds to selecting specific columns from a relation?", "Selection (sigma)", "Projection (pi)", "Cartesian Product (x)", "Join (bowtie)", "Projection (pi)", "MEDIUM"));
        list.add(new QuestionItem("Which relational algebra operation corresponds to filtering tuples based on a predicate condition?", "Selection (sigma)", "Projection (pi)", "Rename (rho)", "Division (/)", "Selection (sigma)", "MEDIUM"));

        // 10 HARD
        list.add(new QuestionItem("What is Strict Two-Phase Locking (S2PL) and what anomaly does it eliminate?", "All exclusive locks held until transaction end; eliminates cascading aborts", "Locks acquired all at once; eliminates deadlocks", "Locks released immediately; maximizes concurrency", "No locking used; relies on rollback", "All exclusive locks held until transaction end; eliminates cascading aborts", "HARD"));
        list.add(new QuestionItem("How does the Wait-Die deadlock prevention scheme handle lock conflicts between transactions T_old and T_young?", "T_old waits for T_young; T_young dies if requesting lock held by T_old", "T_old dies immediately", "Both transactions roll back", "System pauses all transactions", "T_old waits for T_young; T_young dies if requesting lock held by T_old", "HARD"));
        list.add(new QuestionItem("In query optimization, what does System R dynamic programming search for when ordering multi-table joins?", "Left-deep join trees using cost-based estimations", "Bushy join trees with random selection", "Cartesian products first", "Single table scans only", "Left-deep join trees using cost-based estimations", "HARD"));
        list.add(new QuestionItem("What is the purpose of the compensation log record (CLR) in ARIES crash recovery?", "Logs actions taken during UNDO to prevent re-undoing during repeated crashes", "Logs user passwords", "Backs up index metadata", "Records checkpoint start times", "Logs actions taken during UNDO to prevent re-undoing during repeated crashes", "HARD"));
        list.add(new QuestionItem("What is Snapshot Isolation and what specific concurrency anomaly can it exhibit that Serializable isolation forbids?", "Write Skew anomaly", "Dirty Read anomaly", "Lost Update anomaly", "Phantom Read anomaly", "Write Skew anomaly", "HARD"));
        list.add(new QuestionItem("In PostgreSQL MVCC implementation, what hidden system columns track tuple visibility?", "xmin and xmax", "rowid and ctid", "seq_id and ver_id", "ts_start and ts_end", "xmin and xmax", "HARD"));
        list.add(new QuestionItem("What does the Two-Phase Commit (2PC) protocol ensure in distributed databases, and what is its primary weakness?", "Guarantees distributed atomic commit; vulnerable to blocking if coordinator crashes", "Prevents network latency; allows partial commits", "Eliminates all replication lag", "Guarantees 100% availability during network splits", "Guarantees distributed atomic commit; vulnerable to blocking if coordinator crashes", "HARD"));
        list.add(new QuestionItem("What is the Fifth Normal Form (5NF, Project-Join Normal Form)?", "Eliminates join dependencies not implied by candidate keys", "Eliminates functional dependencies", "Eliminates transitive dependencies", "Requires JSON column storage", "Eliminates join dependencies not implied by candidate keys", "HARD"));
        list.add(new QuestionItem("In columnar storage engines (e.g., Parquet, ClickHouse), what encoding techniques are used for fast aggregations?", "Run-Length Encoding (RLE), Dictionary Encoding, and Bit Packing", "B-Tree hashing only", "AES-256 encryption", "Base64 string encoding", "Run-Length Encoding (RLE), Dictionary Encoding, and Bit Packing", "HARD"));
        list.add(new QuestionItem("What is a semi-join reduction in distributed query processing?", "Sends only distinct join keys to remote site to filter rows before data transfer", "Joins half of the table rows", "Executes join without foreign keys", "Splits table into two fragments", "Sends only distinct join keys to remote site to filter rows before data transfer", "HARD"));

        return list;
    }

    public static List<QuestionItem> getOperatingSystemsQuestions() {
        List<QuestionItem> list = new ArrayList<>();
        // 20 EASY
        list.add(new QuestionItem("What is the core component of an Operating System that manages system resources?", "Shell", "Kernel", "Compiler", "File Explorer", "Kernel", "EASY"));
        list.add(new QuestionItem("What is a process in an operating system?", "A program in execution", "A file stored on disk", "A hardware interrupt", "A CPU register", "A program in execution", "EASY"));
        list.add(new QuestionItem("Which CPU scheduling algorithm gives CPU to the process that arrives first?", "Round Robin", "First-Come, First-Served (FCFS)", "Shortest Job First (SJF)", "Priority Scheduling", "First-Come, First-Served (FCFS)", "EASY"));
        list.add(new QuestionItem("What is the state of a process that is waiting to be assigned to the processor?", "Running", "Ready", "Terminated", "Waiting/Blocked", "Ready", "EASY"));
        list.add(new QuestionItem("What hardware mechanism allows the CPU to temporarily halt current execution and handle an urgent event?", "Context switch", "Interrupt", "System call", "Paging", "Interrupt", "EASY"));
        list.add(new QuestionItem("What is the main advantage of multiprogramming?", "Reduces memory usage", "Increases CPU utilization by having a process ready to execute", "Eliminates deadlocks", "Simplifies software development", "Increases CPU utilization by having a process ready to execute", "EASY"));
        list.add(new QuestionItem("Which component translates high-level system calls from user programs into kernel actions?", "Device Driver", "System Call Interface", "Assembler", "Bootloader", "System Call Interface", "EASY"));
        list.add(new QuestionItem("What is the phenomenon where virtual memory is constantly swapping pages between RAM and disk, causing severe performance degradation?", "Fragmentation", "Thrashing", "Paging", "Spooling", "Thrashing", "EASY"));
        list.add(new QuestionItem("Which memory management technique divides physical memory into fixed-size blocks called frames?", "Segmentation", "Paging", "Dynamic Partitioning", "Overlays", "Paging", "EASY"));
        list.add(new QuestionItem("What is a thread in operating systems?", "A separate program in execution", "The smallest unit of execution within a process (lightweight process)", "A hardware bus line", "A disk sector", "The smallest unit of execution within a process (lightweight process)", "EASY"));
        list.add(new QuestionItem("What is a condition where two or more processes are unable to proceed because each is waiting for the other to release a resource?", "Starvation", "Deadlock", "Livelock", "Race Condition", "Deadlock", "EASY"));
        list.add(new QuestionItem("Which scheduling algorithm allocates a fixed time slice (quantum) to each process in turn?", "Shortest Remaining Time", "Round Robin", "Priority Scheduling", "Multilevel Queue", "Round Robin", "EASY"));
        list.add(new QuestionItem("What is the function of the PCB (Process Control Block)?", "Holds process state, program counter, CPU registers, and scheduling info", "Stores executable binary on disk", "Acts as memory firewall", "Manages disk sectors", "Holds process state, program counter, CPU registers, and scheduling info", "EASY"));
        list.add(new QuestionItem("What system call is used in Unix-like operating systems to create a new process?", "exec()", "fork()", "spawn()", "create()", "fork()", "EASY"));
        list.add(new QuestionItem("What type of software runs in privileged CPU mode (ring 0)?", "User Browser", "OS Kernel", "Text Editor", "Java Virtual Machine", "OS Kernel", "EASY"));
        list.add(new QuestionItem("What is a race condition in concurrent programming?", "Processes compete for network bandwidth", "Outcome depends on the non-deterministic relative order or timing of thread execution", "CPU clock speed increases", "Deadlock occurs instantaneously", "Outcome depends on the non-deterministic relative order or timing of thread execution", "EASY"));
        list.add(new QuestionItem("What is internal fragmentation?", "Free memory blocks scattered between allocated partitions", "Unused memory space within an allocated fixed-size block/page", "Disk sector damage", "Swap file overflow", "Unused memory space within an allocated fixed-size block/page", "EASY"));
        list.add(new QuestionItem("What is the primary function of the Translation Lookaside Buffer (TLB)?", "High-speed hardware cache for page-table lookups", "Disk cache for file transfers", "Interrupt priority handler", "Network packet buffer", "High-speed hardware cache for page-table lookups", "EASY"));
        list.add(new QuestionItem("Which file allocation method uses an index block containing pointers to all disk blocks of a file?", "Contiguous Allocation", "Linked Allocation", "Indexed Allocation", "FAT Allocation", "Indexed Allocation", "EASY"));
        list.add(new QuestionItem("What command interpreter provides the user interface to an operating system?", "Kernel", "Shell", "BIOS", "Compiler", "Shell", "EASY"));

        // 20 MEDIUM
        list.add(new QuestionItem("What are the four Coffman conditions required for a deadlock to occur?", "Mutual Exclusion, Hold and Wait, No Preemption, Circular Wait", "Paging, Segmentation, Swapping, Fragmentation", "Atomic, Consistent, Isolated, Durable", "Read, Write, Execute, Modify", "Mutual Exclusion, Hold and Wait, No Preemption, Circular Wait", "MEDIUM"));
        list.add(new QuestionItem("Which algorithm is used for deadlock avoidance by testing for safe states before allocating resources?", "Peterson's Algorithm", "Banker's Algorithm", "Bakery Algorithm", "Dekker's Algorithm", "Banker's Algorithm", "MEDIUM"));
        list.add(new QuestionItem("In Peterson's algorithm for mutual exclusion between two processes, what two variables are shared?", "flag array and turn variable", "semaphore and mutex", "condition variable and monitor", "counter and queue", "flag array and turn variable", "MEDIUM"));
        list.add(new QuestionItem("What is the difference between a binary semaphore and a counting semaphore?", "Binary takes values 0 or 1; counting can take non-negative integer values representing resource units", "Binary is software only; counting is hardware", "Binary cannot be used in OS kernel", "Counting semaphore has no wait() operation", "Binary takes values 0 or 1; counting can take non-negative integer values representing resource units", "MEDIUM"));
        list.add(new QuestionItem("What is the Belady's Anomaly in page replacement algorithms?", "Increasing the number of page frames causes more page faults (observed in FIFO)", "Decreasing frames speeds up execution", "LRU behaves worse than FIFO", "Optimal algorithm produces worst-case faults", "Increasing the number of page frames causes more page faults (observed in FIFO)", "MEDIUM"));
        list.add(new QuestionItem("Which page replacement algorithm replaces the page that will not be used for the longest period in the future?", "FIFO", "LRU", "Optimal Page Replacement (OPT)", "LFU", "Optimal Page Replacement (OPT)", "MEDIUM"));
        list.add(new QuestionItem("What hardware support is required to implement demand paging with virtual memory?", "Page Fault Interrupt and Valid/Invalid bit in Page Table", "Multiple CPU cores", "SSD storage only", "Direct Memory Access (DMA) controller", "Page Fault Interrupt and Valid/Invalid bit in Page Table", "MEDIUM"));
        list.add(new QuestionItem("What is the purpose of the fork() followed by exec() pattern in Unix?", "fork() duplicates current process; exec() replaces address space with a new program", "fork() terminates process; exec() restarts it", "fork() creates thread; exec() creates process", "fork() allocates memory; exec() frees it", "fork() duplicates current process; exec() replaces address space with a new program", "MEDIUM"));
        list.add(new QuestionItem("What is a zombie process in Unix-like operating systems?", "A process that has finished execution but still has an entry in process table waiting for parent to read exit status", "A process running an infinite loop", "A process that cannot be killed by root", "A malware process", "A process that has finished execution but still has an entry in process table waiting for parent to read exit status", "MEDIUM"));
        list.add(new QuestionItem("What is an orphan process in Unix-like systems and who adopts it?", "A process whose parent terminated; adopted by init (PID 1) or systemd", "A process without CPU time", "A process without memory", "A process killed by SIGKILL", "A process whose parent terminated; adopted by init (PID 1) or systemd", "MEDIUM"));
        list.add(new QuestionItem("How does Inverted Page Table architecture save memory compared to standard hierarchical page tables?", "Maintains one entry per physical frame rather than per virtual page", "Compresses page table using gzip", "Stores page table on disk only", "Eliminates virtual addresses", "Maintains one entry per physical frame rather than per virtual page", "MEDIUM"));
        list.add(new QuestionItem("What is priority inversion and what protocol resolves it in real-time operating systems?", "Low priority holds resource needed by high priority; resolved by Priority Inheritance Protocol", "High priority gets starved; resolved by FIFO", "Tasks switch priorities randomly; resolved by Round Robin", "Threads run concurrently; resolved by mutex", "Low priority holds resource needed by high priority; resolved by Priority Inheritance Protocol", "MEDIUM"));
        list.add(new QuestionItem("What is the difference between monolithic kernel and microkernel architecture?", "Monolithic runs all OS services in kernel space; microkernel runs minimal core in kernel and services in user space", "Monolithic is slower than microkernel", "Microkernel cannot run on x86 hardware", "Monolithic has no drivers", "Monolithic runs all OS services in kernel space; microkernel runs minimal core in kernel and services in user space", "MEDIUM"));
        list.add(new QuestionItem("What mechanism allows hardware devices to transfer data directly to/from system RAM without continuous CPU intervention?", "Spooling", "Direct Memory Access (DMA)", "Polling", "Context Switching", "Direct Memory Access (DMA)", "MEDIUM"));
        list.add(new QuestionItem("In Linux, what is the Completely Fair Scheduler (CFS) based on?", "Red-Black Tree tracking virtual runtime (vruntime) of tasks", "Round Robin queues", "Priority bitmap array", "Random lottery scheduling", "Red-Black Tree tracking virtual runtime (vruntime) of tasks", "MEDIUM"));
        list.add(new QuestionItem("What is the difference between thread-level concurrency in user space (User-level threads) vs kernel space (Kernel-level threads)?", "User threads managed without kernel awareness; blocking system call blocks entire process in user-level threads", "Kernel threads cannot run on multi-core CPUs", "User threads are heavier than kernel threads", "Kernel threads do not support scheduling", "User threads managed without kernel awareness; blocking system call blocks entire process in user-level threads", "MEDIUM"));
        list.add(new QuestionItem("What disk scheduling algorithm moves the arm in one direction serving requests until the end, then reverses direction (elevator algorithm)?", "FCFS", "SSTF", "SCAN", "C-LOOK", "SCAN", "MEDIUM"));
        list.add(new QuestionItem("What is the working set model of a process?", "The set of pages actively referenced by the process in the recent time window Delta", "Total size of executable binary", "Number of open files", "CPU cache lines allocated", "The set of pages actively referenced by the process in the recent time window Delta", "MEDIUM"));
        list.add(new QuestionItem("In Unix file systems, what information does an inode store?", "File metadata (permissions, owner, size, timestamps, block pointers) but not filename", "Filename and full path", "Data block contents directly", "User password", "File metadata (permissions, owner, size, timestamps, block pointers) but not filename", "MEDIUM"));
        list.add(new QuestionItem("What is a spinlock and when is it appropriate to use in an OS kernel?", "A lock where thread loops busy-waiting; appropriate in multi-core systems for very short critical sections", "A lock that sleeps on collision; appropriate for disk I/O", "A user-space mutex only", "A lock used only on single-core CPUs", "A lock where thread loops busy-waiting; appropriate in multi-core systems for very short critical sections", "MEDIUM"));

        // 10 HARD
        list.add(new QuestionItem("How does the Read-Copy-Update (RCU) synchronization mechanism achieve zero-lock overhead for readers in the Linux kernel?", "Readers access data without locks; updates create a new copy and reclaim old memory after a grace period", "Readers use hardware transactional memory", "Disables interrupts during reads", "Converts all reads to atomic instructions", "Readers access data without locks; updates create a new copy and reclaim old memory after a grace period", "HARD"));
        list.add(new QuestionItem("What is the purpose of copy-on-write (COW) optimization during the fork() system call?", "Pages are shared read-only between parent and child until one attempts a write, then duplicated", "Prevents memory allocation completely", "Copies all pages immediately to disk", "Encrypts child address space", "Pages are shared read-only between parent and child until one attempts a write, then duplicated", "HARD"));
        list.add(new QuestionItem("In x86-64 long mode, how many levels of page tables are used for 48-bit virtual address translation?", "2 levels", "3 levels", "4 levels (PML4, PDPT, PD, PT)", "5 levels strictly", "4 levels (PML4, PDPT, PD, PT)", "HARD"));
        list.add(new QuestionItem("What is the Meltdown CPU vulnerability and how does Kernel Page-Table Isolation (KPTI) mitigate it?", "Speculative execution read kernel memory from user space; mitigated by separating user and kernel page tables", "Buffer overflow in stack; mitigated by ASLR", "Race condition in scheduler; mitigated by mutex", "Cache poisoning; mitigated by disabling L1 cache", "Speculative execution read kernel memory from user space; mitigated by separating user and kernel page tables", "HARD"));
        list.add(new QuestionItem("What does the Linux epoll mechanism provide over traditional select() and poll() system calls for network servers?", "O(1) event notification using an in-kernel ready list instead of O(N) linear descriptor scanning", "Multi-threaded disk I/O", "Zero-copy UDP transmission", "Automatic packet decryption", "O(1) event notification using an in-kernel ready list instead of O(N) linear descriptor scanning", "HARD"));
        list.add(new QuestionItem("What is the OOM Killer (Out-of-Memory Killer) in Linux and how does it select a victim process?", "Scores processes based on badness score calculated from memory consumed and oom_score_adj", "Kills the oldest process", "Kills the init process", "Kills processes randomly", "Scores processes based on badness score calculated from memory consumed and oom_score_adj", "HARD"));
        list.add(new QuestionItem("In NUMA (Non-Uniform Memory Access) systems, how does OS memory allocation prevent memory bus bottlenecks?", "NUMA-aware memory allocation policies like node-local allocation and interleaving", "Disables caches across nodes", "Restricts system to single CPU socket", "Routes all traffic through central controller", "NUMA-aware memory allocation policies like node-local allocation and interleaving", "HARD"));
        list.add(new QuestionItem("What is the purpose of cgroups (control groups) and namespaces in Linux containerization (Docker)?", "Namespaces isolate process views (PID, NET, MNT); cgroups enforce resource limits (CPU, MEM, I/O)", "Namespaces compile binaries; cgroups manage disks", "Namespaces provide GUI; cgroups provide networking", "Namespaces handle encryption; cgroups handle logging", "Namespaces isolate process views (PID, NET, MNT); cgroups enforce resource limits (CPU, MEM, I/O)", "HARD"));
        list.add(new QuestionItem("What is a TLB Shootdown in symmetric multiprocessing (SMP) operating systems?", "An inter-processor interrupt (IPI) forcing remote cores to invalidate stale cached TLB entries after page unmapping", "A hardware crash caused by overheating", "A cache miss on instruction fetch", "A context switch between processes", "An inter-processor interrupt (IPI) forcing remote cores to invalidate stale cached TLB entries after page unmapping", "HARD"));
        list.add(new QuestionItem("What does the splice() system call in Linux enable for zero-copy data transfer?", "Transfers data between file descriptors and pipes without copying through user-space memory buffers", "Splits large files into chunks", "Merges two processes into one", "Replaces thread stacks", "Transfers data between file descriptors and pipes without copying through user-space memory buffers", "HARD"));

        return list;
    }
}
