package exam_management_syatem.db;

import java.util.ArrayList;
import java.util.List;
import exam_management_syatem.db.QuestionBankPart1.QuestionItem;

public class QuestionBankPart3 {

    public static List<QuestionItem> getAiQuestions() {
        List<QuestionItem> list = new ArrayList<>();
        // 20 EASY
        list.add(new QuestionItem("Who is widely considered the father of Artificial Intelligence who proposed the famous imitation game?", "Alan Turing", "Charles Babbage", "John von Neumann", "Ada Lovelace", "Alan Turing", "EASY"));
        list.add(new QuestionItem("What test evaluates a machine's ability to exhibit intelligent behavior indistinguishable from a human?", "Turing Test", "Voight-Kampff Test", "Chomsky Test", "Shannon Test", "Turing Test", "EASY"));
        list.add(new QuestionItem("In AI search algorithms, what is an agent that perceives its environment through sensors and acts upon it through actuators?", "Rational Agent", "Passive Sensor", "Finite Automaton", "Parser", "Rational Agent", "EASY"));
        list.add(new QuestionItem("Which search algorithm uses a heuristic function h(n) estimating cost to goal along with path cost g(n)?", "Breadth-First Search", "Depth-First Search", "A* Search", "Uniform Cost Search", "A* Search", "EASY"));
        list.add(new QuestionItem("What search strategy is guaranteed to find the shallowest goal node in an unweighted tree?", "Depth-First Search", "Breadth-First Search", "Depth-Limited Search", "Bidirectional DFS", "Breadth-First Search", "EASY"));
        list.add(new QuestionItem("What does PEAS stand for in specifying the task environment of an AI agent?", "Performance measure, Environment, Actuators, Sensors", "Program, Execution, Actions, System", "Perception, Entity, Architecture, Storage", "Probability, Estimation, Algorithm, State", "Performance measure, Environment, Actuators, Sensors", "EASY"));
        list.add(new QuestionItem("Which game playing algorithm is standard for two-player zero-sum perfect information games like Chess and Tic-Tac-Toe?", "Minimax Algorithm", "Dijkstra Algorithm", "K-Means", "Backpropagation", "Minimax Algorithm", "EASY"));
        list.add(new QuestionItem("What pruning technique eliminates branches in the Minimax search tree that cannot influence the final decision?", "Alpha-Beta Pruning", "Branch Pruning", "Decision Pruning", "Heuristic Pruning", "Alpha-Beta Pruning", "EASY"));
        list.add(new QuestionItem("What is a heuristic function in informed search algorithms?", "A function that estimates the cheapest path cost from a given node to the goal state", "A function that calculates exact distance", "A random number generator", "A memory cleanup routine", "A function that estimates the cheapest path cost from a given node to the goal state", "EASY"));
        list.add(new QuestionItem("Which local search algorithm continually moves in the direction of increasing value/elevation (steepest ascent)?", "Hill Climbing Search", "Breadth-First Search", "Depth-First Search", "Uniform Cost Search", "Hill Climbing Search", "EASY"));
        list.add(new QuestionItem("What problem occurs in simple Hill Climbing when all neighboring states have the same evaluation value?", "Plateau / Flat Local Maximum", "Infinite Loop", "Division by Zero", "Stack Overflow", "Plateau / Flat Local Maximum", "EASY"));
        list.add(new QuestionItem("What local search algorithm is inspired by the metallurgical process of heating and controlled cooling?", "Simulated Annealing", "Genetic Algorithm", "Particle Swarm Optimization", "Beam Search", "Simulated Annealing", "EASY"));
        list.add(new QuestionItem("What evolutionary search technique uses selection, crossover, and mutation operators?", "Genetic Algorithm", "Simulated Annealing", "A* Search", "Minimax Search", "Genetic Algorithm", "EASY"));
        list.add(new QuestionItem("What does CSP stand for in AI problem formulation?", "Constraint Satisfaction Problem", "Continuous State Planning", "Central Search Protocol", "Conditional State Prediction", "Constraint Satisfaction Problem", "EASY"));
        list.add(new QuestionItem("Which classic puzzle can be formulated as a Constraint Satisfaction Problem?", "N-Queens Problem", "Fibonacci sequence", "Binary Search", "Merge Sort", "N-Queens Problem", "EASY"));
        list.add(new QuestionItem("What representation system uses nodes to represent concepts and edges to represent relationships like 'is-a'?", "Semantic Network", "Binary Tree", "Hash Map", "Stack", "Semantic Network", "EASY"));
        list.add(new QuestionItem("What is First-Order Logic (FOL) an extension of?", "Propositional Logic", "Boolean Algebra", "Fuzzy Logic", "Bayesian Logic", "Propositional Logic", "EASY"));
        list.add(new QuestionItem("In knowledge-based systems, what engine applies logical deduction rules to the knowledge base to deduce new information?", "Inference Engine", "Compiler", "Assembler", "Tokenizer", "Inference Engine", "EASY"));
        list.add(new QuestionItem("What is an Expert System in Artificial Intelligence?", "A software system that emulates the decision-making ability of a human expert using knowledge bases and rules", "A high-performance supercomputer", "A hardware neural chip", "A database query optimizer", "A software system that emulates the decision-making ability of a human expert using knowledge bases and rules", "EASY"));
        list.add(new QuestionItem("What subfield of AI focuses on enabling computers to understand, interpret, and generate human language?", "Natural Language Processing (NLP)", "Computer Vision", "Robotics", "Reinforcement Learning", "Natural Language Processing (NLP)", "EASY"));

        // 20 MEDIUM
        list.add(new QuestionItem("What condition must a heuristic h(n) satisfy to guarantee that A* tree search is optimal?", "Admissibility (never overestimates true cost to goal)", "Consistency strictly", "Must evaluate to zero everywhere", "Must be monotonically increasing", "Admissibility (never overestimates true cost to goal)", "MEDIUM"));
        list.add(new QuestionItem("What stronger condition on a heuristic h(n) guarantees that A* graph search is optimal without revisiting closed nodes?", "Consistency (Monotonicity: h(n) <= c(n, a, n') + h(n'))", "Admissibility only", "Linearity", "Convexity", "Consistency (Monotonicity: h(n) <= c(n, a, n') + h(n'))", "MEDIUM"));
        list.add(new QuestionItem("What is the time complexity reduction achieved by Alpha-Beta pruning in the best-case move ordering compared to Minimax?", "Reduces effective branching factor from b to sqrt(b) (doubles search depth)", "Reduces complexity to O(1)", "Solves games in linear time", "Eliminates all exponential scaling", "Reduces effective branching factor from b to sqrt(b) (doubles search depth)", "MEDIUM"));
        list.add(new QuestionItem("In Constraint Satisfaction Problems, what does the Arc Consistency algorithm (AC-3) enforce?", "For every value in domain of variable Xi, there exists some allowed value in domain of Xj satisfying binary constraint", "Ensures all variables have same value", "Removes all constraints from graph", "Finds optimal solution immediately", "For every value in domain of variable Xi, there exists some allowed value in domain of Xj satisfying binary constraint", "MEDIUM"));
        list.add(new QuestionItem("What heuristic in CSP selects the variable with the fewest remaining legal values in its domain?", "Minimum Remaining Values (MRV) / Fail-First Heuristic", "Degree Heuristic", "Least Constraining Value Heuristic", "Forward Checking", "Minimum Remaining Values (MRV) / Fail-First Heuristic", "MEDIUM"));
        list.add(new QuestionItem("What heuristic in CSP selects the value that rules out the fewest choices for neighboring variables?", "Least Constraining Value (LCV) Heuristic", "Minimum Remaining Values", "Degree Heuristic", "Backjumping", "Least Constraining Value (LCV) Heuristic", "MEDIUM"));
        list.add(new QuestionItem("What algorithm combines the space efficiency of DFS with the completeness and optimality of BFS for search trees?", "Iterative Deepening Search (IDS)", "Uniform Cost Search", "Bidirectional Search", "Hill Climbing", "Iterative Deepening Search (IDS)", "MEDIUM"));
        list.add(new QuestionItem("What is a Bayesian Network (Belief Network) in probabilistic reasoning?", "A Directed Acyclic Graph (DAG) representing conditional dependencies between random variables", "An undirected cyclic graph", "A deep neural network", "A Markov Decision Process", "A Directed Acyclic Graph (DAG) representing conditional dependencies between random variables", "MEDIUM"));
        list.add(new QuestionItem("What does the Markov Blanket of a node in a Bayesian network consist of?", "Its parents, its children, and its children's other parents", "Only its immediate parents", "Only its immediate children", "All ancestors in the network", "Its parents, its children, and its children's other parents", "MEDIUM"));
        list.add(new QuestionItem("In Hidden Markov Models (HMMs), which dynamic programming algorithm computes the most likely sequence of hidden states given observations?", "Viterbi Algorithm", "Forward-Backward Algorithm", "Baum-Welch Algorithm", "Expectation-Maximization", "Viterbi Algorithm", "MEDIUM"));
        list.add(new QuestionItem("In planning in AI, what does the STRIPS representation specify for each operator/action?", "Preconditions, Add List, and Delete List", "Reward function and discount factor", "State transition probabilities", "Neural weights and biases", "Preconditions, Add List, and Delete List", "MEDIUM"));
        list.add(new QuestionItem("What is a Markov Decision Process (MDP) defined by?", "States, Actions, Transition Probabilities, Reward Function, and Discount Factor gamma", "Neurons, Layers, Weights, Biases", "Knowledge base, Inference rules, Queries", "Vertices, Edges, Heuristics", "States, Actions, Transition Probabilities, Reward Function, and Discount Factor gamma", "MEDIUM"));
        list.add(new QuestionItem("What dynamic programming equation expresses the optimal value of a state in an MDP as the expected immediate reward plus discounted future value?", "Bellman Equation", "Euler-Lagrange Equation", "Navier-Stokes Equation", "Schrodinger Equation", "Bellman Equation", "MEDIUM"));
        list.add(new QuestionItem("What search algorithm balances exploration and exploitation using the Upper Confidence Bound for Trees (UCT) in games like Go?", "Monte Carlo Tree Search (MCTS)", "A* Search", "Beam Search", "Genetic Algorithm", "Monte Carlo Tree Search (MCTS)", "MEDIUM"));
        list.add(new QuestionItem("What are the four phases of Monte Carlo Tree Search (MCTS)?", "Selection, Expansion, Simulation (Rollout), Backpropagation", "Fetch, Decode, Execute, Writeback", "Red, Green, Refactor, Deploy", "Preprocess, Train, Validate, Test", "Selection, Expansion, Simulation (Rollout), Backpropagation", "MEDIUM"));
        list.add(new QuestionItem("What is Forward Chaining in rule-based expert systems?", "Data-driven reasoning starting with known facts and applying rules to extract new conclusions", "Goal-driven reasoning working backward from hypothesis", "Random walk over knowledge graph", "Translating rules to SQL queries", "Data-driven reasoning starting with known facts and applying rules to extract new conclusions", "MEDIUM"));
        list.add(new QuestionItem("What is Backward Chaining in logic systems?", "Goal-driven reasoning starting with a goal/hypothesis and searching for rules that support it", "Data-driven reasoning from facts", "Pruning rules randomly", "Forwarding facts to client browsers", "Goal-driven reasoning starting with a goal/hypothesis and searching for rules that support it", "MEDIUM"));
        list.add(new QuestionItem("What is resolution refutation in propositional and first-order logic theorem proving?", "Proving a statement by negating it, adding to premises, and deriving a contradiction (empty clause)", "Evaluating truth tables directly", "Converting formulas to disjunctive normal form", "Executing forward search", "Proving a statement by negating it, adding to premises, and deriving a contradiction (empty clause)", "MEDIUM"));
        list.add(new QuestionItem("What algorithm finds the most general unifier (MGU) for two first-order logic literals?", "Unification Algorithm", "Resolution Algorithm", "Davis-Putnam Algorithm", "Chomsky Normalization", "Unification Algorithm", "MEDIUM"));
        list.add(new QuestionItem("In multi-agent systems, what is a Nash Equilibrium in game theory?", "A state where no player can benefit by unilaterally changing their strategy while other players keep theirs unchanged", "A state where all players lose", "A state of maximum chaos", "A cooperative agreement enforced by law", "A state where no player can benefit by unilaterally changing their strategy while other players keep theirs unchanged", "MEDIUM"));

        // 10 HARD
        list.add(new QuestionItem("In deep reinforcement learning, what is the purpose of Target Networks and Experience Replay in Deep Q-Networks (DQN)?", "Stabilizes training by breaking correlation between consecutive samples and freezing target Q-values", "Speeds up GPU memory allocation", "Converts discrete actions to continuous controls", "Prevents model overfitting on validation sets", "Stabilizes training by breaking correlation between consecutive samples and freezing target Q-values", "HARD"));
        list.add(new QuestionItem("What is the difference between Policy Gradient methods (e.g., REINFORCE, PPO) and Value-based methods (e.g., Q-Learning)?", "Policy gradient optimizes policy parameters directly via gradient ascent on expected return without requiring action-value argmax", "Policy gradient only works on discrete grids", "Value methods cannot use neural networks", "Policy gradient does not use discount factors", "Policy gradient optimizes policy parameters directly via gradient ascent on expected return without requiring action-value argmax", "HARD"));
        list.add(new QuestionItem("How does Proximal Policy Optimization (PPO) prevent destructive policy updates during reinforcement learning training?", "Uses a clipped surrogate objective function that penalizes policy changes moving probability ratio outside [1-eps, 1+eps]", "Sets learning rate to zero on failure", "Restricts training to single-core CPUs", "Disables backpropagation during evaluation", "Uses a clipped surrogate objective function that penalizes policy changes moving probability ratio outside [1-eps, 1+eps]", "HARD"));
        list.add(new QuestionItem("In partially observable environments (POMDPs), what mathematical construct summarizes all past observations to act as an effective state?", "Belief State (probability distribution over all possible physical states)", "Hidden layer activations of MLP", "Q-value scalar", "Adjacency matrix", "Belief State (probability distribution over all possible physical states)", "HARD"));
        list.add(new QuestionItem("What is the Frame Problem in classical Artificial Intelligence knowledge representation?", "The challenge of representing what remains unchanged in the world when an action is performed without infinite non-effect axioms", "Rendering 3D frames on GPU", "Synchronizing video and audio in NLP", "Memory buffer overflow in inference engine", "The challenge of representing what remains unchanged in the world when an action is performed without infinite non-effect axioms", "HARD"));
        list.add(new QuestionItem("What is Dempster-Shafer Theory in automated reasoning under uncertainty?", "A mathematical theory of evidence that allows assigning belief to sets of propositions rather than single states (handles ignorance)", "A neural network pruning technique", "A proof of P vs NP", "A logic compiler for Python", "A mathematical theory of evidence that allows assigning belief to sets of propositions rather than single states (handles ignorance)", "HARD"));
        list.add(new QuestionItem("In probabilistic reasoning, what is Gibbs Sampling and how does it generate samples from a joint distribution?", "MCMC algorithm that updates each variable sequentially conditioned on the current values of all other variables in Markov Blanket", "Calculates exact marginals in O(1) time", "Samples variables independently ignoring dependencies", "Converts probabilities to integers", "MCMC algorithm that updates each variable sequentially conditioned on the current values of all other variables in Markov Blanket", "HARD"));
        list.add(new QuestionItem("What algorithmic concept underpins AlphaGo and AlphaZero's super-human performance?", "MCTS guided by deep neural networks evaluating board value and prior policy probabilities trained via self-play reinforcement learning", "Hard-coded opening book databases", "Brute-force Minimax with alpha-beta pruning", "Genetic algorithms mutating piece positions", "MCTS guided by deep neural networks evaluating board value and prior policy probabilities trained via self-play reinforcement learning", "HARD"));
        list.add(new QuestionItem("What is the Chinese Room Argument formulated by philosopher John Searle?", "Argues that syntax manipulation (like computer programs) does not constitute intentionality or true semantic understanding (Strong AI)", "A test of network latency across continents", "A proof that neural networks can think", "A machine learning translation benchmark", "Argues that syntax manipulation (like computer programs) does not constitute intentionality or true semantic understanding (Strong AI)", "HARD"));
        list.add(new QuestionItem("What is the Junction Tree Algorithm used for in Bayesian inference?", "Performs exact probabilistic inference on general belief networks by transforming them into a tree of cliques and passing messages", "Constructs decision trees from tabular data", "Trains random forests in parallel", "Compresses audio files using wavelets", "Performs exact probabilistic inference on general belief networks by transforming them into a tree of cliques and passing messages", "HARD"));

        return list;
    }

    public static List<QuestionItem> getMlQuestions() {
        List<QuestionItem> list = new ArrayList<>();
        // 20 EASY
        list.add(new QuestionItem("What type of machine learning uses labeled training data consisting of inputs and desired outputs?", "Supervised Learning", "Unsupervised Learning", "Reinforcement Learning", "Self-Supervised Learning", "Supervised Learning", "EASY"));
        list.add(new QuestionItem("What type of machine learning discovers hidden patterns or clusters in unlabeled data?", "Supervised Learning", "Unsupervised Learning", "Semi-Supervised Learning", "Imitation Learning", "Unsupervised Learning", "EASY"));
        list.add(new QuestionItem("Which algorithm is commonly used for classification by finding the optimal hyperplane maximizing the margin between classes?", "Support Vector Machine (SVM)", "K-Means Clustering", "Linear Regression", "Apriori Algorithm", "Support Vector Machine (SVM)", "EASY"));
        list.add(new QuestionItem("What machine learning task predicts continuous numerical values (e.g. house prices)?", "Classification", "Regression", "Clustering", "Dimensionality Reduction", "Regression", "EASY"));
        list.add(new QuestionItem("What machine learning task predicts categorical class labels (e.g. spam vs non-spam)?", "Regression", "Classification", "Density Estimation", "Quantization", "Classification", "EASY"));
        list.add(new QuestionItem("Which unsupervised algorithm partitions n observations into k clusters where each observation belongs to nearest mean?", "K-Means Clustering", "K-Nearest Neighbors", "Linear Regression", "Logistic Regression", "K-Means Clustering", "EASY"));
        list.add(new QuestionItem("What occurs when a model performs exceptionally well on training data but poorly on unseen test data?", "Underfitting", "Overfitting", "Convergence", "Generalization", "Overfitting", "EASY"));
        list.add(new QuestionItem("What occurs when a model is too simple to capture the underlying structure of the training data?", "Overfitting", "Underfitting", "High Variance", "Data Leakage", "Underfitting", "EASY"));
        list.add(new QuestionItem("What is the purpose of splitting a dataset into training and testing sets?", "To evaluate the model's ability to generalize to new, unseen data", "To speed up gradient descent", "To reduce dataset memory size", "To remove outliers automatically", "To evaluate the model's ability to generalize to new, unseen data", "EASY"));
        list.add(new QuestionItem("Which metric measures the fraction of true positive predictions among all instances predicted as positive?", "Recall", "Precision", "Accuracy", "F1-Score", "Precision", "EASY"));
        list.add(new QuestionItem("Which metric measures the fraction of actual positive instances that were correctly identified by the model?", "Precision", "Recall (Sensitivity)", "Specificity", "Fallout", "Recall (Sensitivity)", "EASY"));
        list.add(new QuestionItem("What is the harmonic mean of Precision and Recall called?", "Accuracy", "F1-Score", "ROC-AUC", "Mean Squared Error", "F1-Score", "EASY"));
        list.add(new QuestionItem("Which activation function outputs values in the range (0, 1) and is widely used for binary classification output layers?", "ReLU", "Sigmoid", "Tanh", "Leaky ReLU", "Sigmoid", "EASY"));
        list.add(new QuestionItem("What is the most common loss function used in standard linear regression?", "Cross-Entropy Loss", "Mean Squared Error (MSE)", "Hinge Loss", "Kullback-Leibler Divergence", "Mean Squared Error (MSE)", "EASY"));
        list.add(new QuestionItem("What algorithm computes gradients of the loss function with respect to neural network weights using the chain rule?", "Forward Propagation", "Backpropagation", "Simulated Annealing", "Principal Component Analysis", "Backpropagation", "EASY"));
        list.add(new QuestionItem("What is the Rectified Linear Unit (ReLU) activation function defined as?", "f(x) = max(0, x)", "f(x) = 1 / (1 + e^-x)", "f(x) = tanh(x)", "f(x) = x^2", "f(x) = max(0, x)", "EASY"));
        list.add(new QuestionItem("What does the learning rate hyperparameter control in gradient descent optimization?", "The size of the weight update step taken in the opposite direction of the gradient", "Number of training epochs", "Number of layers in the network", "The batch size of the dataset", "The size of the weight update step taken in the opposite direction of the gradient", "EASY"));
        list.add(new QuestionItem("Which technique scales numerical features so that they have zero mean and unit variance?", "Min-Max Normalization", "Standardization (Z-score scaling)", "One-Hot Encoding", "Label Encoding", "Standardization (Z-score scaling)", "EASY"));
        list.add(new QuestionItem("Which encoding technique converts categorical variables into binary indicator columns (0 or 1)?", "One-Hot Encoding", "Ordinal Encoding", "Hash Encoding", "Target Encoding", "One-Hot Encoding", "EASY"));
        list.add(new QuestionItem("What popular ensemble learning method builds multiple decision trees on bootstrap samples and aggregates their predictions?", "Random Forest", "Linear Regression", "K-Means", "Single Perceptron", "Random Forest", "EASY"));

        // 20 MEDIUM
        list.add(new QuestionItem("What is the Bias-Variance Tradeoff in machine learning?", "High bias causes underfitting; high variance causes overfitting; model complexity must balance both", "Bias and variance always increase together", "Variance can be eliminated completely with more layers", "Bias applies only to neural networks", "High bias causes underfitting; high variance causes overfitting; model complexity must balance both", "MEDIUM"));
        list.add(new QuestionItem("How does L1 Regularization (Lasso) differ from L2 Regularization (Ridge) regarding feature coefficients?", "L1 regularization drives irrelevant feature weights exactly to zero, producing sparse models", "L2 sets weights to zero; L1 keeps them small", "L1 regularization cannot be used with regression", "L2 regularization prevents gradient descent", "L1 regularization drives irrelevant feature weights exactly to zero, producing sparse models", "MEDIUM"));
        list.add(new QuestionItem("What penalty term does L2 Regularization add to the loss function?", "Sum of squared weights (lambda * sum(w_i^2))", "Sum of absolute weights (lambda * sum(|w_i|))", "Product of weights", "Square root of weights", "Sum of squared weights (lambda * sum(w_i^2))", "MEDIUM"));
        list.add(new QuestionItem("What is k-fold Cross-Validation?", "Partitions data into k equal folds, trains on k-1 folds and validates on the remaining fold, repeating k times", "Training k different models on the entire dataset", "Selecting k features using PCA", "Splitting dataset into k clusters", "Partitions data into k equal folds, trains on k-1 folds and validates on the remaining fold, repeating k times", "MEDIUM"));
        list.add(new QuestionItem("What problem affects deep neural networks when gradients become exponentially small as they propagate backward?", "Exploding Gradient Problem", "Vanishing Gradient Problem", "Dead Neurons", "Internal Covariate Shift", "Vanishing Gradient Problem", "MEDIUM"));
        list.add(new QuestionItem("What activation function was introduced to mitigate the Vanishing Gradient problem in hidden layers?", "Sigmoid", "Tanh", "ReLU (Rectified Linear Unit)", "Softmax", "ReLU (Rectified Linear Unit)", "MEDIUM"));
        list.add(new QuestionItem("What does the Area Under the ROC Curve (AUC-ROC) measure?", "The classifier's ability to discriminate between positive and negative classes across all classification thresholds", "Overall training time in seconds", "Model accuracy at threshold 0.5 only", "The variance of test errors", "The classifier's ability to discriminate between positive and negative classes across all classification thresholds", "MEDIUM"));
        list.add(new QuestionItem("What is the difference between Bagging and Boosting in ensemble learning?", "Bagging trains models independently in parallel; Boosting trains models sequentially to correct previous errors", "Bagging uses decision trees; Boosting uses neural nets only", "Boosting trains models independently in parallel", "Bagging cannot be used for classification", "Bagging trains models independently in parallel; Boosting trains models sequentially to correct previous errors", "MEDIUM"));
        list.add(new QuestionItem("Which popular gradient boosting framework uses histogram-based decision tree algorithms for extreme performance?", "LightGBM", "Scikit-Learn SimpleTree", "Weka", "Perceptron", "LightGBM", "MEDIUM"));
        list.add(new QuestionItem("What is the Kernel Trick in Support Vector Machines (SVM)?", "Computes inner products in high-dimensional feature space implicitly without transforming coordinates explicitly", "A trick to bypass training", "Converting SVM to a Decision Tree", "A way to avoid quadratic programming", "Computes inner products in high-dimensional feature space implicitly without transforming coordinates explicitly", "MEDIUM"));
        list.add(new QuestionItem("What is Principal Component Analysis (PCA) used for in data science?", "Linear dimensionality reduction that projects data onto orthogonal axes of maximum variance", "Non-linear clustering", "Supervised classification", "Missing value imputation", "Linear dimensionality reduction that projects data onto orthogonal axes of maximum variance", "MEDIUM"));
        list.add(new QuestionItem("What regularization technique randomly sets a fraction of neuron activations to zero during training in deep networks?", "Batch Normalization", "Dropout", "Early Stopping", "Weight Decay", "Dropout", "MEDIUM"));
        list.add(new QuestionItem("What is the primary benefit of Batch Normalization during deep neural network training?", "Normalizes layer inputs across the mini-batch, accelerating convergence and reducing sensitivity to initialization", "Prevents model weight updates", "Replaces convolutional layers with linear layers", "Eliminates all nonlinearities", "Normalizes layer inputs across the mini-batch, accelerating convergence and reducing sensitivity to initialization", "MEDIUM"));
        list.add(new QuestionItem("Which neural network architecture uses convolutional kernels and pooling layers for spatial hierarchy learning in images?", "Recurrent Neural Network (RNN)", "Convolutional Neural Network (CNN)", "Multilayer Perceptron (MLP)", "Autoencoder", "Convolutional Neural Network (CNN)", "MEDIUM"));
        list.add(new QuestionItem("What neural network cell incorporates Forget, Input, and Output gates to mitigate vanishing gradients in sequential data?", "Gated Recurrent Unit (GRU)", "Long Short-Term Memory (LSTM)", "Standard RNN cell", "Perceptron", "Long Short-Term Memory (LSTM)", "MEDIUM"));
        list.add(new QuestionItem("What loss function is standard for multi-class classification problems with one-hot encoded targets?", "Mean Squared Error", "Categorical Cross-Entropy Loss", "Hinge Loss", "Huber Loss", "Categorical Cross-Entropy Loss", "MEDIUM"));
        list.add(new QuestionItem("What optimization algorithm computes adaptive learning rates for each parameter using first and second moments of gradients?", "Stochastic Gradient Descent (SGD)", "Adam (Adaptive Moment Estimation)", "Momentum SGD", "Nesterov Accelerated Gradient", "Adam (Adaptive Moment Estimation)", "MEDIUM"));
        list.add(new QuestionItem("What is the difference between Generative models and Discriminative models?", "Discriminative models learn P(Y|X); Generative models learn joint distribution P(X, Y) or P(X)", "Discriminative models generate images; Generative models classify labels", "Discriminative models require no training", "Generative models can only predict binary classes", "Discriminative models learn P(Y|X); Generative models learn joint distribution P(X, Y) or P(X)", "MEDIUM"));
        list.add(new QuestionItem("What is Early Stopping in training machine learning models?", "Monitoring validation loss and halting training when validation loss begins to increase to prevent overfitting", "Halting execution when GPU reaches 80 C", "Stopping after exactly 10 epochs", "Stopping when training loss reaches zero", "Monitoring validation loss and halting training when validation loss begins to increase to prevent overfitting", "MEDIUM"));
        list.add(new QuestionItem("In decision trees, what metric measures the impurity or disorder of a node based on probability distributions of classes?", "Gini Impurity / Shannon Entropy", "Mean Squared Error", "Euclidean Distance", "Cosine Similarity", "Gini Impurity / Shannon Entropy", "MEDIUM"));

        // 10 HARD
        list.add(new QuestionItem("What core mechanism allows the Transformer architecture (Vaswani et al.) to model long-range dependencies without recurrence?", "Scaled Dot-Product Multi-Head Self-Attention", "Bidirectional LSTM cells", "Convolutional dilation filters", "Stochastic depth networks", "Scaled Dot-Product Multi-Head Self-Attention", "HARD"));
        list.add(new QuestionItem("In the self-attention formula Attention(Q, K, V) = softmax(QK^T / sqrt(d_k)) V, why is the scaling factor sqrt(d_k) applied?", "To prevent the dot products from growing excessively large for large dimensions, which would push softmax into tiny gradients", "To ensure matrices are symmetric", "To eliminate floating point division", "To normalize the sum of values to 1", "To prevent the dot products from growing excessively large for large dimensions, which would push softmax into tiny gradients", "HARD"));
        list.add(new QuestionItem("What structural innovation in ResNet (He et al.) solved the degradation problem when training very deep neural networks (100+ layers)?", "Residual skip connections (identity shortcuts) allowing layers to learn F(x) + x", "Replacing ReLU with Sigmoid", "Removing all pooling layers", "Using fully connected layers exclusively", "Residual skip connections (identity shortcuts) allowing layers to learn F(x) + x", "HARD"));
        list.add(new QuestionItem("How does a Generative Adversarial Network (GAN) train its Generator and Discriminator components?", "Zero-sum minimax game where Generator creates realistic samples to fool Discriminator while Discriminator learns to distinguish real from fake", "Supervised classification on ImageNet", "Reinforcement learning with Q-tables", "Autoencoding latent vectors", "Zero-sum minimax game where Generator creates realistic samples to fool Discriminator while Discriminator learns to distinguish real from fake", "HARD"));
        list.add(new QuestionItem("In Denoising Diffusion Probabilistic Models (DDPM), how does the reverse generative process generate high-quality images?", "Iteratively removes predicted Gaussian noise from an initial pure noise image through a learned Markov chain reverse process", "Computes adversarial loss in one forward pass", "Samples directly from an autoregressive softmax distribution", "Performs bicubic upsampling", "Iteratively removes predicted Gaussian noise from an initial pure noise image through a learned Markov chain reverse process", "HARD"));
        list.add(new QuestionItem("What mathematical objective is maximized in Variational Autoencoders (VAEs)?", "Evidence Lower Bound (ELBO), balancing reconstruction loss and KL-divergence against a prior", "Maximum Margin Hyperplane", "Mean Squared Error only", "Cross-entropy loss with L1 norm", "Evidence Lower Bound (ELBO), balancing reconstruction loss and KL-divergence against a prior", "HARD"));
        list.add(new QuestionItem("What is the Reparameterization Trick in VAEs and why is it necessary for backpropagation?", "Expresses latent vector as z = mu + sigma * epsilon where epsilon ~ N(0, I), allowing gradients to flow through deterministic nodes", "Converts discrete categories to floats", "Accelerates matrix multiplication on tensor cores", "Replaces convolutional layers with MLPs", "Expresses latent vector as z = mu + sigma * epsilon where epsilon ~ N(0, I), allowing gradients to flow through deterministic nodes", "HARD"));
        list.add(new QuestionItem("In contrastive learning frameworks like SimCLR, what loss function is used to pull representations of augmented views of the same image together?", "NT-Xent (Normalized Temperature-scaled Cross Entropy) Loss", "Mean Squared Error", "Binary Cross Entropy", "Huber Loss", "NT-Xent (Normalized Temperature-scaled Cross Entropy) Loss", "HARD"));
        list.add(new QuestionItem("What parameter-efficient fine-tuning (PEFT) technique freezes pretrained weights and injects trainable low-rank decomposition matrices?", "LoRA (Low-Rank Adaptation)", "Full Fine-Tuning", "Gradient Clipping", "Weight Pruning", "LoRA (Low-Rank Adaptation)", "HARD"));
        list.add(new QuestionItem("In Transformer architectures, what is the computational complexity of standard self-attention with respect to sequence length N?", "O(N^2)", "O(N)", "O(N log N)", "O(log N)", "O(N^2)", "HARD"));

        return list;
    }

    public static List<QuestionItem> getCloudComputingQuestions() {
        List<QuestionItem> list = new ArrayList<>();
        // 20 EASY
        list.add(new QuestionItem("What are the three fundamental service models in cloud computing according to NIST?", "IaaS, PaaS, SaaS", "TCP, IP, UDP", "LAN, WAN, MAN", "RAM, CPU, SSD", "IaaS, PaaS, SaaS", "EASY"));
        list.add(new QuestionItem("What does IaaS stand for in cloud computing?", "Infrastructure as a Service", "Internet as a Service", "Information as a Service", "Integration as a Service", "Infrastructure as a Service", "EASY"));
        list.add(new QuestionItem("What does PaaS stand for in cloud computing?", "Platform as a Service", "Performance as a Service", "Protocol as a Service", "Process as a Service", "Platform as a Service", "EASY"));
        list.add(new QuestionItem("What does SaaS stand for in cloud computing?", "Software as a Service", "Storage as a Service", "Security as a Service", "System as a Service", "Software as a Service", "EASY"));
        list.add(new QuestionItem("Which cloud deployment model is owned and operated by a third-party cloud provider and shared by multiple tenants?", "Public Cloud", "Private Cloud", "Hybrid Cloud", "Community Cloud", "Public Cloud", "EASY"));
        list.add(new QuestionItem("Which cloud deployment model is used exclusively by a single organization?", "Private Cloud", "Public Cloud", "Hybrid Cloud", "Multi-Tenant Cloud", "Private Cloud", "EASY"));
        list.add(new QuestionItem("What cloud model combines on-premises infrastructure or private cloud with public cloud services?", "Hybrid Cloud", "Single Cloud", "Public Cloud only", "Virtual Private Network", "Hybrid Cloud", "EASY"));
        list.add(new QuestionItem("What essential cloud characteristic refers to the ability to automatically scale resources dynamically to meet demand?", "Rapid Elasticity", "Measured Service", "Resource Pooling", "Broad Network Access", "Rapid Elasticity", "EASY"));
        list.add(new QuestionItem("What cloud storage type stores data as distinct units called objects with metadata and unique identifiers (e.g. Amazon S3)?", "Object Storage", "Block Storage", "File Storage", "Tape Storage", "Object Storage", "EASY"));
        list.add(new QuestionItem("Which cloud storage service provides raw volumes that can be attached to virtual machines like physical hard drives (e.g. AWS EBS)?", "Block Storage", "Object Storage", "Tape Storage", "CDN Cache", "Block Storage", "EASY"));
        list.add(new QuestionItem("What technology enables running multiple isolated virtual machines on a single physical host machine?", "Hypervisor (Virtual Machine Monitor)", "Compiler", "Web Server", "Database Engine", "Hypervisor (Virtual Machine Monitor)", "EASY"));
        list.add(new QuestionItem("What open-source software platform packages application code and dependencies into lightweight, portable containers?", "Docker", "Apache Tomcat", "Node.js", "VirtualBox", "Docker", "EASY"));
        list.add(new QuestionItem("What open-source container orchestration platform automates deployment, scaling, and management of containerized applications?", "Kubernetes (K8s)", "Ansible", "Terraform", "Jenkins", "Kubernetes (K8s)", "EASY"));
        list.add(new QuestionItem("What execution model executes cloud code in response to events without provisioning or managing persistent servers?", "Serverless Computing (FaaS)", "IaaS Bare Metal", "Dedicated Hosting", "On-Premises Mainframe", "Serverless Computing (FaaS)", "EASY"));
        list.add(new QuestionItem("What is AWS Lambda an example of?", "Function as a Service (FaaS / Serverless)", "Object Storage", "Relational Database", "Virtual Machine Hypervisor", "Function as a Service (FaaS / Serverless)", "EASY"));
        list.add(new QuestionItem("What distributed network of proxy servers delivers web content and media quickly based on user geographic location?", "Content Delivery Network (CDN)", "Virtual Private Cloud", "Subnet Mask", "Load Balancer", "Content Delivery Network (CDN)", "EASY"));
        list.add(new QuestionItem("What cloud component automatically distributes incoming network traffic across multiple healthy target servers?", "Load Balancer", "Firewall", "NAT Gateway", "DNS Resolver", "Load Balancer", "EASY"));
        list.add(new QuestionItem("What is a Region in cloud computing infrastructure (e.g. AWS, GCP, Azure)?", "A separate geographic area containing multiple isolated Availability Zones", "A single rack inside a data center", "A software library", "A billing account", "A separate geographic area containing multiple isolated Availability Zones", "EASY"));
        list.add(new QuestionItem("What is an Availability Zone (AZ)?", "One or more discrete data centers with redundant power, networking, and cooling within a Region", "A public IP address block", "A customer support tier", "A cloud storage bucket", "One or more discrete data centers with redundant power, networking, and cooling within a Region", "EASY"));
        list.add(new QuestionItem("What cloud model charges customers only for the specific computing resources consumed without upfront commitments?", "Pay-as-you-go (Utility Pricing)", "Fixed Monthly License", "Per-User Lifetime Seat", "Hardware Depreciation Model", "Pay-as-you-go (Utility Pricing)", "EASY"));

        // 20 MEDIUM
        list.add(new QuestionItem("What is the Shared Responsibility Model in public cloud computing security?", "Cloud provider manages security 'of' the cloud (hardware, host); customer manages security 'in' the cloud (data, IAM, OS)", "Cloud provider takes 100% legal responsibility for all customer data breaches", "Customers are responsible for replacing server hardware", "Cloud provider configures customer application passwords", "Cloud provider manages security 'of' the cloud (hardware, host); customer manages security 'in' the cloud (data, IAM, OS)", "MEDIUM"));
        list.add(new QuestionItem("What is the difference between a Type-1 (Bare-Metal) and Type-2 (Hosted) Hypervisor?", "Type-1 runs directly on physical host hardware; Type-2 runs as software on top of a host operating system", "Type-1 is slower than Type-2", "Type-2 runs directly on bare metal", "Type-1 only supports Linux guests", "Type-1 runs directly on physical host hardware; Type-2 runs as software on top of a host operating system", "MEDIUM"));
        list.add(new QuestionItem("What is Infrastructure as Code (IaC) and which declarative tool is widely used for multi-cloud IaC provisioning?", "Managing and provisioning cloud infrastructure using code definitions; Terraform", "Writing bash scripts on each server", "Configuring servers manually in the AWS web console", "Compiling Java code on cloud VMs", "Managing and provisioning cloud infrastructure using code definitions; Terraform", "MEDIUM"));
        list.add(new QuestionItem("In Kubernetes architecture, what is the smallest deployable computing unit that groups one or more containers?", "Pod", "Node", "Cluster", "Service", "Pod", "MEDIUM"));
        list.add(new QuestionItem("Which Kubernetes control plane component schedules newly created Pods onto available worker Nodes based on resource requirements?", "kube-scheduler", "kube-apiserver", "etcd", "kube-controller-manager", "kube-scheduler", "MEDIUM"));
        list.add(new QuestionItem("What consistent, distributed key-value store is used by Kubernetes to persist all cluster state and configuration data?", "etcd", "Redis", "PostgreSQL", "MongoDB", "etcd", "MEDIUM"));
        list.add(new QuestionItem("In AWS networking, what is a Virtual Private Cloud (VPC)?", "A logically isolated virtual network dedicated to an AWS customer account with custom IP ranges and subnets", "A physical data center facility", "A public internet exchange point", "An unencrypted wireless network", "A logically isolated virtual network dedicated to an AWS customer account with custom IP ranges and subnets", "MEDIUM"));
        list.add(new QuestionItem("What component in a cloud VPC allows instances in a private subnet to initiate outbound internet connections without accepting inbound traffic?", "NAT Gateway", "Internet Gateway", "Transit Gateway", "Direct Connect", "NAT Gateway", "MEDIUM"));
        list.add(new QuestionItem("What is an immutable infrastructure deployment pattern in cloud operations?", "Servers are never modified or patched in-place; new updated server images/containers are deployed to replace old ones", "Servers cannot be shut down", "Databases are read-only forever", "Source code is compiled once", "Servers are never modified or patched in-place; new updated server images/containers are deployed to replace old ones", "MEDIUM"));
        list.add(new QuestionItem("What is a Service Level Agreement (SLA) in cloud computing?", "A formal contract defining guaranteed performance standards (uptime, latency) and penalties for non-compliance", "A software user manual", "An employee code of conduct", "A billing invoice", "A formal contract defining guaranteed performance standards (uptime, latency) and penalties for non-compliance", "MEDIUM"));
        list.add(new QuestionItem("How many minutes of downtime per year does 'Four Nines' (99.99%) cloud availability permit?", "Approximately 52.6 minutes per year", "8.76 hours per year", "3.65 days per year", "5 minutes per year", "Approximately 52.6 minutes per year", "MEDIUM"));
        list.add(new QuestionItem("What is the purpose of Auto Scaling Groups (ASG) in cloud environments?", "Automatically adds or removes compute instances based on CPU utilization, schedule, or network demand", "Defragmenting virtual hard disks", "Installing OS security patches automatically", "Renaming virtual machines", "Automatically adds or removes compute instances based on CPU utilization, schedule, or network demand", "MEDIUM"));
        list.add(new QuestionItem("What is a Cold Start in serverless function execution (e.g., AWS Lambda)?", "The latency delay incurred when provisioning a new execution environment container and loading function code from scratch", "Rebooting the physical data center", "Cooling servers with liquid nitrogen", "Compiling C++ code on startup", "The latency delay incurred when provisioning a new execution environment container and loading function code from scratch", "MEDIUM"));
        list.add(new QuestionItem("What is the principle of least privilege in Cloud Identity and Access Management (IAM)?", "Users and service accounts are granted only the minimum permissions necessary to perform their required tasks", "Every user has full root admin access", "Users change passwords every hour", "Accounts are shared among team members", "Users and service accounts are granted only the minimum permissions necessary to perform their required tasks", "MEDIUM"));
        list.add(new QuestionItem("What is a Sidecar Pattern in containerized microservice architectures?", "Deploying a helper container into the same Pod alongside the main container to handle logging, monitoring, or proxying", "Running two copies of database", "Using dual network cables", "A backup server in another country", "Deploying a helper container into the same Pod alongside the main container to handle logging, monitoring, or proxying", "MEDIUM"));
        list.add(new QuestionItem("What is a Service Mesh (e.g., Istio, Linkerd) in Kubernetes environments?", "A dedicated infrastructure layer for managing service-to-service communication, mTLS encryption, observability, and traffic routing", "A high-speed physical fiber cable", "A cloud billing dashboard", "A replacement for Docker", "A dedicated infrastructure layer for managing service-to-service communication, mTLS encryption, observability, and traffic routing", "MEDIUM"));
        list.add(new QuestionItem("What does RPO (Recovery Point Objective) measure in cloud disaster recovery planning?", "The maximum acceptable amount of data loss measured in time between backup point and disaster", "The time it takes to restore services", "The cost of cloud backup storage", "The network latency during replication", "The maximum acceptable amount of data loss measured in time between backup point and disaster", "MEDIUM"));
        list.add(new QuestionItem("What does RTO (Recovery Time Objective) measure in disaster recovery?", "The maximum acceptable duration of time to restore business operations after a service disruption", "The amount of data lost", "The time to train operators", "The bandwidth of internet connection", "The maximum acceptable duration of time to restore business operations after a service disruption", "MEDIUM"));
        list.add(new QuestionItem("What is Chaos Mesh / Gremlin used for in cloud-native infrastructure?", "Conducting controlled chaos experiments (pod kills, network delay, packet loss) to validate cluster resilience", "Encrypting database backups", "Monitoring CPU temperatures", "Generating synthetic web traffic", "Conducting controlled chaos experiments (pod kills, network delay, packet loss) to validate cluster resilience", "MEDIUM"));
        list.add(new QuestionItem("What is Cloud Spanning / Multi-Cloud strategy and what is its primary benefit?", "Using services from multiple cloud providers (AWS, GCP, Azure) to prevent vendor lock-in and optimize costs/resilience", "Connecting multiple monitors to a PC", "Using multiple web browsers", "Hosting on-premises servers without internet", "Using services from multiple cloud providers (AWS, GCP, Azure) to prevent vendor lock-in and optimize costs/resilience", "MEDIUM"));

        // 10 HARD
        list.add(new QuestionItem("What is the Raft Consensus Algorithm used for in distributed cloud systems (like etcd)?", "Elects a leader and manages replicated state machine logs through term voting and log matching to guarantee strong consistency", "Distributes HTTP requests randomly", "Calculates hash keys for Amazon S3", "Compiles microservices in parallel", "Elects a leader and manages replicated state machine logs through term voting and log matching to guarantee strong consistency", "HARD"));
        list.add(new QuestionItem("In AWS Nitro architecture, how did Amazon offload hypervisor virtualization overhead from the main server CPU?", "Dedicated Nitro ASIC/PCIe cards handle VPC networking, EBS storage, security, and management, freeing 100% of host CPU for guest instances", "Replaced CPUs with GPUs", "Moved hypervisors to client laptops", "Ran virtual machines in browser", "Dedicated Nitro ASIC/PCIe cards handle VPC networking, EBS storage, security, and management, freeing 100% of host CPU for guest instances", "HARD"));
        list.add(new QuestionItem("What is the difference between Strong Consistency and Eventual Consistency in cloud distributed databases (like DynamoDB or Spanner)?", "Strong guarantees reads always return the latest write; Eventual guarantees all replicas will converge after a period without new writes", "Eventual consistency never guarantees correct data", "Strong consistency does not work across availability zones", "DynamoDB only supports strong consistency", "Strong guarantees reads always return the latest write; Eventual guarantees all replicas will converge after a period without new writes", "HARD"));
        list.add(new QuestionItem("How does Google Cloud Spanner achieve globally distributed ACID transactions with external consistency without blocking reads?", "Uses TrueTime API with synchronized GPS and atomic clocks to provide bounded uncertainty time windows for commit wait", "Uses standard NTP server pools over internet", "Relies exclusively on Paxos without clocks", "Executes transactions on a single centralized supercomputer", "Uses TrueTime API with synchronized GPS and atomic clocks to provide bounded uncertainty time windows for commit wait", "HARD"));
        list.add(new QuestionItem("What is eBPF-based container networking (e.g., Cilium) and why does it outperform standard iptables in Kubernetes?", "Replaces tens of thousands of sequential iptables rules with O(1) in-kernel BPF maps and bypasses network stack overhead", "Runs networking on user-space proxies", "Disables network encryption", "Uses physical switch hardware only", "Replaces tens of thousands of sequential iptables rules with O(1) in-kernel BPF maps and bypasses network stack overhead", "HARD"));
        list.add(new QuestionItem("In Kubernetes networking, how does the CNI (Container Network Interface) ensure that all Pods can communicate across nodes without NAT?", "Assigns a globally routable IP address from cluster CIDR to each Pod, routed via overlay networks (VXLAN) or BGP routing", "Forces all Pods to share the host IP address and different ports", "Routes all traffic through a centralized proxy server", "Uses loopback adapters only", "Assigns a globally routable IP address from cluster CIDR to each Pod, routed via overlay networks (VXLAN) or BGP routing", "HARD"));
        list.add(new QuestionItem("What is the difference between horizontal pod autoscaling (HPA) and vertical pod autoscaling (VPA) in Kubernetes?", "HPA scales the number of pod replicas up/down; VPA adjusts the CPU/memory resource requests and limits of existing pods", "HPA modifies node hardware; VPA deletes pods", "VPA works in real time without restarting pods", "HPA only works with custom metrics", "HPA scales the number of pod replicas up/down; VPA adjusts the CPU/memory resource requests and limits of existing pods", "HARD"));
        list.add(new QuestionItem("What is GitOps (e.g., ArgoCD, Flux) in modern cloud-native continuous delivery?", "The practice of using a Git repository as the single source of truth for declarative infrastructure and applications, with automated reconciliation loops", "Storing binary images inside Git commits", "Writing cloud code in bash scripts", "Manually applying kubectl commands", "The practice of using a Git repository as the single source of truth for declarative infrastructure and applications, with automated reconciliation loops", "HARD"));
        list.add(new QuestionItem("In cloud security, what is a Confident Computing (Confidential VMs) environment?", "Uses hardware-based Trusted Execution Environments (TEEs, like AMD SEV or Intel SGX) to keep data encrypted in memory during processing", "Disables all network ports", "Runs VMs on air-gapped computers", "Stores passwords in plain text", "Uses hardware-based Trusted Execution Environments (TEEs, like AMD SEV or Intel SGX) to keep data encrypted in memory during processing", "HARD"));
        list.add(new QuestionItem("What is a Split-Brain scenario in a high-availability multi-region cloud cluster, and how is it prevented?", "Network partition causes two sub-clusters to each believe the other is dead and both act as master; prevented by quorum voting", "Server CPU overheats and halves its clock speed", "Database table is partitioned into two schemas", "Load balancer splits HTTP traffic 50/50", "Network partition causes two sub-clusters to each believe the other is dead and both act as master; prevented by quorum voting", "HARD"));

        return list;
    }

    public static List<QuestionItem> getCyberSecurityQuestions() {
        List<QuestionItem> list = new ArrayList<>();
        // 20 EASY
        list.add(new QuestionItem("What are the three pillars of information security in the CIA Triad?", "Confidentiality, Integrity, Availability", "Control, Identification, Access", "Cryptology, Inspection, Authentication", "Communication, Internet, Architecture", "Confidentiality, Integrity, Availability", "EASY"));
        list.add(new QuestionItem("What does the 'Integrity' pillar of the CIA Triad guarantee?", "Information is accurate, complete, and protected against unauthorized modification or deletion", "Information is accessible 24/7", "Information is secret from all parties", "Information is backed up on tape", "Information is accurate, complete, and protected against unauthorized modification or deletion", "EASY"));
        list.add(new QuestionItem("What type of attack involves sending deceptive emails pretending to be from a reputable source to steal credentials?", "Phishing", "DDoS", "SQL Injection", "Buffer Overflow", "Phishing", "EASY"));
        list.add(new QuestionItem("What malicious software encrypts a victim's files and demands payment for the decryption key?", "Ransomware", "Adware", "Spyware", "Worm", "Ransomware", "EASY"));
        list.add(new QuestionItem("What security practice requires users to provide two or more verification factors to gain access to an account?", "Multi-Factor Authentication (MFA / 2FA)", "Single Sign-On", "Strong Passwords", "Captcha", "Multi-Factor Authentication (MFA / 2FA)", "EASY"));
        list.add(new QuestionItem("What type of malware self-replicates and spreads across network connections without requiring user interaction?", "Worm", "Trojan Horse", "Macro Virus", "Rootkit", "Worm", "EASY"));
        list.add(new QuestionItem("What type of malware disguises itself as legitimate or useful software while executing hidden malicious actions?", "Trojan Horse", "Worm", "Ransomware", "Keylogger", "Trojan Horse", "EASY"));
        list.add(new QuestionItem("What attack overwhelms a server or network with a flood of traffic to render it unavailable to legitimate users?", "Denial of Service (DoS / DDoS)", "Phishing", "Cross-Site Scripting", "Man-in-the-Middle", "Denial of Service (DoS / DDoS)", "EASY"));
        list.add(new QuestionItem("Which encryption type uses the same shared secret key for both encryption and decryption?", "Symmetric Encryption (e.g. AES)", "Asymmetric Encryption (e.g. RSA)", "Hashing (e.g. SHA-256)", "Homomorphic Encryption", "Symmetric Encryption (e.g. AES)", "EASY"));
        list.add(new QuestionItem("Which encryption type uses a mathematically paired public key for encryption and private key for decryption?", "Asymmetric Encryption (Public Key Cryptography)", "Symmetric Encryption", "Stream Cipher", "Block Cipher", "Asymmetric Encryption (Public Key Cryptography)", "EASY"));
        list.add(new QuestionItem("What is the primary cryptographic standard widely used for symmetric data encryption globally (NIST standard)?", "AES (Advanced Encryption Standard)", "DES", "MD5", "RC4", "AES (Advanced Encryption Standard)", "EASY"));
        list.add(new QuestionItem("What is a cryptographic hash function characterized by?", "A one-way mathematical function transforming arbitrary data into a fixed-size digest that cannot be reversed", "A reversible encryption algorithm", "A public-private key pair generator", "A random number generator", "A one-way mathematical function transforming arbitrary data into a fixed-size digest that cannot be reversed", "EASY"));
        list.add(new QuestionItem("Why is MD5 considered obsolete and insecure for security and password verification?", "It is vulnerable to collision attacks where two different inputs produce the same hash", "It produces hashes that are too long", "It requires too much CPU time", "It cannot hash text files", "It is vulnerable to collision attacks where two different inputs produce the same hash", "EASY"));
        list.add(new QuestionItem("What attack injects malicious SQL statements into entry fields to manipulate backend database queries?", "SQL Injection (SQLi)", "Cross-Site Scripting (XSS)", "Cross-Site Request Forgery (CSRF)", "Directory Traversal", "SQL Injection (SQLi)", "EASY"));
        list.add(new QuestionItem("What is the primary defense against SQL Injection vulnerabilities in software code?", "Using Parameterized Queries (Prepared Statements)", "Validating user emails", "Hiding SQL table names", "Using HTTPS connections", "Using Parameterized Queries (Prepared Statements)", "EASY"));
        list.add(new QuestionItem("What is a Zero-Day vulnerability in cybersecurity?", "A software vulnerability that is unknown to the vendor and has no available security patch", "A virus that infects systems in zero seconds", "A hardware component with zero warranty", "A vulnerability discovered on the first day of the year", "A software vulnerability that is unknown to the vendor and has no available security patch", "EASY"));
        list.add(new QuestionItem("What security mechanism inspects and filters incoming and outgoing network traffic based on established security rules?", "Firewall", "Repeater", "Switch", "Hub", "Firewall", "EASY"));
        list.add(new QuestionItem("What is a digital certificate issued by a Certificate Authority (CA) used for in HTTPS?", "Binds a public key to an entity/domain name and verifies server authenticity", "Encrypts client hard drives", "Speeds up browser rendering", "Filters malware from incoming emails", "Binds a public key to an entity/domain name and verifies server authenticity", "EASY"));
        list.add(new QuestionItem("What does VPN stand for in secure remote networking?", "Virtual Private Network", "Variable Protocol Node", "Visual Protection Network", "Verified Packet Node", "Virtual Private Network", "EASY"));
        list.add(new QuestionItem("What is a Honeypot in network defense?", "A decoy system intentionally deployed to lure attackers and study their techniques without risking production data", "A firewall configuration file", "A password cracking tool", "A secure backup drive", "A decoy system intentionally deployed to lure attackers and study their techniques without risking production data", "EASY"));

        // 20 MEDIUM
        list.add(new QuestionItem("What is a Salt in password hashing and why is it essential?", "A random string added to the password before hashing to defend against precomputed Rainbow Table attacks", "A secret encryption key", "A password compression algorithm", "A pepper value shared across all users", "A random string added to the password before hashing to defend against precomputed Rainbow Table attacks", "MEDIUM"));
        list.add(new QuestionItem("Which password hashing algorithms are specifically designed to be slow and memory-hard to resist GPU brute-force attacks?", "bcrypt, Argon2, and scrypt", "MD5 and SHA-1", "AES and DES", "RSA and ECC", "bcrypt, Argon2, and scrypt", "MEDIUM"));
        list.add(new QuestionItem("What is the difference between Authentication and Authorization in access control?", "Authentication verifies who you are; Authorization determines what resources you are allowed to access", "Authentication checks permissions; Authorization checks passwords", "Both terms are completely identical", "Authorization occurs before authentication", "Authentication verifies who you are; Authorization determines what resources you are allowed to access", "MEDIUM"));
        list.add(new QuestionItem("What is a Buffer Overflow attack?", "Writing data past the boundary of a buffer, overwriting adjacent memory and hijacking execution flow (e.g. return address)", "Flooding network buffers with packets", "Exhausting database disk space", "Cracking passwords by dictionary", "Writing data past the boundary of a buffer, overwriting adjacent memory and hijacking execution flow (e.g. return address)", "MEDIUM"));
        list.add(new QuestionItem("What memory protection mechanism randomizes the memory addresses of key data areas (stack, heap, libraries) to thwart exploits?", "Address Space Layout Randomization (ASLR)", "Data Execution Prevention (DEP)", "Stack Canaries", "Control Flow Guard", "Address Space Layout Randomization (ASLR)", "MEDIUM"));
        list.add(new QuestionItem("What security feature marks memory regions (like the stack) as non-executable to prevent executing injected shellcode?", "Data Execution Prevention (DEP / NX bit)", "ASLR", "Virtual Memory", "Paging", "Data Execution Prevention (DEP / NX bit)", "MEDIUM"));
        list.add(new QuestionItem("What is a Man-in-the-Middle (MitM) attack?", "An attacker secretly intercepts and potentially alters communication between two parties who believe they are talking directly", "An attacker breaking into a physical server room", "A hardware failure in a core switch", "A distributed botnet attack", "An attacker secretly intercepts and potentially alters communication between two parties who believe they are talking directly", "MEDIUM"));
        list.add(new QuestionItem("What is ARP Poisoning (ARP Spoofing) on a local area network?", "Broadcasting fraudulent ARP messages to associate the attacker's MAC address with a legitimate IP (like the default gateway)", "Flooding DHCP with requests", "Modifying DNS records on root servers", "Overheating the network interface card", "Broadcasting fraudulent ARP messages to associate the attacker's MAC address with a legitimate IP (like the default gateway)", "MEDIUM"));
        list.add(new QuestionItem("In Public Key Infrastructure (PKI), what is a Certificate Revocation List (CRL)?", "A list of digital certificates that have been revoked by the issuing CA before their scheduled expiration date", "A list of trusted root authorities", "A list of registered domain names", "A list of banned IP addresses", "A list of digital certificates that have been revoked by the issuing CA before their scheduled expiration date", "MEDIUM"));
        list.add(new QuestionItem("What protocol provides real-time verification of certificate revocation status without downloading the entire CRL?", "Online Certificate Status Protocol (OCSP)", "DNSSEC", "SNMP", "NTP", "Online Certificate Status Protocol (OCSP)", "MEDIUM"));
        list.add(new QuestionItem("What is the Zero Trust security architecture model fundamentally based on?", "'Never trust, always verify' — strictly authenticate and authorize every user, device, and network transaction continuously", "Trusting all devices inside corporate firewall", "Allowing unauthenticated LAN traffic", "Disabling multi-factor authentication", "'Never trust, always verify' — strictly authenticate and authorize every user, device, and network transaction continuously", "MEDIUM"));
        list.add(new QuestionItem("What is Privilege Escalation in computer security?", "An attacker exploiting a bug or misconfiguration to gain elevated access (e.g. root/admin) beyond their initial permissions", "Increasing CPU clock speed", "Upgrading a user's subscription tier", "Promoting a developer to manager", "An attacker exploiting a bug or misconfiguration to gain elevated access (e.g. root/admin) beyond their initial permissions", "MEDIUM"));
        list.add(new QuestionItem("What is Server-Side Request Forgery (SSRF)?", "A vulnerability allowing an attacker to coerce a web application into sending crafted HTTP requests to internal or third-party resources", "Modifying client-side cookies", "Injecting JavaScript into HTML", "Overriding DNS records", "A vulnerability allowing an attacker to coerce a web application into sending crafted HTTP requests to internal or third-party resources", "MEDIUM"));
        list.add(new QuestionItem("What is the difference between an IDS (Intrusion Detection System) and an IPS (Intrusion Prevention System)?", "IDS monitors and alerts on suspicious activity out-of-band; IPS is placed inline and actively blocks detected threats", "IDS blocks traffic; IPS only generates logs", "IDS is hardware only; IPS is software only", "Both are completely identical", "IDS monitors and alerts on suspicious activity out-of-band; IPS is placed inline and actively blocks detected threats", "MEDIUM"));
        list.add(new QuestionItem("In cryptography, what does Kerckhoffs's Principle state?", "A cryptographic system should be secure even if everything about the system, except the key, is public knowledge", "Security through obscurity is best", "Keys should be hardcoded in source code", "Encryption algorithms must be kept secret", "A cryptographic system should be secure even if everything about the system, except the key, is public knowledge", "MEDIUM"));
        list.add(new QuestionItem("What is Perfect Forward Secrecy (PFS) in secure communications?", "Compromise of long-term server private keys does not compromise past session keys or decrypt recorded historical traffic", "Passwords never expire", "Certificates are renewed every year", "Data is encrypted twice with AES", "Compromise of long-term server private keys does not compromise past session keys or decrypt recorded historical traffic", "MEDIUM"));
        list.add(new QuestionItem("What is a Replay Attack and what mechanism mitigates it in secure protocols?", "An attacker intercepts valid transmission and retransmits it later; mitigated by timestamps, sequence numbers, and nonces", "An attacker decrypts data using quantum computers; mitigated by longer keys", "An attacker changes data in transit; mitigated by hashing", "An attacker floods server with SYN packets; mitigated by SYN cookies", "An attacker intercepts valid transmission and retransmits it later; mitigated by timestamps, sequence numbers, and nonces", "MEDIUM"));
        list.add(new QuestionItem("What is Insecure Direct Object Reference (IDOR)?", "An access control vulnerability where an application uses user-supplied input to access database objects directly without authorization checks", "A broken CSS layout", "A missing foreign key constraint", "A memory leak in Java", "An access control vulnerability where an application uses user-supplied input to access database objects directly without authorization checks", "MEDIUM"));
        list.add(new QuestionItem("What does SIEM stand for in enterprise security monitoring?", "Security Information and Event Management", "System Integration and Encryption Mechanism", "Standard Inspection and Electronic Monitoring", "Secure Internet Endpoint Management", "Security Information and Event Management", "MEDIUM"));
        list.add(new QuestionItem("What is the principle of Defense in Depth in cybersecurity architecture?", "Employing multiple layered security controls throughout an IT system so that if one fails, others protect the assets", "Using one single extremely strong firewall", "Encrypting files only at rest", "Placing all servers in a bunker", "Employing multiple layered security controls throughout an IT system so that if one fails, others protect the assets", "MEDIUM"));

        // 10 HARD
        list.add(new QuestionItem("What is Return-Oriented Programming (ROP) in binary exploitation?", "Chaining together short existing machine code sequences ('gadgets') ending in 'ret' to bypass Data Execution Prevention (DEP)", "Writing scripts in assembly language", "Returning function pointers to null", "Modifying compiler flags", "Chaining together short existing machine code sequences ('gadgets') ending in 'ret' to bypass Data Execution Prevention (DEP)", "HARD"));
        list.add(new QuestionItem("In elliptic curve cryptography (ECC), what hard mathematical problem provides the foundation for cryptographic security?", "The Elliptic Curve Discrete Logarithm Problem (ECDLP)", "Integer factorization of large primes", "Shortest Vector Problem in lattices", "Finding Hamiltonian paths", "The Elliptic Curve Discrete Logarithm Problem (ECDLP)", "HARD"));
        list.add(new QuestionItem("What is a Timing Attack in cryptographic implementations?", "A side-channel attack that analyzes the exact time taken to execute cryptographic algorithms to infer secret keys", "Setting the system clock forward", "Overclocking CPU cores", "Delaying network packets on purpose", "A side-channel attack that analyzes the exact time taken to execute cryptographic algorithms to infer secret keys", "HARD"));
        list.add(new QuestionItem("What is Post-Quantum Cryptography (PQC) and what mathematical family is selected by NIST for primary quantum-resistant standards (e.g. ML-KEM / Kyber)?", "Lattice-based cryptography designed to resist attacks by Shor's algorithm on quantum computers", "Symmetric AES-64", "RSA with 1024-bit keys", "DES algorithms", "Lattice-based cryptography designed to resist attacks by Shor's algorithm on quantum computers", "HARD"));
        list.add(new QuestionItem("What is Pass-the-Hash (PtH) attack in Windows Active Directory environments?", "An attacker extracts NTLM password hashes from memory and uses them directly to authenticate to remote servers without cracking the plaintext", "Guessing passwords through brute-force", "Modifying password hashes in SQL database", "Stealing Kerberos tickets via DNS", "An attacker extracts NTLM password hashes from memory and uses them directly to authenticate to remote servers without cracking the plaintext", "HARD"));
        list.add(new QuestionItem("In Kerberos authentication, what is a Golden Ticket attack?", "Forging a valid Kerberos Ticket Granting Ticket (TGT) using the extracted KRBTGT account password hash, granting permanent unrestricted domain admin access", "Brute forcing a user password", "Sniffing NTLM packets on Wi-Fi", "Modifying DNS records", "Forging a valid Kerberos Ticket Granting Ticket (TGT) using the extracted KRBTGT account password hash, granting permanent unrestricted domain admin access", "HARD"));
        list.add(new QuestionItem("What is a Blind SQL Injection attack and how does an attacker extract data?", "Application displays no database errors or data; attacker extracts info by asking boolean True/False queries or injecting sleep/time delays", "Attacker cannot see the web browser", "Attacker injects random characters", "Attacker runs queries on an encrypted database", "Application displays no database errors or data; attacker extracts info by asking boolean True/False queries or injecting sleep/time delays", "HARD"));
        list.add(new QuestionItem("What is an XML External Entity (XXE) injection attack?", "Exploits vulnerable XML parsers that process external entity references to disclose internal files, scan ports, or execute SSRF", "Corrupting HTML tags", "Uploading malicious SVG images to crash browsers", "Injecting JavaScript into JSON", "Exploits vulnerable XML parsers that process external entity references to disclose internal files, scan ports, or execute SSRF", "HARD"));
        list.add(new QuestionItem("What is Differential Cryptanalysis in symmetric block cipher cryptanalysis?", "Studying how differences in plaintext inputs affect the resulting differences in output ciphertexts to recover secret keys", "Comparing file sizes of encrypted data", "Analyzing CPU power consumption", "Using rainbow tables", "Studying how differences in plaintext inputs affect the resulting differences in output ciphertexts to recover secret keys", "HARD"));
        list.add(new QuestionItem("What is Homomorphic Encryption?", "A cryptographic form that allows computations to be performed directly on encrypted ciphertexts, generating an encrypted result that decrypts to match operations on plaintext", "Encrypting files twice with different keys", "Converting text to base64", "Compressing files before encryption", "A cryptographic form that allows computations to be performed directly on encrypted ciphertexts, generating an encrypted result that decrypts to match operations on plaintext", "HARD"));

        return list;
    }

    public static List<QuestionItem> getDistributedSystemsQuestions() {
        List<QuestionItem> list = new ArrayList<>();
        // 20 EASY
        list.add(new QuestionItem("What is a Distributed System?", "A collection of independent, autonomous computers that appear to users as a single coherent system", "A single supercomputer with many cores", "A local database with multiple tables", "A software library for multi-threading", "A collection of independent, autonomous computers that appear to users as a single coherent system", "EASY"));
        list.add(new QuestionItem("What does the CAP Theorem state regarding distributed data stores?", "It is impossible for a distributed data store to simultaneously provide Consistency, Availability, and Partition Tolerance", "Systems must be Cost-effective, Agile, and Performant", "Caches, Arrays, and Processors must be balanced", "Only Centralized systems can be Available", "It is impossible for a distributed data store to simultaneously provide Consistency, Availability, and Partition Tolerance", "EASY"));
        list.add(new QuestionItem("What does the 'P' stand for in the CAP theorem?", "Partition Tolerance (system continues to operate despite arbitrary network message loss or delay)", "Performance", "Parallelism", "Persistence", "Partition Tolerance (system continues to operate despite arbitrary network message loss or delay)", "EASY"));
        list.add(new QuestionItem("What does the 'C' stand for in the CAP theorem?", "Consistency (every read receives the most recent write or an error)", "Concurrency", "Capacity", "Coherence", "Consistency (every read receives the most recent write or an error)", "EASY"));
        list.add(new QuestionItem("What does the 'A' stand for in the CAP theorem?", "Availability (every non-failing node returns a non-error response for every request)", "Accuracy", "Authentication", "Atomicity", "Availability (every non-failing node returns a non-error response for every request)", "EASY"));
        list.add(new QuestionItem("What communication paradigm allows a computer program to cause a subroutine to execute on another computer without explicit coding of remote details?", "Remote Procedure Call (RPC)", "Shared Memory", "File Transfer Protocol", "Pipes", "Remote Procedure Call (RPC)", "EASY"));
        list.add(new QuestionItem("What does gRPC use as its default Interface Definition Language (IDL) and serialization mechanism?", "Protocol Buffers (protobuf)", "JSON", "XML", "YAML", "Protocol Buffers (protobuf)", "EASY"));
        list.add(new QuestionItem("What is horizontal scaling (scaling out) in distributed architecture?", "Adding more computer nodes/servers to the pool of resources", "Upgrading CPU and RAM on a single server", "Increasing network cable length", "Writing multi-threaded code", "Adding more computer nodes/servers to the pool of resources", "EASY"));
        list.add(new QuestionItem("What is vertical scaling (scaling up)?", "Adding more power (CPU, RAM, disk) to an existing single machine", "Adding more servers to a cluster", "Deploying to multiple cloud regions", "Splitting database into microservices", "Adding more power (CPU, RAM, disk) to an existing single machine", "EASY"));
        list.add(new QuestionItem("What distributed architecture model divides work between service requesters (clients) and service providers (servers)?", "Client-Server Architecture", "Peer-to-Peer Architecture", "Master-Slave Architecture", "Pipeline Architecture", "Client-Server Architecture", "EASY"));
        list.add(new QuestionItem("What distributed architecture model gives every participating node equal privilege and responsibility without central coordination?", "Peer-to-Peer (P2P)", "Client-Server", "Mainframe-Terminal", "Three-Tier Architecture", "Peer-to-Peer (P2P)", "EASY"));
        list.add(new QuestionItem("What is a heartbeat mechanism in distributed systems?", "Periodic signals sent between nodes to announce that a node is alive and functioning properly", "A hardware clock crystal", "A CPU cooler pulse", "A database query timer", "Periodic signals sent between nodes to announce that a node is alive and functioning properly", "EASY"));
        list.add(new QuestionItem("What is data replication in distributed systems?", "Storing copies of the same data across multiple distinct nodes to enhance reliability, fault tolerance, and read performance", "Compressing files before saving", "Deleting redundant records", "Encrypting database backups", "Storing copies of the same data across multiple distinct nodes to enhance reliability, fault tolerance, and read performance", "EASY"));
        list.add(new QuestionItem("What is database sharding (horizontal partitioning)?", "Splitting a database table rows across multiple distinct database servers based on a shard key", "Normalizing database tables to BCNF", "Creating B+ Tree indexes", "Taking hourly database snapshots", "Splitting a database table rows across multiple distinct database servers based on a shard key", "EASY"));
        list.add(new QuestionItem("What is a message broker (e.g., Apache Kafka, RabbitMQ) in distributed architectures?", "An intermediary program that decouples producers and consumers by handling message queuing, routing, and delivery", "A network router", "A database query compiler", "A firewall controller", "An intermediary program that decouples producers and consumers by handling message queuing, routing, and delivery", "EASY"));
        list.add(new QuestionItem("What messaging pattern distributes messages to all subscribed services without the sender knowing who the subscribers are?", "Publish-Subscribe (Pub/Sub)", "Point-to-Point", "Request-Response", "Polling", "Publish-Subscribe (Pub/Sub)", "EASY"));
        list.add(new QuestionItem("What is latency in a distributed network?", "The time taken for a packet of data to travel from source to destination across the network", "The maximum amount of data that can be transferred per second", "The storage capacity of the hard disk", "The number of CPU cores", "The time taken for a packet of data to travel from source to destination across the network", "EASY"));
        list.add(new QuestionItem("What is throughput in distributed systems?", "The rate at which successful transactions or operations are processed per unit of time", "The round-trip ping time", "The size of the server memory", "The number of network cables", "The rate at which successful transactions or operations are processed per unit of time", "EASY"));
        list.add(new QuestionItem("What is a single point of failure (SPOF)?", "A component whose failure will cause the entire system or service to cease functioning", "A software syntax error", "A disconnected mouse", "A slow internet connection", "A component whose failure will cause the entire system or service to cease functioning", "EASY"));
        list.add(new QuestionItem("What is fault tolerance in distributed computing?", "The ability of a system to continue operating properly in the event of the failure of one or more of its components", "The ability to run without electricity", "The ability to prevent all bugs", "The ability to eliminate network latency", "The ability of a system to continue operating properly in the event of the failure of one or more of its components", "EASY"));

        // 20 MEDIUM
        list.add(new QuestionItem("What are Lamport Timestamps used for in distributed systems?", "Providing a partial logical ordering of events across distributed nodes without requiring synchronized physical clocks", "Measuring CPU clock cycle execution times", "Calculating network round-trip ping", "Synchronizing timezone offsets", "Providing a partial logical ordering of events across distributed nodes without requiring synchronized physical clocks", "MEDIUM"));
        list.add(new QuestionItem("What are Vector Clocks and how do they improve upon Lamport Timestamps?", "An array of logical clocks maintained by each process that captures causal relationships and detects concurrent events", "They measure physical time in nanoseconds", "They eliminate network latency", "They require GPS hardware on every server", "An array of logical clocks maintained by each process that captures causal relationships and detects concurrent events", "MEDIUM"));
        list.add(new QuestionItem("What is Consistent Hashing and why is it preferred for distributed caching (e.g. Memcached, Cassandra)?", "Maps both keys and servers to a hash ring so that adding/removing nodes only requires remapping K/N keys rather than all keys", "Computes SHA-256 hashes in constant time", "Encrypts all cache entries", "Eliminates cache misses completely", "Maps both keys and servers to a hash ring so that adding/removing nodes only requires remapping K/N keys rather than all keys", "MEDIUM"));
        list.add(new QuestionItem("What is the Two-Phase Commit (2PC) protocol?", "An atomic commitment protocol consisting of a Prepare phase (voting) and a Commit/Abort phase managed by a coordinator", "A two-step user login process", "A database backup technique", "A Git merge workflow", "An atomic commitment protocol consisting of a Prepare phase (voting) and a Commit/Abort phase managed by a coordinator", "MEDIUM"));
        list.add(new QuestionItem("What is the primary operational vulnerability of the Two-Phase Commit (2PC) protocol?", "It is a blocking protocol: if the coordinator crashes after nodes vote Yes, participants must wait indefinitely holding locks", "It cannot guarantee consistency", "It allows dirty reads", "It only works on two nodes", "It is a blocking protocol: if the coordinator crashes after nodes vote Yes, participants must wait indefinitely holding locks", "MEDIUM"));
        list.add(new QuestionItem("What is the Paxos Consensus Algorithm?", "A consensus protocol for reaching agreement among a network of unreliable processors in the presence of crash failures", "A routing algorithm for packet switching", "A compression algorithm for text files", "A cryptographic hashing algorithm", "A consensus protocol for reaching agreement among a network of unreliable processors in the presence of crash failures", "MEDIUM"));
        list.add(new QuestionItem("How does the Raft consensus algorithm make consensus more understandable compared to Paxos?", "Decomposes consensus into distinct subproblems: Leader Election, Log Replication, and Safety invariants", "Uses neural networks to vote", "Disables log replication", "Requires dedicated hardware", "Decomposes consensus into distinct subproblems: Leader Election, Log Replication, and Safety invariants", "MEDIUM"));
        list.add(new QuestionItem("What is the Byzantine Generals Problem in fault-tolerant distributed systems?", "Reaching consensus when participating nodes may not only fail or crash, but also send conflicting or malicious messages", "Finding the shortest path in a graph", "Allocating memory to virtual machines", "Sorting numbers across multiple threads", "Reaching consensus when participating nodes may not only fail or crash, but also send conflicting or malicious messages", "MEDIUM"));
        list.add(new QuestionItem("In a system of N nodes, how many faulty Byzantine nodes (f) can be tolerated by Practical Byzantine Fault Tolerance (PBFT)?", "At most f < N / 3 (requires N >= 3f + 1)", "At most f < N / 2", "At most f = N - 1", "Zero nodes", "At most f < N / 3 (requires N >= 3f + 1)", "MEDIUM"));
        list.add(new QuestionItem("What is the PACELC Theorem an extension of?", "CAP theorem: If Partition (P), choose Availability (A) or Consistency (C); Else (E), choose Latency (L) or Consistency (C)", "Moore's Law", "Amdahl's Law", "Little's Law", "CAP theorem: If Partition (P), choose Availability (A) or Consistency (C); Else (E), choose Latency (L) or Consistency (C)", "MEDIUM"));
        list.add(new QuestionItem("What is an Idempotent API operation in distributed systems?", "An operation that produces the exact same side-effect on the system state regardless of how many times it is repeated", "An operation that returns immediately in 0 ms", "An operation that cannot be canceled", "An operation that runs on multiple threads", "An operation that produces the exact same side-effect on the system state regardless of how many times it is repeated", "MEDIUM"));
        list.add(new QuestionItem("What is the purpose of Distributed Tracing (e.g., OpenTelemetry, Jaeger)?", "Tracks the lifecycle of requests as they flow across multiple microservices by propagating trace and span IDs", "Compiles microservices in parallel", "Backs up distributed databases", "Filters DDoS attacks", "Tracks the lifecycle of requests as they flow across multiple microservices by propagating trace and span IDs", "MEDIUM"));
        list.add(new QuestionItem("What is a Gossip Protocol (Epidemic Protocol) in peer-to-peer networks?", "A decentralized communication protocol where nodes periodically exchange state with randomly chosen neighbors to achieve eventual consistency", "A protocol that logs employee chats", "A high-speed optical fiber protocol", "A secure encryption protocol", "A decentralized communication protocol where nodes periodically exchange state with randomly chosen neighbors to achieve eventual consistency", "MEDIUM"));
        list.add(new QuestionItem("In distributed data stores, what is Quorum Consistency (R + W > N)?", "If read quorum R and write quorum W sum to greater than total replicas N, read quorum is guaranteed to overlap with latest write", "All nodes must vote unanimously on every read", "Replicas are never updated", "Data is replicated to 100 nodes", "If read quorum R and write quorum W sum to greater than total replicas N, read quorum is guaranteed to overlap with latest write", "MEDIUM"));
        list.add(new QuestionItem("What is a Distributed Lock Manager (DLM, e.g. Redlock, Zookeeper locks) used for?", "Coordinates mutually exclusive access to shared resources across independent machines in a cluster", "Locks computer screens when idle", "Encrypts hard drives on servers", "Prevents unauthorized SSH access", "Coordinates mutually exclusive access to shared resources across independent machines in a cluster", "MEDIUM"));
        list.add(new QuestionItem("What is Eventual Consistency?", "A consistency model guaranteeing that, if no new updates are made, all replicas will eventually return the same latest value", "Data is never consistent", "Writes are immediately visible to all nodes instantly", "Transactions cannot be aborted", "A consistency model guaranteeing that, if no new updates are made, all replicas will eventually return the same latest value", "MEDIUM"));
        list.add(new QuestionItem("What is the Split-Brain problem in distributed clustering?", "A network partition causes isolated partitions to both assume leadership, resulting in conflicting writes and data corruption", "A CPU core running out of memory", "A dual-boot operating system failure", "A cable disconnection between two switches", "A network partition causes isolated partitions to both assume leadership, resulting in conflicting writes and data corruption", "MEDIUM"));
        list.add(new QuestionItem("What is the role of an Election Algorithm (e.g. Bully Algorithm, Ring Algorithm) in distributed systems?", "Selects a unique coordinator or leader process among active participating nodes following a failure", "Votes on feature requests from users", "Balances network packet routing", "Compresses log files", "Selects a unique coordinator or leader process among active participating nodes following a failure", "MEDIUM"));
        list.add(new QuestionItem("What is Read Repair in distributed databases like Apache Cassandra?", "A background process where inconsistencies detected among replica nodes during a read operation are corrected", "Fixing physical disk sectors", "Restoring database from tape", "Rerouting network traffic", "A background process where inconsistencies detected among replica nodes during a read operation are corrected", "MEDIUM"));
        list.add(new QuestionItem("What is Linearizability (Strong Consistency) in distributed computing?", "Every operation appears to take effect instantaneously at a precise point in real time between its invocation and response", "Operations are processed in random order", "Operations can be delayed up to 24 hours", "Reads always return null", "Every operation appears to take effect instantaneously at a precise point in real time between its invocation and response", "MEDIUM"));

        // 10 HARD
        list.add(new QuestionItem("What is the FLP Impossibility Theorem (Fischer, Lynch, Paterson)?", "In an asynchronous network, no deterministic consensus protocol can guarantee both safety and liveness in the presence of even a single unannounced crash failure", "No distributed system can scale beyond 1000 nodes", "Quantum computers cannot run consensus algorithms", "Network packets will always be duplicated", "In an asynchronous network, no deterministic consensus protocol can guarantee both safety and liveness in the presence of even a single unannounced crash failure", "HARD"));
        list.add(new QuestionItem("What are Conflict-Free Replicated Data Types (CRDTs)?", "Data structures that can be replicated across nodes and modified concurrently without coordination, guaranteed to mathematically converge without conflicts", "Encrypted relational database tables", "In-memory cache locks", "Hardware register models", "Data structures that can be replicated across nodes and modified concurrently without coordination, guaranteed to mathematically converge without conflicts", "HARD"));
        list.add(new QuestionItem("What is the difference between Operation-based (Op-based) and State-based (CvRDT) CRDTs?", "State-based sends full state and merges using a join semilattice; Op-based transmits operations assuming causal reliable broadcast", "State-based requires atomic locks; Op-based does not", "Op-based only works on single nodes", "State-based cannot handle deletes", "State-based sends full state and merges using a join semilattice; Op-based transmits operations assuming causal reliable broadcast", "HARD"));
        list.add(new QuestionItem("In distributed databases, what is Casual Consistency and what anomaly can it still permit?", "Guarantees operations causally related are seen in the same order by all nodes; permits concurrent writes to be seen in different orders by different nodes", "Permits dirty reads", "Forbids reads from secondary replicas", "Requires GPS clocks on all nodes", "Guarantees operations causally related are seen in the same order by all nodes; permits concurrent writes to be seen in different orders by different nodes", "HARD"));
        list.add(new QuestionItem("What is the Chubby lock service developed by Google and what underlying algorithm does it implement?", "A distributed lock service providing coarse-grained locking and reliable low-volume storage, implemented using Paxos", "A hardware biometric scanner", "A web load balancer based on Round Robin", "An asynchronous message queue", "A distributed lock service providing coarse-grained locking and reliable low-volume storage, implemented using Paxos", "HARD"));
        list.add(new QuestionItem("How does the Raft consensus algorithm handle a network partition where the leader is isolated with a minority of nodes?", "Leader cannot achieve quorum for log entries; majority partition elects a new leader with higher term; old leader steps down upon reconnection", "Old leader shuts down physical servers", "Both partitions continue committing transactions independently", "Cluster permanently halts execution", "Leader cannot achieve quorum for log entries; majority partition elects a new leader with higher term; old leader steps down upon reconnection", "HARD"));
        list.add(new QuestionItem("In Apache Kafka architecture, how does Partition Leadership and the In-Sync Replicas (ISR) list guarantee durability without waiting for all replicas?", "Messages are committed once acknowledged by all replicas in the active ISR list; failed replicas that lag behind are dropped from ISR", "Messages are written to disk on every single broker in the world", "Only the leader broker writes to disk", "Messages are kept only in RAM", "Messages are committed once acknowledged by all replicas in the active ISR list; failed replicas that lag behind are dropped from ISR", "HARD"));
        list.add(new QuestionItem("What is the difference between at-least-once, at-most-once, and exactly-once processing semantics in stream processing (e.g. Apache Flink)?", "At-least-once may duplicate messages on failure; at-most-once may drop messages; exactly-once guarantees state updates reflect each message exactly once via checkpoints", "At-most-once is the most reliable", "Exactly-once cannot be achieved in software", "At-least-once never sends duplicates", "At-least-once may duplicate messages on failure; at-most-once may drop messages; exactly-once guarantees state updates reflect each message exactly once via checkpoints", "HARD"));
        list.add(new QuestionItem("What is the Chandy-Lamport algorithm used for in distributed systems?", "Determines a consistent global state (snapshot) of a distributed system without freezing execution or interrupting channels", "Elects a leader in wireless sensor networks", "Encrypts communication between nodes", "Detects deadlocks in single-core processors", "Determines a consistent global state (snapshot) of a distributed system without freezing execution or interrupting channels", "HARD"));
        list.add(new QuestionItem("In large-scale key-value stores (e.g. Amazon Dynamo), what mechanism resolves concurrent conflicting writes when vector clocks diverge?", "Client-side reconciliation (e.g. shopping cart merge) or Last-Write-Wins (LWW) resolution policy", "Dropping both writes", "Crashing the database node", "Locking all tables for 1 hour", "Client-side reconciliation (e.g. shopping cart merge) or Last-Write-Wins (LWW) resolution policy", "HARD"));

        return list;
    }
}
