package exam_management_syatem.db;

import java.util.ArrayList;
import java.util.List;
import exam_management_syatem.db.QuestionBankPart1.QuestionItem;

public class QuestionBankPart2 {

    public static List<QuestionItem> getComputerNetworksQuestions() {
        List<QuestionItem> list = new ArrayList<>();
        // 20 EASY
        list.add(new QuestionItem("How many layers are in the OSI reference model?", "4", "5", "7", "6", "7", "EASY"));
        list.add(new QuestionItem("Which layer of the OSI model is responsible for routing packets across networks?", "Data Link Layer", "Network Layer", "Transport Layer", "Physical Layer", "Network Layer", "EASY"));
        list.add(new QuestionItem("What protocol resolves an IP address to a physical MAC address on a local area network?", "DNS", "DHCP", "ARP", "ICMP", "ARP", "EASY"));
        list.add(new QuestionItem("Which transport layer protocol is connection-oriented and guarantees reliable packet delivery?", "UDP", "TCP", "IP", "ICMP", "TCP", "EASY"));
        list.add(new QuestionItem("Which transport layer protocol is connectionless and prioritized for low latency?", "TCP", "UDP", "SCTP", "FTP", "UDP", "EASY"));
        list.add(new QuestionItem("What is the default port number used by standard unencrypted HTTP traffic?", "21", "80", "443", "8080", "80", "EASY"));
        list.add(new QuestionItem("What is the default port number used by HTTPS traffic?", "80", "22", "443", "53", "443", "EASY"));
        list.add(new QuestionItem("What is the size of an IPv4 address in bits?", "32-bit", "64-bit", "128-bit", "16-bit", "32-bit", "EASY"));
        list.add(new QuestionItem("What is the size of an IPv6 address in bits?", "32-bit", "64-bit", "128-bit", "256-bit", "128-bit", "EASY"));
        list.add(new QuestionItem("Which device operates at Layer 2 (Data Link) and forwards frames based on MAC addresses?", "Hub", "Switch", "Router", "Repeater", "Switch", "EASY"));
        list.add(new QuestionItem("What is the standard loopback IP address in IPv4?", "192.168.1.1", "10.0.0.1", "127.0.0.1", "255.255.255.255", "127.0.0.1", "EASY"));
        list.add(new QuestionItem("What protocol automatically assigns IP configuration settings to client devices on a network?", "DNS", "DHCP", "SNMP", "NTP", "DHCP", "EASY"));
        list.add(new QuestionItem("Which protocol translates human-readable domain names into IP addresses?", "DHCP", "DNS", "FTP", "SSH", "DNS", "EASY"));
        list.add(new QuestionItem("What utility uses ICMP echo request and reply messages to test network reachability?", "traceroute", "ping", "netstat", "ipconfig", "ping", "EASY"));
        list.add(new QuestionItem("What topology connects all devices to a single central hub or switch?", "Bus", "Ring", "Star", "Mesh", "Star", "EASY"));
        list.add(new QuestionItem("What is the maximum theoretical length of a standard Ethernet twisted-pair cable (Cat5e/Cat6) segment?", "50 meters", "100 meters", "500 meters", "1000 meters", "100 meters", "EASY"));
        list.add(new QuestionItem("What is the default port for SSH (Secure Shell)?", "21", "22", "23", "25", "22", "EASY"));
        list.add(new QuestionItem("Which email protocol is used for sending outgoing emails between servers?", "POP3", "IMAP", "SMTP", "SNMP", "SMTP", "EASY"));
        list.add(new QuestionItem("What is a MAC address composed of in terms of hexadecimal digits and bits?", "32 bits (8 hex digits)", "48 bits (12 hex digits)", "64 bits (16 hex digits)", "128 bits (32 hex digits)", "48 bits (12 hex digits)", "EASY"));
        list.add(new QuestionItem("Which layer in the TCP/IP model corresponds to OSI Sessions, Presentation, and Application layers combined?", "Transport Layer", "Network Access Layer", "Application Layer", "Internet Layer", "Application Layer", "EASY"));

        // 20 MEDIUM
        list.add(new QuestionItem("What is the TCP 3-way handshake sequence used to establish a connection?", "SYN -> SYN-ACK -> ACK", "ACK -> SYN -> SYN-ACK", "SYN -> ACK -> DATA", "FIN -> ACK -> FIN-ACK", "SYN -> SYN-ACK -> ACK", "MEDIUM"));
        list.add(new QuestionItem("How does the Stop-and-Wait ARQ protocol differ from Go-Back-N ARQ?", "Stop-and-Wait transmits one frame and waits for ACK before sending the next", "Stop-and-Wait uses a window of size N", "Stop-and-Wait never retransmits", "Go-Back-N does not require acknowledgments", "Stop-and-Wait transmits one frame and waits for ACK before sending the next", "MEDIUM"));
        list.add(new QuestionItem("What is the purpose of CIDR (Classless Inter-Domain Routing) notation?", "Allocates IP address blocks flexibly using variable-length subnet masking (VLSM)", "Replaces IPv4 with IPv6", "Encrypts routing tables", "Disables network firewalls", "Allocates IP address blocks flexibly using variable-length subnet masking (VLSM)", "MEDIUM"));
        list.add(new QuestionItem("In /24 IPv4 subnet mask (255.255.255.0), how many usable host addresses are available?", "256", "254", "255", "128", "254", "MEDIUM"));
        list.add(new QuestionItem("What routing algorithm is used by OSPF (Open Shortest Path First)?", "Bellman-Ford distance vector", "Dijkstra's link-state algorithm", "Floyd-Warshall", "Spanning tree algorithm", "Dijkstra's link-state algorithm", "MEDIUM"));
        list.add(new QuestionItem("Which exterior gateway protocol is used to exchange routing and reachability information between Autonomous Systems on the global Internet?", "RIP", "EIGRP", "OSPF", "BGP (Border Gateway Protocol)", "BGP (Border Gateway Protocol)", "MEDIUM"));
        list.add(new QuestionItem("What is the Count-to-Infinity problem in distance-vector routing protocols, and what technique mitigates it?", "Routing loops caused by slow convergence; mitigated by split horizon and poison reverse", "Buffer overflow in routers; mitigated by RED", "Packet loss on optical fiber; mitigated by FEC", "DNS cache poisoning; mitigated by DNSSEC", "Routing loops caused by slow convergence; mitigated by split horizon and poison reverse", "MEDIUM"));
        list.add(new QuestionItem("In TCP congestion control, what happens when packet loss is detected via 3 duplicate ACKs (Fast Retransmit)?", "Slow start resets cwnd to 1 MSS", "Fast Recovery halves cwnd and performs fast retransmission without dropping to 1 MSS", "Connection is terminated", "Receiver window is set to zero", "Fast Recovery halves cwnd and performs fast retransmission without dropping to 1 MSS", "MEDIUM"));
        list.add(new QuestionItem("What is Network Address Translation (NAT) and why was it introduced?", "Translates private RFC 1918 IP addresses into public IP addresses to alleviate IPv4 exhaustion", "Encrypts all payload data", "Compresses HTTP headers", "Calculates packet checksums", "Translates private RFC 1918 IP addresses into public IP addresses to alleviate IPv4 exhaustion", "MEDIUM"));
        list.add(new QuestionItem("What is the role of the Spanning Tree Protocol (STP) in bridged Ethernet local area networks?", "Prevents switching loops and broadcast storms by blocking redundant paths", "Encrypts Layer 2 frames", "Assigns VLAN IDs dynamically", "Performs Layer 3 IP routing", "Prevents switching loops and broadcast storms by blocking redundant paths", "MEDIUM"));
        list.add(new QuestionItem("What does the Time-to-Live (TTL) field in an IPv4 packet header prevent?", "Packets from circulating indefinitely in routing loops", "Unauthorized decryption", "TCP retransmissions", "Duplicate IP address assignments", "Packets from circulating indefinitely in routing loops", "MEDIUM"));
        list.add(new QuestionItem("What does CSMA/CD stand for in Ethernet networking?", "Carrier Sense Multiple Access with Collision Detection", "Channel State Multiplexing with Conflict Delay", "Client Server Mode Access with Collision Domain", "Core Switch Media Access with Carrier Division", "Carrier Sense Multiple Access with Collision Detection", "MEDIUM"));
        list.add(new QuestionItem("Why is CSMA/CA (Collision Avoidance) used in Wi-Fi (802.11) instead of CSMA/CD?", "Wireless stations cannot detect collisions while transmitting due to signal attenuation", "Wi-Fi does not use radio frequencies", "Collisions are impossible in wireless media", "Wireless frames have no MAC addresses", "Wireless stations cannot detect collisions while transmitting due to signal attenuation", "MEDIUM"));
        list.add(new QuestionItem("In TCP, what mechanism does the receiver use to prevent the sender from overwhelming its buffer space?", "Congestion window (cwnd)", "Receive window (rwnd) flow control advertising", "Nagle algorithm", "Path MTU discovery", "Receive window (rwnd) flow control advertising", "MEDIUM"));
        list.add(new QuestionItem("What is the difference between persistent HTTP (HTTP/1.1) and non-persistent HTTP (HTTP/1.0)?", "HTTP/1.1 can reuse a single TCP connection for multiple HTTP requests/responses", "HTTP/1.1 requires UDP", "HTTP/1.0 supports streaming video", "HTTP/1.1 does not support cookies", "HTTP/1.1 can reuse a single TCP connection for multiple HTTP requests/responses", "MEDIUM"));
        list.add(new QuestionItem("What does HTTP/2 multiplexing achieve over a single TCP connection?", "Interleaves multiple concurrent request and response streams to eliminate Head-of-Line blocking at application layer", "Uses multiple IP addresses", "Compresses images with lossless WebP", "Disables TLS encryption", "Interleaves multiple concurrent request and response streams to eliminate Head-of-Line blocking at application layer", "MEDIUM"));
        list.add(new QuestionItem("Which DNS record type maps a domain name to an IPv6 address?", "A record", "AAAA record", "CNAME record", "MX record", "AAAA record", "MEDIUM"));
        list.add(new QuestionItem("What is the function of ICMP in the Internet protocol suite?", "Reports network transmission errors and operational query information", "Transfers large files reliably", "Allocates dynamic IP addresses", "Establishes VPN tunnels", "Reports network transmission errors and operational query information", "MEDIUM"));
        list.add(new QuestionItem("In SSL/TLS, what is the purpose of Diffie-Hellman Ephemeral (DHE/ECDHE) key exchange?", "Provides Perfect Forward Secrecy (PFS)", "Eliminates server digital certificates", "Speeds up symmetric AES hashing", "Compresses TCP payload", "Provides Perfect Forward Secrecy (PFS)", "MEDIUM"));
        list.add(new QuestionItem("What is the purpose of the Nagle algorithm in TCP implementations?", "Combines small outgoing packets into a single segment to avoid Small Packet Problem", "Limits TCP window size to 1 KB", "Enforces immediate packet transmission without buffer", "Closes idle connections after 60 seconds", "Combines small outgoing packets into a single segment to avoid Small Packet Problem", "MEDIUM"));

        // 10 HARD
        list.add(new QuestionItem("What underlying transport protocol does HTTP/3 utilize, and what primary limitation of TCP does it eliminate?", "QUIC over UDP; eliminates TCP head-of-line blocking across independent streams", "SCTP; eliminates IP packet fragmentation", "Raw IP; removes transport header overhead", "TLS over TCP; eliminates DNS lookups", "QUIC over UDP; eliminates TCP head-of-line blocking across independent streams", "HARD"));
        list.add(new QuestionItem("In BGP routing, what does the MED (Multi-Exit Discriminator) attribute convey to an external neighboring AS?", "Suggestions on the preferred entry path into the advertising AS when multiple links exist", "The internal router cost to reach the destination", "The total autonomous system path length", "A directive that forces immediate traffic disconnection", "Suggestions on the preferred entry path into the advertising AS when multiple links exist", "HARD"));
        list.add(new QuestionItem("What is Bufferbloat in computer networking, and what queue management algorithm mitigates it?", "Excessive packet buffering in routers causing massive latency; mitigated by CoDel (Controlled Delay) and FQ-CoDel", "Memory leak in network interface cards; mitigated by rebooting", "TCP window overflow; mitigated by Reno", "Routing table exhaustion; mitigated by CIDR", "Excessive packet buffering in routers causing massive latency; mitigated by CoDel (Controlled Delay) and FQ-CoDel", "HARD"));
        list.add(new QuestionItem("How does BBR (Bottleneck Bandwidth and RTT) congestion control fundamentally differ from loss-based TCP algorithms like Cubic and Reno?", "BBR models network delivery rate and min RTT to operate at max throughput without filling queues", "BBR treats any packet drop as an emergency back-off signal", "BBR requires explicit congestion notification (ECN) on every hop", "BBR disables TCP sliding window", "BBR models network delivery rate and min RTT to operate at max throughput without filling queues", "HARD"));
        list.add(new QuestionItem("What vulnerability does DNSSEC (Domain Name System Security Extensions) address using cryptographic signatures?", "DNS cache poisoning and spoofing", "DDoS amplification attacks", "Slow DNS resolution speed", "IPv6 packet loss", "DNS cache poisoning and spoofing", "HARD"));
        list.add(new QuestionItem("In MPLS (Multiprotocol Label Switching), how are packets forwarded through the provider core network?", "By inspecting short fixed-length labels in the MPLS header rather than IP routing tables", "By full deep packet inspection (DPI)", "By calculating SHA-256 hashes of every packet", "By broadcasting to all egress switches", "By inspecting short fixed-length labels in the MPLS header rather than IP routing tables", "HARD"));
        list.add(new QuestionItem("What is the difference between Anycast routing and Unicast routing?", "Anycast routes packets to the topologically closest node among multiple nodes sharing the same IP address", "Anycast sends packets to every device on subnet", "Anycast is restricted to wireless networks", "Anycast does not use routing protocols", "Anycast routes packets to the topologically closest node among multiple nodes sharing the same IP address", "HARD"));
        list.add(new QuestionItem("What is the purpose of eBPF (Extended Berkeley Packet Filter) in high-performance Linux network packet processing?", "Runs sandboxed custom code inside kernel space at XDP/TC hooks for line-rate filtering and telemetry without context switching", "Replaces standard ethernet drivers with proprietary code", "Emulates Windows networking APIs", "Enforces disk quotas on FTP servers", "Runs sandboxed custom code inside kernel space at XDP/TC hooks for line-rate filtering and telemetry without context switching", "HARD"));
        list.add(new QuestionItem("How does the SYN Flood attack exploit the TCP state machine, and what is the standard defense?", "Sends flood of SYN packets without ACK to exhaust embryonic connection table; defended by SYN Cookies", "Sends malformed FIN packets; defended by disabling firewall", "Spoofs DNS records; defended by DNSSEC", "Floods ICMP echo replies; defended by NAT", "Sends flood of SYN packets without ACK to exhaust embryonic connection table; defended by SYN Cookies", "HARD"));
        list.add(new QuestionItem("In Software-Defined Networking (SDN), what architectural separation is established?", "Separation of the Control Plane (centralized controller) from the Data Plane (forwarding switches)", "Separation of LAN from WAN", "Separation of IPv4 from IPv6", "Separation of physical memory from virtual memory", "Separation of the Control Plane (centralized controller) from the Data Plane (forwarding switches)", "HARD"));

        return list;
    }

    public static List<QuestionItem> getSoftwareEngineeringQuestions() {
        List<QuestionItem> list = new ArrayList<>();
        // 20 EASY
        list.add(new QuestionItem("What does SDLC stand for in software engineering?", "Software Development Life Cycle", "System Design and Language Compilation", "Standard Development Logic Control", "Security Development Licensing Code", "Software Development Life Cycle", "EASY"));
        list.add(new QuestionItem("Which software development model follows a strict linear sequential flow of phases?", "Agile Model", "Waterfall Model", "Spiral Model", "RAD Model", "Waterfall Model", "EASY"));
        list.add(new QuestionItem("In Scrum, what is a time-boxed iteration during which a team produces a working product increment called?", "Sprint", "Epic", "Milestone", "Backlog", "Sprint", "EASY"));
        list.add(new QuestionItem("What is the primary document containing the formal requirements agreed upon between client and developers?", "Software Requirements Specification (SRS)", "User Acceptance Plan", "Design Document Specification", "Architecture Blueprint", "Software Requirements Specification (SRS)", "EASY"));
        list.add(new QuestionItem("Which testing level verifies that individual functions, procedures, or methods work correctly in isolation?", "Integration Testing", "System Testing", "Unit Testing", "Acceptance Testing", "Unit Testing", "EASY"));
        list.add(new QuestionItem("What type of testing tests the software without knowledge of the internal source code structure?", "White Box Testing", "Black Box Testing", "Gray Box Testing", "Mutation Testing", "Black Box Testing", "EASY"));
        list.add(new QuestionItem("What type of testing tests internal paths, branch structures, and code logic?", "Black Box Testing", "White Box Testing", "Performance Testing", "Stress Testing", "White Box Testing", "EASY"));
        list.add(new QuestionItem("What is the process of restructuring existing computer code without changing its external behavior called?", "Refactoring", "Compiling", "Debugging", "Reverse Engineering", "Refactoring", "EASY"));
        list.add(new QuestionItem("What does CI/CD stand for in modern DevOps practices?", "Continuous Integration / Continuous Delivery (or Deployment)", "Code Inspection / Code Distribution", "Centralized Integration / Command Dispatch", "Continuous Iteration / Continuous Debugging", "Continuous Integration / Continuous Delivery (or Deployment)", "EASY"));
        list.add(new QuestionItem("Which Git command creates a copy of an existing remote repository onto a local machine?", "git pull", "git push", "git clone", "git commit", "git clone", "EASY"));
        list.add(new QuestionItem("In Agile Scrum, what role is responsible for prioritizing the product backlog and representing stakeholders?", "Scrum Master", "Product Owner", "Lead Developer", "QA Lead", "Product Owner", "EASY"));
        list.add(new QuestionItem("What is testing conducted to determine if recent code changes have broken existing working features called?", "Smoke Testing", "Regression Testing", "Sanity Testing", "Stress Testing", "Regression Testing", "EASY"));
        list.add(new QuestionItem("Which diagram in UML represents the dynamic sequence of interactions and messages between objects over time?", "Class Diagram", "Sequence Diagram", "Use Case Diagram", "Deployment Diagram", "Sequence Diagram", "EASY"));
        list.add(new QuestionItem("What is a lightweight representation of a software requirement written from an end-user's perspective called?", "User Story", "Use Case", "Test Case", "Functional Spec", "User Story", "EASY"));
        list.add(new QuestionItem("What does the 'DRY' software engineering principle stand for?", "Don't Repeat Yourself", "Do Repeat Yourself", "Deploy Rapidly Yearly", "Design Robust Yields", "Don't Repeat Yourself", "EASY"));
        list.add(new QuestionItem("What does the 'KISS' design principle stand for?", "Keep It Simple, Stupid", "Know Interface Single State", "Keep Integration System Safe", "Kernel Interface Shared State", "Keep It Simple, Stupid", "EASY"));
        list.add(new QuestionItem("What metric measures the degree to which elements inside a single module belong together?", "Coupling", "Cohesion", "Complexity", "Modularity", "Cohesion", "EASY"));
        list.add(new QuestionItem("What metric measures the degree of interdependence between separate software modules?", "Cohesion", "Coupling", "Encapsulation", "Inheritance", "Coupling", "EASY"));
        list.add(new QuestionItem("In good software design, what relationship between cohesion and coupling is strongly desired?", "High cohesion and low coupling", "Low cohesion and high coupling", "High cohesion and high coupling", "Low cohesion and low coupling", "High cohesion and low coupling", "EASY"));
        list.add(new QuestionItem("What type of testing evaluates system performance under extreme operational conditions beyond anticipated peak limits?", "Functional Testing", "Stress Testing", "Usability Testing", "Regression Testing", "Stress Testing", "EASY"));

        // 20 MEDIUM
        list.add(new QuestionItem("What are the four phases of the Unified Process (UP) / Rational Unified Process (RUP)?", "Inception, Elaboration, Construction, Transition", "Requirement, Design, Code, Test", "Plan, Do, Check, Act", "Discovery, Prototyping, Delivery, Maintenance", "Inception, Elaboration, Construction, Transition", "MEDIUM"));
        list.add(new QuestionItem("What is the primary risk-driven characteristic of Boehm's Spiral Model?", "Explicit risk assessment and prototyping cycles in each spiral iteration", "Fixed price contracts", "Complete upfront documentation without changes", "Single release at the end", "Explicit risk assessment and prototyping cycles in each spiral iteration", "MEDIUM"));
        list.add(new QuestionItem("What does McCabe's Cyclomatic Complexity measure in software source code?", "Number of lines of code", "Number of linearly independent execution paths through code", "Number of global variables", "Execution speed in milliseconds", "Number of linearly independent execution paths through code", "MEDIUM"));
        list.add(new QuestionItem("What is Equivalence Partitioning in black-box software test design?", "Dividing input domain into classes of data where all values in a partition are treated equivalently", "Testing only boundary edge values", "Executing all conditional statements", "Splitting tests across multiple developers", "Dividing input domain into classes of data where all values in a partition are treated equivalently", "MEDIUM"));
        list.add(new QuestionItem("What is Boundary Value Analysis (BVA) in software testing?", "Testing values at the boundaries of equivalence partitions (min, just below, on, just above, max)", "Testing random values across the system", "Testing only null pointers", "Testing network bandwidth thresholds", "Testing values at the boundaries of equivalence partitions (min, just below, on, just above, max)", "MEDIUM"));
        list.add(new QuestionItem("In Test-Driven Development (TDD), what is the repeating development cycle known as?", "Red-Green-Refactor", "Build-Measure-Learn", "Design-Code-Debug", "Write-Commit-Deploy", "Red-Green-Refactor", "MEDIUM"));
        list.add(new QuestionItem("What is Technical Debt in software engineering?", "The implied cost of future rework caused by choosing an easy, expedient solution now instead of a better approach", "Financial loans taken to purchase servers", "Unpaid software vendor licenses", "Salary costs of software engineers", "The implied cost of future rework caused by choosing an easy, expedient solution now instead of a better approach", "MEDIUM"));
        list.add(new QuestionItem("What does Mutation Testing evaluate in a software engineering test suite?", "The effectiveness and fault-detecting adequacy of unit test cases by injecting artificial bugs", "Memory leaks in production", "Code compilation speed", "Database transaction speed", "The effectiveness and fault-detecting adequacy of unit test cases by injecting artificial bugs", "MEDIUM"));
        list.add(new QuestionItem("What is the difference between software verification and software validation?", "Verification checks 'Are we building the product right?'; Validation checks 'Are we building the right product?'", "Verification is performed by clients; Validation is performed by developers", "Verification is dynamic testing; Validation is static testing", "Verification is automated; Validation is manual", "Verification checks 'Are we building the product right?'; Validation checks 'Are we building the right product?'", "MEDIUM"));
        list.add(new QuestionItem("Which architectural style separates an application into Presentation, Business Logic, and Data Access layers?", "Microservices Architecture", "Layered (N-Tier) Architecture", "Event-Driven Architecture", "Hexagonal Architecture", "Layered (N-Tier) Architecture", "MEDIUM"));
        list.add(new QuestionItem("What does the Clean Architecture / Hexagonal (Ports and Adapters) pattern enforce regarding dependency directions?", "Dependencies must always point inward toward high-level business domain rules", "Domain entities must depend on database libraries", "UI controllers must call database drivers directly", "Frameworks must wrap around business logic", "Dependencies must always point inward toward high-level business domain rules", "MEDIUM"));
        list.add(new QuestionItem("What is the purpose of Semantic Versioning (SemVer: MAJOR.MINOR.PATCH)?", "MAJOR for breaking API changes, MINOR for backwards-compatible features, PATCH for backwards-compatible bug fixes", "Arbitrary release counter chosen by marketing", "Date of software compilation", "Number of tests passed", "MAJOR for breaking API changes, MINOR for backwards-compatible features, PATCH for backwards-compatible bug fixes", "MEDIUM"));
        list.add(new QuestionItem("What is the role of a Service-Oriented Architecture (SOA) Enterprise Service Bus (ESB)?", "Provides message routing, transformation, and protocol mediation between distributed services", "Acts as an electrical backup for servers", "Replaces web servers", "Compiles code across servers", "Provides message routing, transformation, and protocol mediation between distributed services", "MEDIUM"));
        list.add(new QuestionItem("What is Canary Deployment in software delivery?", "Rolling out changes to a small subset of real users first to verify stability before wider rollout", "Deploying software on a dedicated test server", "Testing software in an offline staging lab", "Instantaneous replacement of all servers", "Rolling out changes to a small subset of real users first to verify stability before wider rollout", "MEDIUM"));
        list.add(new QuestionItem("What is Blue-Green Deployment?", "Running two identical production environments (Blue and Green); one serves live traffic while the other is updated, then traffic switches", "Gradual percentage-based rollout", "Running software in debug mode", "Distributing code to open source community", "Running two identical production environments (Blue and Green); one serves live traffic while the other is updated, then traffic switches", "MEDIUM"));
        list.add(new QuestionItem("What is the Purpose of Feature Toggles (Feature Flags) in continuous delivery?", "Enables modifying system behavior and releasing features in production dynamically without redeploying code", "Prevents hackers from accessing code", "Replaces Git branches entirely", "Compresses HTTP traffic", "Enables modifying system behavior and releasing features in production dynamically without redeploying code", "MEDIUM"));
        list.add(new QuestionItem("What is Pair Programming in Extreme Programming (XP)?", "Two programmers work together at one workstation: the Driver writes code, and the Navigator reviews each line", "Two developers work on separate branches", "One programmer writes tests and the other writes docs", "Developers trade computers every week", "Two programmers work together at one workstation: the Driver writes code, and the Navigator reviews each line", "MEDIUM"));
        list.add(new QuestionItem("In software metrics, what is Function Point Analysis (FPA) used for?", "Estimating the functional size and effort of software based on user requirements independent of technology", "Counting CPU instructions per function", "Measuring function execution time", "Calculating line count of Python scripts", "Estimating the functional size and effort of software based on user requirements independent of technology", "MEDIUM"));
        list.add(new QuestionItem("What is the difference between a stub and a mock in unit testing?", "A stub provides pre-canned answers to calls; a mock also verifies that expected interactions and method calls occurred", "A stub tests the database; a mock tests the UI", "A stub is used in production; a mock is used in staging", "A stub is written in C; a mock is written in Java", "A stub provides pre-canned answers to calls; a mock also verifies that expected interactions and method calls occurred", "MEDIUM"));
        list.add(new QuestionItem("What is the goal of Static Code Analysis tools like SonarQube?", "Analyzes source code without executing it to detect bugs, code smells, vulnerabilities, and duplication", "Runs performance benchmarks on GPU", "Generates UML diagrams from executables", "Automates acceptance tests in browser", "Analyzes source code without executing it to detect bugs, code smells, vulnerabilities, and duplication", "MEDIUM"));

        // 10 HARD
        list.add(new QuestionItem("What is the Strangler Fig pattern in legacy software modernizations?", "Incrementally replacing specific pieces of functionality with new microservices until the legacy system is retired", "Deleting legacy databases directly", "Running legacy code on modern virtual machines", "Rewriting entire monolithic system in a single release", "Incrementally replacing specific pieces of functionality with new microservices until the legacy system is retired", "HARD"));
        list.add(new QuestionItem("In Domain-Driven Design (DDD), what is a Bounded Context?", "An explicit boundary within which a specific domain model and its ubiquitous language apply consistently", "A physical server boundary in a data center", "A Git repository branch boundary", "A database connection pool limit", "An explicit boundary within which a specific domain model and its ubiquitous language apply consistently", "HARD"));
        list.add(new QuestionItem("In Domain-Driven Design, what distinguishes an Entity from a Value Object?", "An Entity has a continuous identity across state changes; a Value Object is defined purely by its attributes and is immutable", "An Entity is stored in a database; a Value Object is not", "An Entity cannot have methods", "A Value Object has a primary key ID", "An Entity has a continuous identity across state changes; a Value Object is defined purely by its attributes and is immutable", "HARD"));
        list.add(new QuestionItem("What does the Saga Pattern solve in distributed microservices architectures without two-phase commit?", "Manages distributed transactions using a sequence of local transactions and compensating transactions on failure", "Encrypts inter-service communication", "Balances HTTP traffic across nodes", "Generates synthetic test data", "Manages distributed transactions using a sequence of local transactions and compensating transactions on failure", "HARD"));
        list.add(new QuestionItem("What is the Outbox Pattern in microservices data architecture?", "Saves domain entity changes and corresponding outgoing integration events atomically in the local database outbox table", "Sends emails to clients asynchronously", "Archives old database records to S3", "Deletes unread notifications", "Saves domain entity changes and corresponding outgoing integration events atomically in the local database outbox table", "HARD"));
        list.add(new QuestionItem("What is Chaos Engineering in software architecture resilience (e.g., Chaos Monkey)?", "The discipline of experimenting on a system in production by deliberately injecting failures to build confidence in resilience", "Writing unformatted spaghetti code", "Allowing random users to push code to main branch", "Deploying untested software on weekends", "The discipline of experimenting on a system in production by deliberately injecting failures to build confidence in resilience", "HARD"));
        list.add(new QuestionItem("In software reliability engineering (SRE), what is an Error Budget?", "The allowable threshold of unreliability (100% - SLO) that product teams can spend on risky releases", "Financial penalty paid to cloud providers for outages", "Budget allocated to hire QA engineers", "Cost of bug bounty payouts", "The allowable threshold of unreliability (100% - SLO) that product teams can spend on risky releases", "HARD"));
        list.add(new QuestionItem("What is the Circuit Breaker pattern and what are its three operating states?", "Prevents cascading failures by halting calls to failing service; Closed (normal), Open (failing/blocked), Half-Open (trial)", "Active, Inactive, Terminated", "Compile, Link, Execute", "Input, Output, Processing", "Prevents cascading failures by halting calls to failing service; Closed (normal), Open (failing/blocked), Half-Open (trial)", "HARD"));
        list.add(new QuestionItem("What is the difference between Event Sourcing and traditional CRUD state persistence?", "Event Sourcing persists the full history of state-changing events as an append-only log rather than current state only", "Event Sourcing only works in memory", "Event Sourcing does not allow queries", "Event Sourcing requires relational SQL tables", "Event Sourcing persists the full history of state-changing events as an append-only log rather than current state only", "HARD"));
        list.add(new QuestionItem("What does CQRS (Command Query Responsibility Segregation) prescribe in enterprise software architecture?", "Separates read (Query) models from write/modification (Command) models to optimize performance and scalability independently", "Combines UI controllers and database queries into one class", "Prohibits SQL queries in distributed systems", "Requires all services to use GraphQL", "Separates read (Query) models from write/modification (Command) models to optimize performance and scalability independently", "HARD"));

        return list;
    }

    public static List<QuestionItem> getOopQuestions() {
        List<QuestionItem> list = new ArrayList<>();
        // 20 EASY
        list.add(new QuestionItem("What are the four fundamental principles of Object-Oriented Programming?", "Encapsulation, Inheritance, Polymorphism, Abstraction", "Compilation, Interpretation, Linking, Loading", "Classes, Objects, Methods, Variables", "Stack, Heap, Queue, Tree", "Encapsulation, Inheritance, Polymorphism, Abstraction", "EASY"));
        list.add(new QuestionItem("What is an Object in Object-Oriented Programming?", "An instance of a class containing state and behavior", "A primitive data type", "A compiler directive", "A database table definition", "An instance of a class containing state and behavior", "EASY"));
        list.add(new QuestionItem("What is a Class in Object-Oriented Programming?", "A blueprint or template for creating objects", "An individual runtime instance", "A memory pointer", "A hardware component", "A blueprint or template for creating objects", "EASY"));
        list.add(new QuestionItem("Which OOP concept bundles data (attributes) and methods that operate on that data into a single unit while restricting direct outside access?", "Inheritance", "Polymorphism", "Encapsulation", "Association", "Encapsulation", "EASY"));
        list.add(new QuestionItem("Which OOP concept allows a new class to acquire properties and methods of an existing class?", "Encapsulation", "Inheritance", "Abstraction", "Overloading", "Inheritance", "EASY"));
        list.add(new QuestionItem("What is Polymorphism in Object-Oriented Programming?", "The ability of a message or method call to be processed in different ways depending on object type", "Hiding memory addresses from users", "Creating multiple copies of a class", "Compiling code to different platforms", "The ability of a message or method call to be processed in different ways depending on object type", "EASY"));
        list.add(new QuestionItem("What is Abstraction in OOP?", "Displaying only essential features and hiding complex implementation details", "Creating private variables only", "Making all methods static", "Preventing subclasses from overriding methods", "Displaying only essential features and hiding complex implementation details", "EASY"));
        list.add(new QuestionItem("What is Method Overloading?", "Multiple methods in the same class with identical name but different parameter lists", "Redefining a superclass method in a subclass", "Making a method run in multiple threads", "Overloading CPU execution cache", "Multiple methods in the same class with identical name but different parameter lists", "EASY"));
        list.add(new QuestionItem("What is Method Overriding?", "A subclass providing a specific implementation of a method already defined in its superclass", "Calling a method multiple times in a loop", "Passing wrong data types to a method", "Renaming a private method", "A subclass providing a specific implementation of a method already defined in its superclass", "EASY"));
        list.add(new QuestionItem("What special method is automatically invoked when an object is instantiated?", "Destructor", "Constructor", "Finalizer", "Initializer", "Constructor", "EASY"));
        list.add(new QuestionItem("Can an abstract class be directly instantiated with the 'new' operator?", "Yes, always", "No, never", "Only if it has no abstract methods", "Only inside a static block", "No, never", "EASY"));
        list.add(new QuestionItem("What is a destructor in languages like C++?", "A special method invoked automatically when an object's lifetime ends to release resources", "A method that deletes files from disk", "A syntax error detector", "A compiler optimization phase", "A special method invoked automatically when an object's lifetime ends to release resources", "EASY"));
        list.add(new QuestionItem("What relationship does inheritance represent between classes?", "'has-a' relationship", "'is-a' relationship", "'uses-a' relationship", "'belongs-to' relationship", "'is-a' relationship", "EASY"));
        list.add(new QuestionItem("What relationship does composition represent between classes?", "'is-a' relationship", "'has-a' (part-of) relationship", "'inherits-from' relationship", "'implements' relationship", "'has-a' (part-of) relationship", "EASY"));
        list.add(new QuestionItem("What is the default access modifier in Java when no modifier is specified (package-private)?", "Accessible to any class in any package", "Accessible only to classes within the same package", "Accessible only to subclasses in other packages", "Accessible only within the same class", "Accessible only to classes within the same package", "EASY"));
        list.add(new QuestionItem("What keyword in C++ and Java refers to the current object instance?", "super", "this", "self", "base", "this", "EASY"));
        list.add(new QuestionItem("What design principle states that 'Favor object composition over class inheritance'?", "Encapsulation", "Composition over Inheritance", "Multiple Inheritance", "Open-Closed Principle", "Composition over Inheritance", "EASY"));
        list.add(new QuestionItem("What is the Diamond Problem in object-oriented programming?", "Ambiguity arising when a class inherits from two classes that both inherit from a common ancestor", "Memory leak in heap", "Stack overflow in recursion", "Syntax error in constructor", "Ambiguity arising when a class inherits from two classes that both inherit from a common ancestor", "EASY"));
        list.add(new QuestionItem("How does Java resolve the Diamond Problem regarding multiple inheritance of state?", "Allows multiple class inheritance with virtual base classes", "Disallows multiple inheritance of classes (only permits implementing multiple interfaces)", "Throws runtime exception", "Selects the first class in alphabet", "Disallows multiple inheritance of classes (only permits implementing multiple interfaces)", "EASY"));
        list.add(new QuestionItem("What is a pure virtual function in C++?", "A virtual function declared with '= 0' that has no implementation in the base class", "A function that has no parameters", "A static member function", "A template function", "A virtual function declared with '= 0' that has no implementation in the base class", "EASY"));

        // 20 MEDIUM
        list.add(new QuestionItem("What are the five SOLID principles of object-oriented design?", "Single Responsibility, Open/Closed, Liskov Substitution, Interface Segregation, Dependency Inversion", "Simple, Organized, Linear, Iterative, Dynamic", "State, Object, Logic, Instance, Design", "Security, Optimization, Logging, Integration, Deployment", "Single Responsibility, Open/Closed, Liskov Substitution, Interface Segregation, Dependency Inversion", "MEDIUM"));
        list.add(new QuestionItem("What does the Single Responsibility Principle (SRP) state?", "A class should have one, and only one, reason to change", "A method must not exceed 20 lines of code", "A class should only contain private methods", "An application should have only one class", "A class should have one, and only one, reason to change", "MEDIUM"));
        list.add(new QuestionItem("What does the Open/Closed Principle (OCP) require of software entities?", "Classes should be open for extension, but closed for modification", "Files must be open for reading, but closed for writing", "Methods should be open to all packages", "Network sockets must remain open", "Classes should be open for extension, but closed for modification", "MEDIUM"));
        list.add(new QuestionItem("What does the Liskov Substitution Principle (LSP) state?", "Subtypes must be substitutable for their base types without altering program correctness", "Classes must substitute composition for inheritance", "Constructors must not be overridden", "All objects must implement Serializable", "Subtypes must be substitutable for their base types without altering program correctness", "MEDIUM"));
        list.add(new QuestionItem("What does the Interface Segregation Principle (ISP) state?", "Clients should not be forced to depend upon interfaces that they do not use", "Every class must have its own interface", "Interfaces must inherit from Object", "Interfaces can only contain static methods", "Clients should not be forced to depend upon interfaces that they do not use", "MEDIUM"));
        list.add(new QuestionItem("What does the Dependency Inversion Principle (DIP) state?", "High-level modules should not depend on low-level modules; both should depend on abstractions", "Classes must invert their inheritance tree", "Database calls must be written before business logic", "Subclasses must precede superclasses in source code", "High-level modules should not depend on low-level modules; both should depend on abstractions", "MEDIUM"));
        list.add(new QuestionItem("Which Creational Design Pattern ensures that a class has only one instance and provides global access to it?", "Factory Method", "Singleton Pattern", "Builder Pattern", "Prototype Pattern", "Singleton Pattern", "MEDIUM"));
        list.add(new QuestionItem("Which Structural Design Pattern allows incompatible interfaces to work together by acting as a bridge/wrapper?", "Decorator Pattern", "Adapter Pattern", "Proxy Pattern", "Facade Pattern", "Adapter Pattern", "MEDIUM"));
        list.add(new QuestionItem("Which Behavioral Design Pattern defines a one-to-many dependency between objects so that when one changes state, all dependents are notified?", "Strategy Pattern", "Observer Pattern", "Command Pattern", "Iterator Pattern", "Observer Pattern", "MEDIUM"));
        list.add(new QuestionItem("Which Structural Design Pattern dynamically attaches additional responsibilities or behaviors to an object without altering its structure?", "Decorator Pattern", "Composite Pattern", "Flyweight Pattern", "Bridge Pattern", "Decorator Pattern", "MEDIUM"));
        list.add(new QuestionItem("Which Creational Design Pattern separates the construction of a complex object from its representation, allowing the same process to create various representations?", "Builder Pattern", "Abstract Factory", "Singleton", "Factory Method", "Builder Pattern", "MEDIUM"));
        list.add(new QuestionItem("What is the difference between Aggregation and Composition in object modeling?", "Composition implies strong ownership where parts cannot exist without the whole; Aggregation implies weak ownership where parts can exist independently", "Aggregation is 'is-a'; Composition is 'has-a'", "Composition cannot use pointers", "Aggregation is only supported in C++", "Composition implies strong ownership where parts cannot exist without the whole; Aggregation implies weak ownership where parts can exist independently", "MEDIUM"));
        list.add(new QuestionItem("What is the purpose of the vtable (virtual method table) in C++ / OOP implementations?", "Enables dynamic dispatch (runtime polymorphism) by storing pointers to virtual functions", "Stores static variable values", "Manages garbage collection", "Speeds up compile-time template instantiation", "Enables dynamic dispatch (runtime polymorphism) by storing pointers to virtual functions", "MEDIUM"));
        list.add(new QuestionItem("What is Covariant Return Type in method overriding?", "An overriding method in a subclass can return a subtype of the return type declared in the superclass method", "Return types must match primitive types exactly", "Return types are converted to void", "Return types must be generic", "An overriding method in a subclass can return a subtype of the return type declared in the superclass method", "MEDIUM"));
        list.add(new QuestionItem("Which Behavioral Design Pattern encapsulates an algorithm inside a class, making algorithms interchangeable at runtime?", "Template Method", "Strategy Pattern", "State Pattern", "Visitor Pattern", "Strategy Pattern", "MEDIUM"));
        list.add(new QuestionItem("What is the difference between Strategy Pattern and State Pattern?", "Strategy configures an object with an algorithm; State allows an object to alter its behavior when its internal state changes", "Strategy uses inheritance; State uses composition", "State is a creational pattern; Strategy is behavioral", "Strategy only works with singletons", "Strategy configures an object with an algorithm; State allows an object to alter its behavior when its internal state changes", "MEDIUM"));
        list.add(new QuestionItem("What is the Law of Demeter (Principle of Least Knowledge)?", "An object should only communicate with its immediate neighbors and not talk to strangers (avoid a.getB().getC().doD())", "Classes must have at most 3 methods", "Database tables must not have foreign keys", "Modules should not use third-party libraries", "An object should only communicate with its immediate neighbors and not talk to strangers (avoid a.getB().getC().doD())", "MEDIUM"));
        list.add(new QuestionItem("What is the difference between Early Binding (Static Binding) and Late Binding (Dynamic Binding)?", "Early binding resolves method calls at compile time; late binding resolves method calls at runtime based on actual object type", "Early binding is slower than late binding", "Late binding cannot be used with objects", "Early binding requires virtual functions", "Early binding resolves method calls at compile time; late binding resolves method calls at runtime based on actual object type", "MEDIUM"));
        list.add(new QuestionItem("Which Creational Design Pattern creates families of related or dependent objects without specifying their concrete classes?", "Abstract Factory Pattern", "Factory Method", "Builder Pattern", "Prototype", "Abstract Factory Pattern", "MEDIUM"));
        list.add(new QuestionItem("What is the purpose of the Proxy Design Pattern?", "Provides a surrogate or placeholder for another object to control access, perform lazy loading, or add logging/security", "Converts interface types", "Duplicates objects in memory", "Serializes objects to JSON", "Provides a surrogate or placeholder for another object to control access, perform lazy loading, or add logging/security", "MEDIUM"));

        // 10 HARD
        list.add(new QuestionItem("What is the Double-Checked Locking pattern in Singleton implementation and why is the 'volatile' keyword required in Java?", "Volatile prevents instruction reordering by compiler and CPU during object allocation before instance pointer is assigned", "Volatile locks the entire classloader", "Volatile speeds up CPU cache synchronization", "Volatile prevents garbage collection of the singleton", "Volatile prevents instruction reordering by compiler and CPU during object allocation before instance pointer is assigned", "HARD"));
        list.add(new QuestionItem("How does the Visitor Design Pattern achieve double dispatch in languages that only support single dispatch?", "The element accepts a visitor, and inside accept(), calls the visitor's visit() method passing 'this'", "Uses reflection at runtime", "Generates dynamic proxy classes", "Overrides the JVM bytecode verifier", "The element accepts a visitor, and inside accept(), calls the visitor's visit() method passing 'this'", "HARD"));
        list.add(new QuestionItem("What is the Liskov Substitution Principle violation in the classic Square inherits from Rectangle dilemma?", "Square alters Rectangle's invariant that width and height can vary independently; setting width modifies height", "Square has four sides instead of two", "Square cannot compute its area", "Rectangle is not a geometric shape", "Square alters Rectangle's invariant that width and height can vary independently; setting width modifies height", "HARD"));
        list.add(new QuestionItem("What problem does the Flyweight Design Pattern solve in graphics and game engines?", "Minimizes memory usage by sharing common intrinsic state across a large number of fine-grained objects", "Speeds up disk file loading", "Prevents memory fragmentation in heap", "Calculates lighting in parallel on GPU", "Minimizes memory usage by sharing common intrinsic state across a large number of fine-grained objects", "HARD"));
        list.add(new QuestionItem("In C++, how does virtual inheritance solve the Diamond Problem?", "Ensures that only one shared sub-object of the base class exists in the derived class hierarchy", "Deletes all virtual functions", "Prevents calling base class constructors", "Converts derived classes into friend classes", "Ensures that only one shared sub-object of the base class exists in the derived class hierarchy", "HARD"));
        list.add(new QuestionItem("What is the Memento Design Pattern used for?", "Captures and externalizes an object's internal state so it can be restored later without violating encapsulation (Undo mechanism)", "Caches database query results", "Records method execution times", "Creates immutable object copies", "Captures and externalizes an object's internal state so it can be restored later without violating encapsulation (Undo mechanism)", "HARD"));
        list.add(new QuestionItem("What is the difference between the Bridge Pattern and the Adapter Pattern?", "Bridge decouples an abstraction from its implementation upfront so both can vary; Adapter fixes interface mismatches between existing classes after the fact", "Bridge is behavioral; Adapter is creational", "Adapter requires multiple inheritance; Bridge does not", "Bridge only works with UI components", "Bridge decouples an abstraction from its implementation upfront so both can vary; Adapter fixes interface mismatches between existing classes after the fact", "HARD"));
        list.add(new QuestionItem("What is Monostate (Borg) Pattern and how does it differ from Singleton?", "Multiple instances can be created, but all instances share the same underlying static state", "Only one instance can ever exist in memory", "Instances are destroyed after one method call", "State is stored in a relational database", "Multiple instances can be created, but all instances share the same underlying static state", "HARD"));
        list.add(new QuestionItem("How does Inversion of Control (IoC) with Dependency Injection (DI) improve software testability?", "Allows injecting mock or stub implementations of interfaces during unit testing instead of hard-coded concrete dependencies", "Eliminates need for writing test cases", "Executes unit tests in parallel", "Compiles source code faster", "Allows injecting mock or stub implementations of interfaces during unit testing instead of hard-coded concrete dependencies", "HARD"));
        list.add(new QuestionItem("What is the Null Object Pattern and what benefit does it provide in clean OOP code?", "Provides an object that implements an interface with default neutral behavior to eliminate repetitive null-checks", "Throws NullPointerException explicitly", "Deletes unreferenced objects from heap", "Returns null from all methods", "Provides an object that implements an interface with default neutral behavior to eliminate repetitive null-checks", "HARD"));

        return list;
    }

    public static List<QuestionItem> getComputerArchitectureQuestions() {
        List<QuestionItem> list = new ArrayList<>();
        // 20 EASY
        list.add(new QuestionItem("What does CPU stand for in computer systems?", "Central Processing Unit", "Control Program Utility", "Core Processor Unit", "Compute Power Unit", "Central Processing Unit", "EASY"));
        list.add(new QuestionItem("What are the primary functional components of the Von Neumann architecture?", "CPU (ALU + Control Unit), Memory, and Input/Output mechanisms", "Motherboard, GPU, Keyboard, Monitor", "Compiler, Assembler, Linker, Loader", "Cache, RAM, ROM, SSD", "CPU (ALU + Control Unit), Memory, and Input/Output mechanisms", "EASY"));
        list.add(new QuestionItem("What component inside the CPU performs arithmetic and logical operations?", "Control Unit (CU)", "Arithmetic Logic Unit (ALU)", "Program Counter (PC)", "Instruction Register (IR)", "Arithmetic Logic Unit (ALU)", "EASY"));
        list.add(new QuestionItem("What is the primary function of the Program Counter (PC) register?", "Holds the memory address of the next instruction to be fetched and executed", "Stores calculation results", "Counts clock cycles", "Tracks memory errors", "Holds the memory address of the next instruction to be fetched and executed", "EASY"));
        list.add(new QuestionItem("What is the fastest memory type in the computer memory hierarchy?", "Main Memory (DRAM)", "SRAM Cache", "CPU Registers", "SSD NVMe", "CPU Registers", "EASY"));
        list.add(new QuestionItem("What does the basic instruction cycle consist of?", "Fetch, Decode, Execute", "Compile, Link, Run", "Input, Output, Store", "Read, Write, Clear", "Fetch, Decode, Execute", "EASY"));
        list.add(new QuestionItem("What type of memory loses its stored contents when power is turned off?", "ROM", "Volatile Memory (e.g. RAM)", "Flash Memory", "Magnetic Disk", "Volatile Memory (e.g. RAM)", "EASY"));
        list.add(new QuestionItem("What is the difference between RISC and CISC processor architectures?", "RISC uses a small set of simple, single-cycle instructions; CISC has a large set of complex, multi-cycle instructions", "RISC has no registers; CISC has many registers", "RISC is 64-bit; CISC is 32-bit", "RISC cannot run operating systems", "RISC uses a small set of simple, single-cycle instructions; CISC has a large set of complex, multi-cycle instructions", "EASY"));
        list.add(new QuestionItem("Which register holds the instruction currently being executed by the processor?", "Program Counter (PC)", "Instruction Register (IR)", "Memory Address Register (MAR)", "Memory Buffer Register (MBR)", "Instruction Register (IR)", "EASY"));
        list.add(new QuestionItem("What is the width of the data bus related to in computer architecture?", "The number of bits that can be transferred simultaneously between components", "The total size of physical RAM", "The clock speed in Gigahertz", "The number of CPU cores", "The number of bits that can be transferred simultaneously between components", "EASY"));
        list.add(new QuestionItem("What does the clock speed of a microprocessor measure?", "Number of clock cycles executed per second (Hertz)", "Power consumption in Watts", "Memory storage capacity", "Network transmission bandwidth", "Number of clock cycles executed per second (Hertz)", "EASY"));
        list.add(new QuestionItem("What is a byte in terms of bits?", "4 bits", "8 bits", "16 bits", "32 bits", "8 bits", "EASY"));
        list.add(new QuestionItem("What number representation uses sign bit and inversion plus 1 to represent negative numbers in computers?", "Sign-Magnitude", "One's Complement", "Two's Complement", "Excess-3 code", "Two's Complement", "EASY"));
        list.add(new QuestionItem("What is the primary benefit of instruction pipelining in modern microprocessors?", "Increases instruction throughput by overlapping execution of multiple instructions", "Reduces CPU clock speed", "Eliminates need for ALU", "Eliminates program memory", "Increases instruction throughput by overlapping execution of multiple instructions", "EASY"));
        list.add(new QuestionItem("Which cache level is typically located closest to the CPU core and has the lowest latency?", "L1 Cache", "L2 Cache", "L3 Cache", "Disk Cache", "L1 Cache", "EASY"));
        list.add(new QuestionItem("What is a bus in computer architecture?", "A communication system that transfers data between components inside a computer or between computers", "An optical drive", "A power supply line", "A cooling fan mechanism", "A communication system that transfers data between components inside a computer or between computers", "EASY"));
        list.add(new QuestionItem("What does Moore's Law historically observe?", "The number of transistors on a microchip doubles roughly every two years", "Internet bandwidth triples every year", "Software size shrinks by half every decade", "CPU power consumption drops to zero", "The number of transistors on a microchip doubles roughly every two years", "EASY"));
        list.add(new QuestionItem("What register holds the address in memory that is currently being read from or written to?", "Memory Address Register (MAR)", "Instruction Register (IR)", "Program Counter (PC)", "Accumulator (ACC)", "Memory Address Register (MAR)", "EASY"));
        list.add(new QuestionItem("What is Little-Endian byte ordering?", "The least significant byte (LSB) is stored at the lowest memory address", "The most significant byte is stored first", "Bytes are stored randomly", "Bytes are encrypted on write", "The least significant byte (LSB) is stored at the lowest memory address", "EASY"));
        list.add(new QuestionItem("What component manages and coordinates all operations inside the CPU by generating timing and control signals?", "Control Unit", "ALU", "Cache Controller", "Floating Point Unit", "Control Unit", "EASY"));

        // 20 MEDIUM
        list.add(new QuestionItem("What are the three major classes of pipeline hazards that cause pipeline stalls?", "Structural Hazards, Data Hazards, and Control (Branch) Hazards", "Arithmetic Hazards, Memory Hazards, Disk Hazards", "Read Hazards, Write Hazards, Update Hazards", "Cache Hazards, Page Hazards, TLB Hazards", "Structural Hazards, Data Hazards, and Control (Branch) Hazards", "MEDIUM"));
        list.add(new QuestionItem("What is a Read-After-Write (RAW) data hazard in a pipelined processor?", "An instruction tries to read a source register before a preceding instruction has finished writing to it", "An instruction writes before reading", "Two instructions write to the same register simultaneously", "Memory read causes page fault", "An instruction tries to read a source register before a preceding instruction has finished writing to it", "MEDIUM"));
        list.add(new QuestionItem("What hardware technique resolves data hazards without stalling by routing the ALU result directly to the inputs of dependent instructions?", "Data Forwarding (Bypassing)", "Branch Prediction", "Out-of-Order Execution", "Speculative Execution", "Data Forwarding (Bypassing)", "MEDIUM"));
        list.add(new QuestionItem("What are the three C's of cache misses formulated by Mark Hill?", "Compulsory (Cold), Capacity, and Conflict misses", "Coherent, Concurrent, and Cyclic misses", "Critical, Constant, and Clock misses", "Core, Chip, and Circuit misses", "Compulsory (Cold), Capacity, and Conflict misses", "MEDIUM"));
        list.add(new QuestionItem("What is a direct-mapped cache compared to an n-way set-associative cache?", "Each memory block maps to exactly one cache line; in n-way, block can map to any of n lines in a set", "Direct-mapped has no cache lines", "Direct-mapped is fully associative", "Direct-mapped only stores instructions", "Each memory block maps to exactly one cache line; in n-way, block can map to any of n lines in a set", "MEDIUM"));
        list.add(new QuestionItem("In cache memory write policies, what is the difference between Write-Through and Write-Back?", "Write-Through updates memory immediately on write; Write-Back updates cache and writes to memory only when block is evicted", "Write-Through is faster than Write-Back", "Write-Back writes to disk directly", "Write-Through does not use cache", "Write-Through updates memory immediately on write; Write-Back updates cache and writes to memory only when block is evicted", "MEDIUM"));
        list.add(new QuestionItem("What does the Principle of Locality state regarding computer memory access patterns?", "Programs tend to reuse data and instructions they have used recently (temporal) or nearby (spatial)", "Data must always be stored in alphabetical order", "CPU instructions execute in random memory regions", "Memory addresses are evenly distributed across chips", "Programs tend to reuse data and instructions they have used recently (temporal) or nearby (spatial)", "MEDIUM"));
        list.add(new QuestionItem("What is Amdahl's Law used to calculate?", "The theoretical speedup of a program when using multiple processors, limited by its serial fraction", "The maximum power dissipation of a chip", "The latency of DRAM memory access", "The bandwidth of PCI Express lanes", "The theoretical speedup of a program when using multiple processors, limited by its serial fraction", "MEDIUM"));
        list.add(new QuestionItem("What is SIMD (Single Instruction, Multiple Data) processing (e.g., AVX, NEON)?", "Executing a single instruction simultaneously on multiple data elements in vector registers", "Running one instruction on multiple computers", "Using single-core CPUs", "Pipelining independent instructions", "Executing a single instruction simultaneously on multiple data elements in vector registers", "MEDIUM"));
        list.add(new QuestionItem("What is superscalar execution in modern microprocessors?", "The ability to fetch, decode, and execute multiple instructions concurrently per clock cycle using multiple execution units", "Running clock speeds above 5 GHz", "Using multiple physical motherboards", "Executing instructions exclusively in software", "The ability to fetch, decode, and execute multiple instructions concurrently per clock cycle using multiple execution units", "MEDIUM"));
        list.add(new QuestionItem("What does a Branch Target Buffer (BTB) store to speed up conditional branch handling?", "The predicted target address of branch instructions to allow fetching target before branch is decoded", "Previous calculation results", "Stack return addresses", "Interrupt vector tables", "The predicted target address of branch instructions to allow fetching target before branch is decoded", "MEDIUM"));
        list.add(new QuestionItem("What is the difference between static branch prediction and dynamic branch prediction?", "Static uses compile-time heuristics (e.g., backward branches taken); dynamic tracks runtime execution history in hardware tables", "Static prediction is 100% accurate", "Dynamic prediction is done by software compiler", "Static prediction requires hardware history registers", "Static uses compile-time heuristics (e.g., backward branches taken); dynamic tracks runtime execution history in hardware tables", "MEDIUM"));
        list.add(new QuestionItem("What is the purpose of the Tomasulo algorithm in out-of-order processors?", "Enables dynamic instruction scheduling and register renaming using reservation stations to resolve WAR and WAW hazards", "Controls cooling fan speeds", "Compiles binary instructions to microcode", "Encrypts memory bus traffic", "Enables dynamic instruction scheduling and register renaming using reservation stations to resolve WAR and WAW hazards", "MEDIUM"));
        list.add(new QuestionItem("What is the difference between Write-After-Read (WAR) anti-dependence and Write-After-Write (WAW) output dependence?", "WAR: later instruction writes to register before earlier reads it; WAW: later instruction writes before earlier writes to same register", "WAR is a true data dependence; WAW is not", "WAW can only occur in in-order pipelines", "WAR causes structural hazards", "WAR: later instruction writes to register before earlier reads it; WAW: later instruction writes before earlier writes to same register", "MEDIUM"));
        list.add(new QuestionItem("What hardware buffer ensures that out-of-order instructions commit their architectural state in original program order?", "Reorder Buffer (ROB)", "Translation Lookaside Buffer (TLB)", "Instruction Cache", "Branch History Table", "Reorder Buffer (ROB)", "MEDIUM"));
        list.add(new QuestionItem("What cache coherency protocol uses states Modified, Exclusive, Shared, and Invalid?", "MESI Protocol", "LRU Protocol", "Snooping Protocol", "Directory Protocol", "MESI Protocol", "MEDIUM"));
        list.add(new QuestionItem("What is the difference between Snooping-based and Directory-based cache coherence protocols?", "Snooping broadcasts changes on a shared bus; Directory maintains a centralized or distributed directory of cached blocks", "Snooping is for thousands of cores; Directory is for small systems", "Directory protocol does not support multi-core", "Snooping disables L2 cache", "Snooping broadcasts changes on a shared bus; Directory maintains a centralized or distributed directory of cached blocks", "MEDIUM"));
        list.add(new QuestionItem("What is DMA (Direct Memory Access) and how does it prevent CPU stalling during large disk or network I/O?", "DMA controller transfers data blocks directly between I/O device and main memory, interrupting CPU only when complete", "DMA speeds up CPU clock cycles", "DMA compresses disk data in real time", "DMA replaces RAM with high-speed registers", "DMA controller transfers data blocks directly between I/O device and main memory, interrupting CPU only when complete", "MEDIUM"));
        list.add(new QuestionItem("What is simultaneous multithreading (SMT, e.g., Intel Hyper-Threading)?", "Allowing multiple hardware threads to issue instructions simultaneously to execution units of a single physical core", "Connecting two CPUs with a cable", "Running multiple operating systems concurrently", "Dividing CPU clock speed in half", "Allowing multiple hardware threads to issue instructions simultaneously to execution units of a single physical core", "MEDIUM"));
        list.add(new QuestionItem("What is Memory-Mapped I/O (MMIO)?", "Mapping device control and data registers into the same address space as physical memory, using standard load/store instructions", "Mapping virtual memory to SSD", "Storing RAM contents on hard disk", "Using special IN and OUT instructions only", "Mapping device control and data registers into the same address space as physical memory, using standard load/store instructions", "MEDIUM"));

        // 10 HARD
        list.add(new QuestionItem("What is the Spectre hardware vulnerability and how does it leak data from speculative execution?", "Uses speculative execution across mispredicted branches to transiently access secrets and leak them via microarchitectural cache side-channels", "Buffer overflow in microcode", "Hardware fault in ALU multiplier", "Electromagnetic radiation emission from DRAM", "Uses speculative execution across mispredicted branches to transiently access secrets and leak them via microarchitectural cache side-channels", "HARD"));
        list.add(new QuestionItem("In the MOESI cache coherence protocol, what does the Owner (O) state indicate?", "The cache line is dirty and shared with other cores; the owner is responsible for updating memory upon eviction", "The cache line is read-only", "The CPU owns the system bus exclusively", "The cache line is invalid and waiting for flush", "The cache line is dirty and shared with other cores; the owner is responsible for updating memory upon eviction", "HARD"));
        list.add(new QuestionItem("What is False Sharing in multi-core symmetric multiprocessing systems?", "Threads on different cores modify independent variables that reside in the same shared cache line, causing ping-pong invalidations", "Two processes share the same virtual address space", "A core reads stale data from disk", "Virtual memory pages are incorrectly mapped", "Threads on different cores modify independent variables that reside in the same shared cache line, causing ping-pong invalidations", "HARD"));
        list.add(new QuestionItem("What is the purpose of Register Renaming in out-of-order execution microarchitectures?", "Eliminates false name dependencies (WAR and WAW hazards) by mapping architectural registers to a larger pool of physical registers", "Changes variable names in source code", "Reduces compiler optimization time", "Converts 32-bit registers to 64-bit", "Eliminates false name dependencies (WAR and WAW hazards) by mapping architectural registers to a larger pool of physical registers", "HARD"));
        list.add(new QuestionItem("How does the TAGE (TAgged GEometric history length) branch predictor achieve state-of-the-art prediction accuracy?", "Uses multiple tagged predictor tables indexed with geometric history lengths to capture both short and long correlation patterns", "Uses genetic algorithms on GPU", "Executes all branches concurrently", "Reads future instructions from SSD", "Uses multiple tagged predictor tables indexed with geometric history lengths to capture both short and long correlation patterns", "HARD"));
        list.add(new QuestionItem("What is the memory consistency model known as Total Store Order (TSO) supported by x86-64?", "Writes by a core are seen in order; stores can be buffered before loads, allowing Store-Load reordering but preserving other orders", "All loads and stores can be executed in completely random order", "Stores are delayed until program completion", "Only one thread can access memory at a time", "Writes by a core are seen in order; stores can be buffered before loads, allowing Store-Load reordering but preserving other orders", "HARD"));
        list.add(new QuestionItem("What is the Rowhammer vulnerability in DRAM chips?", "Repeatedly accessing (hammering) a memory row causes electrical disturbance that flips bits in adjacent unaccessed rows", "Cracking the silicon die with physical shock", "Overclocking RAM until it overheats", "Corrupting BIOS firmware via USB", "Repeatedly accessing (hammering) a memory row causes electrical disturbance that flips bits in adjacent unaccessed rows", "HARD"));
        list.add(new QuestionItem("What is the function of the Translation Lookaside Buffer (TLB) Page Fault Handler when a hardware-managed TLB experiences a miss?", "Hardware Page Table Walker traverses multi-level page tables in memory to load the missing PTE into TLB", "OS kernel terminates process", "CPU shuts down execution pipeline", "RAM controller reboots", "Hardware Page Table Walker traverses multi-level page tables in memory to load the missing PTE into TLB", "HARD"));
        list.add(new QuestionItem("What architectural difference distinguishes VLIW (Very Long Instruction Word) from Superscalar processors?", "VLIW relies on compiler to statically schedule and bundle independent operations into one wide word; Superscalar uses hardware logic", "VLIW has no registers", "VLIW can only execute arithmetic operations", "Superscalar cannot run C code", "VLIW relies on compiler to statically schedule and bundle independent operations into one wide word; Superscalar uses hardware logic", "HARD"));
        list.add(new QuestionItem("What is Non-Uniform Memory Access (NUMA) interconnect topology and what is the NUMA factor?", "Multi-socket systems where access time depends on memory location relative to CPU; NUMA factor is ratio of remote to local access latency", "A bus connecting GPU directly to monitor", "A cache replacement algorithm", "A compiler flag for multi-threading", "Multi-socket systems where access time depends on memory location relative to CPU; NUMA factor is ratio of remote to local access latency", "HARD"));

        return list;
    }

    public static List<QuestionItem> getWebTechnologiesQuestions() {
        List<QuestionItem> list = new ArrayList<>();
        // 20 EASY
        list.add(new QuestionItem("What does HTML stand for in web development?", "HyperText Markup Language", "Hyperlink Text Management Language", "Home Tool Markup Language", "Hyper Transfer Mode Language", "HyperText Markup Language", "EASY"));
        list.add(new QuestionItem("What does CSS stand for?", "Cascading Style Sheets", "Computer Style Sheets", "Creative Style System", "Colorful Style Sheets", "Cascading Style Sheets", "EASY"));
        list.add(new QuestionItem("Which HTML element is used to define an internal stylesheet?", "<style>", "<css>", "<script>", "<link>", "<style>", "EASY"));
        list.add(new QuestionItem("Which HTML tag is used to create a hyperlink to another web page?", "<a>", "<link>", "<href>", "<nav>", "<a>", "EASY"));
        list.add(new QuestionItem("Which JavaScript keyword is used to declare a block-scoped variable that can be reassigned?", "let", "const", "var", "static", "let", "EASY"));
        list.add(new QuestionItem("Which JavaScript keyword declares a block-scoped constant that cannot be reassigned?", "const", "let", "var", "immutable", "const", "EASY"));
        list.add(new QuestionItem("What does the DOM stand for in client-side web technologies?", "Document Object Model", "Data Object Management", "Digital Ordinance Model", "Document Operating Method", "Document Object Model", "EASY"));
        list.add(new QuestionItem("Which HTTP request method is typically used to request data from a specified resource without side effects?", "POST", "GET", "PUT", "DELETE", "GET", "EASY"));
        list.add(new QuestionItem("Which HTTP method is used to send data to a server to create a resource?", "GET", "POST", "HEAD", "OPTIONS", "POST", "EASY"));
        list.add(new QuestionItem("What HTTP status code indicates a successful request?", "200 OK", "404 Not Found", "500 Internal Server Error", "301 Moved Permanently", "200 OK", "EASY"));
        list.add(new QuestionItem("What HTTP status code indicates that the requested resource could not be found?", "404 Not Found", "403 Forbidden", "502 Bad Gateway", "200 OK", "404 Not Found", "EASY"));
        list.add(new QuestionItem("What HTTP status code indicates an internal server error?", "500 Internal Server Error", "400 Bad Request", "401 Unauthorized", "503 Service Unavailable", "500 Internal Server Error", "EASY"));
        list.add(new QuestionItem("What does JSON stand for in web data exchange?", "JavaScript Object Notation", "Java System Oriented Network", "JavaScript Online Node", "Java Standard Object Network", "JavaScript Object Notation", "EASY"));
        list.add(new QuestionItem("Which CSS property is used to change the background color of an element?", "color", "background-color", "bgcolor", "fill-color", "background-color", "EASY"));
        list.add(new QuestionItem("Which CSS layout model provides efficient alignment and space distribution among items in a one-dimensional container?", "Flexbox", "Grid", "Float", "Position", "Flexbox", "EASY"));
        list.add(new QuestionItem("Which CSS layout module introduces a two-dimensional grid-based layout system for web design?", "CSS Grid", "Flexbox", "Tables", "Inline-Block", "CSS Grid", "EASY"));
        list.add(new QuestionItem("Which HTML5 semantic tag represents self-contained content such as a blog post or news story?", "<article>", "<section>", "<div>", "<aside>", "<article>", "EASY"));
        list.add(new QuestionItem("What function is used in modern JavaScript to make asynchronous HTTP requests returning a Promise?", "fetch()", "ajax()", "get()", "http()", "fetch()", "EASY"));
        list.add(new QuestionItem("Where is data stored via window.localStorage in the web browser?", "Persisted in browser storage across sessions without expiration date", "Cleared when browser tab is closed", "Stored on the web server", "Stored in session cookies only", "Persisted in browser storage across sessions without expiration date", "EASY"));
        list.add(new QuestionItem("What is the main difference between localStorage and sessionStorage?", "sessionStorage data is cleared when the page session/tab ends; localStorage persists indefinitely", "localStorage is encrypted; sessionStorage is not", "sessionStorage can only hold 1 KB", "localStorage is sent to server on every request", "sessionStorage data is cleared when the page session/tab ends; localStorage persists indefinitely", "EASY"));

        // 20 MEDIUM
        list.add(new QuestionItem("What is the Same-Origin Policy (SOP) enforced by web browsers?", "Restricts scripts running on one origin from accessing resources or DOM on another origin", "Forces all sites to use HTTPS", "Requires websites to use same domain registrar", "Disables cookie storage", "Restricts scripts running on one origin from accessing resources or DOM on another origin", "MEDIUM"));
        list.add(new QuestionItem("What mechanism allows servers to specify which remote origins are permitted to access their resources (relaxing SOP)?", "Cross-Origin Resource Sharing (CORS)", "Content Security Policy (CSP)", "Cross-Site Scripting (XSS)", "Cross-Site Request Forgery (CSRF)", "Cross-Origin Resource Sharing (CORS)", "MEDIUM"));
        list.add(new QuestionItem("What is Cross-Site Scripting (XSS)?", "Vulnerability where malicious scripts are injected into trusted web applications and executed by victims' browsers", "Stealing passwords from database directly", "Flooding web server with traffic", "Intercepting Wi-Fi packets", "Vulnerability where malicious scripts are injected into trusted web applications and executed by victims' browsers", "MEDIUM"));
        list.add(new QuestionItem("What security header helps mitigate XSS attacks by restricting sources from which scripts and assets can be loaded?", "Content-Security-Policy (CSP)", "Strict-Transport-Security (HSTS)", "X-Frame-Options", "Cache-Control", "Content-Security-Policy (CSP)", "MEDIUM"));
        list.add(new QuestionItem("What is Cross-Site Request Forgery (CSRF) and what is the standard defense?", "Tricking an authenticated user into executing unwanted actions; defended by Anti-CSRF tokens and SameSite cookies", "Brute-forcing login passwords; defended by captcha", "SQL injection in input fields; defended by ORM", "Man-in-the-middle attack; defended by DNSSEC", "Tricking an authenticated user into executing unwanted actions; defended by Anti-CSRF tokens and SameSite cookies", "MEDIUM"));
        list.add(new QuestionItem("What does the 'HttpOnly' flag on a cookie prevent?", "Prevents client-side scripts (JavaScript) from accessing the cookie via document.cookie", "Prevents transmitting cookie over HTTPS", "Deletes cookie on browser restart", "Restricts cookie to subdomain only", "Prevents client-side scripts (JavaScript) from accessing the cookie via document.cookie", "MEDIUM"));
        list.add(new QuestionItem("What does the 'Secure' flag on an HTTP cookie ensure?", "Cookie is only transmitted over encrypted HTTPS connections", "Cookie cannot be read by anyone", "Cookie has 256-bit encryption key", "Cookie never expires", "Cookie is only transmitted over encrypted HTTPS connections", "MEDIUM"));
        list.add(new QuestionItem("What does JWT stand for in modern web authentication, and what are its three components?", "JSON Web Token; composed of Header, Payload, and Signature separated by dots", "Java Web Tracker; Token, Hash, Salt", "JavaScript Worker Thread; ID, State, Callback", "JSON Web Transmission; Key, IV, Data", "JSON Web Token; composed of Header, Payload, and Signature separated by dots", "MEDIUM"));
        list.add(new QuestionItem("What is the JavaScript Event Loop and what is the difference between Macrotasks and Microtasks?", "Microtasks (Promises, queueMicrotask) execute before the next Macrotask (setTimeout, setInterval) in each tick", "Microtasks run in background threads; Macrotasks run on CPU", "Macrotasks cannot handle network requests", "Event loop creates a new OS thread per event", "Microtasks (Promises, queueMicrotask) execute before the next Macrotask (setTimeout, setInterval) in each tick", "MEDIUM"));
        list.add(new QuestionItem("What is Event Bubbling in the browser Document Object Model (DOM)?", "Events trigger on the innermost target element first and propagate upward through its ancestors in the DOM tree", "Events drop from window to target", "Events execute in random order", "Events are discarded after capture", "Events trigger on the innermost target element first and propagate upward through its ancestors in the DOM tree", "MEDIUM"));
        list.add(new QuestionItem("What does event.preventDefault() do in a JavaScript event handler?", "Cancels the default browser action associated with the event (e.g. form submission or link navigation)", "Stops event from bubbling up the DOM tree", "Removes the event listener", "Disables the mouse pointer", "Cancels the default browser action associated with the event (e.g. form submission or link navigation)", "MEDIUM"));
        list.add(new QuestionItem("What does event.stopPropagation() do in JavaScript?", "Prevents further propagation of the current event in the capturing and bubbling phases", "Cancels the form submit action", "Closes the current browser tab", "Disables keyboard input", "Prevents further propagation of the current event in the capturing and bubbling phases", "MEDIUM"));
        list.add(new QuestionItem("What protocol provides full-duplex, bidirectional communication channels over a single TCP connection for real-time web applications?", "WebSocket", "HTTP/1.1", "Server-Sent Events (SSE)", "FTP", "WebSocket", "MEDIUM"));
        list.add(new QuestionItem("What is the Virtual DOM used by frontend libraries like React?", "An in-memory lightweight representation of the real DOM that enables efficient batch diffing and minimal reconciliations", "A browser extension", "A virtual machine running inside Chrome", "A CSS preprocessor", "An in-memory lightweight representation of the real DOM that enables efficient batch diffing and minimal reconciliations", "MEDIUM"));
        list.add(new QuestionItem("In RESTful API design, what is an Idempotent HTTP method?", "A method that produces the same server state whether executed once or multiple times consecutively (e.g., GET, PUT, DELETE)", "A method that never returns data", "A method that executes in 0 ms", "A method that encrypts request parameters", "A method that produces the same server state whether executed once or multiple times consecutively (e.g., GET, PUT, DELETE)", "MEDIUM"));
        list.add(new QuestionItem("What is the purpose of the CSS box-sizing: border-box property?", "Includes padding and border within the specified element's width and height rather than expanding it", "Removes all margins from element", "Hides borders completely", "Converts element to flex container", "Includes padding and border within the specified element's width and height rather than expanding it", "MEDIUM"));
        list.add(new QuestionItem("What is the difference between Server-Side Rendering (SSR) and Client-Side Rendering (CSR)?", "SSR renders full HTML on server before sending to client; CSR sends minimal HTML and renders UI in browser via JavaScript", "SSR only works with PHP", "CSR does not use JavaScript", "SSR cannot connect to databases", "SSR renders full HTML on server before sending to client; CSR sends minimal HTML and renders UI in browser via JavaScript", "MEDIUM"));
        list.add(new QuestionItem("What is a Progressive Web App (PWA) and what component enables its offline capabilities?", "Web applications that behave like native mobile apps; enabled by Service Workers caching assets and requests", "App compiled to native C++", "Website running inside an iframe", "Browser plugin required to install websites", "Web applications that behave like native mobile apps; enabled by Service Workers caching assets and requests", "MEDIUM"));
        list.add(new QuestionItem("What is the difference between debounce and throttle in frontend JavaScript performance optimization?", "Debounce waits until a delay has elapsed since the last event; Throttle limits execution to at most once per time interval", "Throttle cancels all executions; Debounce executes immediately", "Debounce is built into HTML; Throttle is in CSS", "Both are identical", "Debounce waits until a delay has elapsed since the last event; Throttle limits execution to at most once per time interval", "MEDIUM"));
        list.add(new QuestionItem("What is WebAssembly (Wasm) in modern browsers?", "A binary instruction format for a stack-based virtual machine enabling near-native execution speed for languages like C++, Rust, and Go", "A replacement for HTML", "A JavaScript transpiler", "A cloud database service", "A binary instruction format for a stack-based virtual machine enabling near-native execution speed for languages like C++, Rust, and Go", "MEDIUM"));

        // 10 HARD
        list.add(new QuestionItem("How does the Critical Rendering Path (CRP) optimize web page loading speed?", "Optimizes order of DOM creation, CSSOM creation, Render Tree construction, Layout, and Paint to minimize render-blocking resources", "Disables CSS parsing until page is clicked", "Renders images before text", "Compiles HTML into machine code", "Optimizes order of DOM creation, CSSOM creation, Render Tree construction, Layout, and Paint to minimize render-blocking resources", "HARD"));
        list.add(new QuestionItem("What is the purpose of HTTP Strict Transport Security (HSTS) with the includeSubDomains and preload directives?", "Instructs browsers to strictly interact with the domain exclusively over HTTPS and submit domain to browser preloaded lists", "Blocks all search engine web crawlers", "Forces users to accept cookies", "Compresses TLS certificates", "Instructs browsers to strictly interact with the domain exclusively over HTTPS and submit domain to browser preloaded lists", "HARD"));
        list.add(new QuestionItem("How do Service Workers run in browser architecture and what limitations are placed on their execution environment?", "Run in a separate background thread without access to DOM, localStorage, or window object; communicate via postMessage", "Run inside the main UI thread with full DOM access", "Run only on the web server", "Cannot intercept fetch network requests", "Run in a separate background thread without access to DOM, localStorage, or window object; communicate via postMessage", "HARD"));
        list.add(new QuestionItem("What is the difference between Shadow DOM and standard DOM in Web Components?", "Shadow DOM provides scoped CSS styling and encapsulated DOM subtree isolation hidden from the main document", "Shadow DOM is rendered on the server only", "Shadow DOM cannot accept user input", "Shadow DOM requires React library", "Shadow DOM provides scoped CSS styling and encapsulated DOM subtree isolation hidden from the main document", "HARD"));
        list.add(new QuestionItem("What is Subresource Integrity (SRI) in HTML script and link tags?", "A cryptographic hash (e.g., sha384-...) allowing browsers to verify that fetched third-party assets have not been maliciously modified", "A license verification key for fonts", "A compression flag for CDN scripts", "An authorization token for API endpoints", "A cryptographic hash (e.g., sha384-...) allowing browsers to verify that fetched third-party assets have not been maliciously modified", "HARD"));
        list.add(new QuestionItem("In OAuth 2.0 / OpenID Connect, what is the Authorization Code Flow with PKCE (Proof Key for Code Exchange)?", "Protects mobile and single-page apps against code interception attacks by using dynamically generated code_verifier and code_challenge", "Replaces passwords with SMS codes", "Encrypts client database on server", "Disables client-side tokens", "Protects mobile and single-page apps against code interception attacks by using dynamically generated code_verifier and code_challenge", "HARD"));
        list.add(new QuestionItem("What is the difference between Server-Sent Events (SSE) and WebSockets regarding transport and connection semantics?", "SSE provides unidirectional server-to-client streaming over standard HTTP; WebSockets provide bidirectional full-duplex TCP communication", "SSE requires binary protocols; WebSockets use plain text", "SSE cannot reconnect automatically", "WebSockets are only supported in mobile browsers", "SSE provides unidirectional server-to-client streaming over standard HTTP; WebSockets provide bidirectional full-duplex TCP communication", "HARD"));
        list.add(new QuestionItem("What is the purpose of the Cache-Control: no-cache directive versus Cache-Control: no-store?", "no-cache forces validation with origin server before using cached copy; no-store forbids storing any version of the response anywhere", "no-cache means never store on disk; no-store means store only in RAM", "Both directives are completely identical", "no-cache applies only to images; no-store applies to HTML", "no-cache forces validation with origin server before using cached copy; no-store forbids storing any version of the response anywhere", "HARD"));
        list.add(new QuestionItem("What is Tree Shaking in modern JavaScript bundlers (Webpack, Rollup, Vite)?", "Dead code elimination that analyzes ES6 import/export static syntax to remove unused code exports from final bundle", "Minifying HTML comments", "Compressing PNG images using gzip", "Renaming variables to single letters", "Dead code elimination that analyzes ES6 import/export static syntax to remove unused code exports from final bundle", "HARD"));
        list.add(new QuestionItem("How does the CSS contain property (e.g., contain: layout paint) enhance browser rendering performance?", "Isolates an element's subtree from rest of page, allowing browser to calculate layout and painting without reflowing entire document", "Embeds base64 images inside CSS", "Renders CSS rules using WebGL", "Prevents user text selection", "Isolates an element's subtree from rest of page, allowing browser to calculate layout and painting without reflowing entire document", "HARD"));

        return list;
    }
}
